### ISSUE TITLE
Shadowroot only working for first item in glace card

### ISSUE THREAD

**Issue by kendrome** [thomasloven/lovelace-card-mod#102]
My Home Assistant version: 2021.1.5

My lovelace configuration method (GUI or yaml):
Glance Card example yaml -
```yaml
type: glance
entities:
  - entity: switch.living_room_tv
    tap_action:
      action: toggle
  - entity: light.livingroom_light
    tap_action:
      action: toggle
  - entity: fan.livingroom_fan
    tap_action:
      action: toggle
  - entity: switch.fireplace_light
    tap_action:
      action: toggle
```

What I am doing: Creating theme to modify the margin on glance entity state badge

What I expected to happen: Margin to be reduced to zero on all state badges

What happened instead: Margin is reduced on the first glace entity for each card and an error in javascript happens 

Screenshot of glance cards - 
![Screenshot of glance cards with margin being reduced on first element](https://user-images.githubusercontent.com/4109239/108634964-17bf2b00-7442-11eb-89f8-ee89fe565c44.png)
Screenshot of element tree in chrome - 
![Screenshot of element tree](https://user-images.githubusercontent.com/4109239/108635160-7fc24100-7443-11eb-9cd1-21c225d78d9a.png)

**Minimal** steps to reproduce: 
Theme yaml
```yaml
test:
  card-mod-theme: test
  card-mod-card-yaml: |
    ".entity$": |
      state-badge {
        margin: 0;
      }
```

Error messages from the browser console: Happens for each card visible

```
Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at HTMLElement.setStyle (card-mod.js:1)
    at async HTMLElement._setTemplate (card-mod.js:1)
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
