### ISSUE TITLE
Error in "horizontal-stack" even using "custom: mod-card"

### ISSUE THREAD

**Issue by orickcorreia** [thomasloven/lovelace-card-mod#109]
My Home Assistant version: 5.11

My lovelace configuration method (GUI or yaml): **YAML**

**What I am doing:**
I understand the problems related to the "horizontal-stack" card. However, it worked as I expected using the "custom: mod-card", but not anymore.

**What I expected to happen:**
Version 2.0.3
![image](https://user-images.githubusercontent.com/58919667/109424966-7e04fa00-79bc-11eb-9d0d-5f91708a5bce.png)

**What happened instead:**
Version 3.0.4
![image](https://user-images.githubusercontent.com/58919667/109424991-92e18d80-79bc-11eb-8743-f0d5d5aa055c.png)

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
- type: custom:mod-card
  card:
    type: horizontal-stack
    cards:

      - type: button
        tap_action:
          action: toggle
        entity: input_boolean.campainha

      - type: button
        tap_action:
          action: toggle
        entity: input_boolean.campainha

      - type: button
        tap_action:
          action: toggle
        entity: input_boolean.campainha
      
  card_mod:
    style: |
      ha-card {
        margin: 30px 10px 30px 10px;
      }

# End of code
```

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
