### ISSUE TITLE
Modification of element in shadow-root only works while switching to another tab

### ISSUE THREAD

**Issue by noxhirsch** [thomasloven/lovelace-card-mod#11]
My Home Assistant version: 0.98.1

My lovelace configuration method (GUI or yaml):
YAML

What I am doing:
I modified my map card to resize the marker as described in #8 
(Plugin & HASS up2date - all caches cleared)

What I expected to happen:
At least to resize after some seconds - or better on page load

What happened instead:
With lovelace-card-mod version 4 & 5 the style is only applied while switching to another view. As soon as I press the icon of another view, the marker resizes.

**Minimal** steps to reproduce:
Map card with following style added:

```yaml
# The least ammount of code possible to reproduce my error

      ha-entity-marker:
        $: |
          .marker {
            width: 24px!important;
            height: 24px!important;
            border: 0px!important;
            margin-top: 12px!important;
            margin-left: 12px!important;
          }

# End of code
```

Error messages from the browser console:
No errors or warnings (even in `debug_cardMod: true` mode)

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
