### ISSUE TITLE
Shadowroot not formatting secondary attribute correctly

### ISSUE THREAD

**Issue by kaizersoje** [thomasloven/lovelace-card-mod#111]
My Home Assistant version: 2021.2.3

My lovelace configuration method (GUI or yaml): YAML

What I am doing: 
I am trying to format the secondary info on a `multiple-entity-row` using the following code:

```
card_mod:
    hui-generic-entity-row:
      $: |
        .info .secondary{
          font-size: 8pt !important;
        }
```

What I expected to happen: Trying to change the font size on the secondary attribute of the row.

What happened instead: Nothing seems to be happening.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

- type: custom:multiple-entity-row
  entity: sensor.phone_connection_type
  name: Network
  card_mod:
    hui-generic-entity-row:
      $: |
        .secondary{
          font-size: 8pt !important;
        }
  entities:
    - entity: sensor.phone_ssid
      name: SSID
  secondary_info:
    entity: sensor.phone_last_update_trigger
    name: "LastUpdtTrgr:"

# End of code
```

Error messages from the browser console: None
This is the HTML code below.

![HTML](https://user-images.githubusercontent.com/54566217/109595235-3d49e400-7b68-11eb-94c4-d2770dc6aea5.png)

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
