### ISSUE TITLE
Card-mod not working properly with decluttering cards

### ISSUE THREAD

**Issue by kaizersoje** [thomasloven/lovelace-card-mod#112]
My Home Assistant version: 2021.2.3

My lovelace configuration method (GUI or yaml): YAML

What I am doing:
This is my original code:

```
- type: custom:fold-entity-row
  open: false
  head: sensor.hacs
  tap_action:
    action: navigate
    navigation_path: /hacs/installed
  card_mod:
    style: |
      :host {
      --paper-item-icon-color:
        {% if states('sensor.hacs')|int > 0 %}
          rgb(244, 208, 63)
        {% endif %}
        ;
      }
  entities:
    - type: custom:list-card
      entity: sensor.hacs
      columns:
        - {field: display_name, title: 'Name'}
        - field: installed_version
          title: Installed
          style:
            - text-align: center
        - field: available_version
          title: Latest
          style:
            - text-align: center
      feed_attribute: repositories

```
I made this as a decluttering card.

```
hacs_list_card:
  card:
    type: custom:fold-entity-row
    open: false
    head: sensor.hacs
    tap_action:
      action: navigate
      navigation_path: /hacs/installed
    card_mod:
      style: |
        :host {
        --paper-item-icon-color:
          {% if states('sensor.hacs')|int > 0 %}
            rgb(244, 208, 63)
          {% endif %}
          ;
        }
    entities:
      - type: custom:list-card
        entity: sensor.hacs
        columns:
          - {field: display_name, title: 'Name'}
          - field: installed_version
            title: Installed
            style:
              - text-align: center
          - field: available_version
            title: Latest
            style:
              - text-align: center
        feed_attribute: repositories

- type: custom:decluttering-card
  template: hacs_list_card
```

What I expected to happen: 
![hacs](https://user-images.githubusercontent.com/54566217/109636885-350d9b00-7ba0-11eb-8ee0-63a19228c221.png)

What happened instead:
The icon is not getting formatted similar to when it was not a decluttered card

![hacs2](https://user-images.githubusercontent.com/54566217/109637674-368b9300-7ba1-11eb-9c63-ef90f687d78a.png)

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
