### ISSUE TITLE
Not working on iOS and sometimes even on Edge

### ISSUE THREAD

**Issue by chemelli74** [thomasloven/lovelace-card-mod#116]
My Home Assistant version: 2021.3.1

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Modified `--icon` for 3 button cards inside a horizontal-stack

What I expected to happen: Icon to reflect code changes always and on all devices

What happened instead: sometimes a refresh of the browser ( Edge on Win10 ) shows standard icons, mostly of the time it works. Instead it never worked for mobile app ( iOS device ).
I have tried with javascript_version: latest as per troubleshooting steps but I receive:

`2021-03-07 19:48:12 ERROR (MainThread) [homeassistant.components.frontend] Please remove javascript_version from your frontend config. It is no longer supported`

**Minimal** steps to reproduce:

```yaml
    card_mod:
      style: |
        :host {
          --icon:
            {% if states('binary_sensor.custom_alexa_speaks') == 'on' %}
              mdi:volume-high;
            {% else %}
              mdi:volume-off;
            {% endif %}
          }
```

Error messages from the browser console: 

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
You need to quote the values. Also, the indentation on your closing parenthesis is off.

**Comment by chemelli74** [comment]
Tried with ' and " but both make it not working on lovelace:

```
    card_mod:
      style: |
        :host {
          --icon:
               {% if states('binary_sensor.custom_alexa_speaks') == 'on' %}
                 "mdi:volume-high";
               {% else %}
                 "mdi:volume-off";
               {% endif %}
              }
```

Can you please show me the write syntax ?

Simone

**Comment by KTibow** [comment]
Where did you find the value `--icon`?

**Comment by KTibow** [comment]
Besides, button-card has its own templating syntax. You should use that.

**Comment by chemelli74** [comment]
> Besides, button-card has its own templating syntax. You should use that.

Can you be so kind to show me the right way to go ?
Seems I was not able to find the correct info.

Thx in advance,

Simone

**Comment by chemelli74** [comment]
> Where did you find the value `--icon`?

https://github.com/thomasloven/lovelace-card-mod#changing-icons

**Comment by KTibow** [comment]
Are you sure `--icon` works with button-card?
> Seems I was not able to find the correct info.

Do a ctrl+f in the button-card readme.

**Comment by chemelli74** [comment]
> Are you sure `--icon` works with button-card?
> 
> > Seems I was not able to find the correct info.
> 
> Do a ctrl+f in the button-card readme.

Damn, I must be really blind.
Cannot find anything in card page: https://www.home-assistant.io/lovelace/button/

Simone

**Comment by KTibow** [comment]
Oh, thought you were using `custom:button-card`. Sorry; my fault. Anyway, can you put your whole button config, and a screenshot not working?

**Comment by chemelli74** [comment]
Full code:

```
cards:
  - entity: binary_sensor.custom_alexa_speaks
    hold_action:
      action: more-info
    icon_height: 100px
    name: Alexa
    show_icon: true
    show_name: true
    show_state: false
    tap_action:
      action: call-service
      service: switch.turn_off
      service_data:
        entity_id: group.group_alexa_do_not_disturb
    type: button
    card_mod:
      style: |
        :host {
          --icon:
               {% if states('binary_sensor.custom_alexa_speaks') == 'on' %}
                 mdi:volume-high;
               {% else %}
                 mdi:volume-off;
               {% endif %}
              }
  - entity: cover.tapparelle_casa_gruppo
    hold_action:
      action: more-info
    icon: 'mdi:window-shutter'
    icon_height: 100px
    name: Tapparelle
    show_icon: true
    show_name: true
    show_state: false
    tap_action:
      action: call-service
      service: cover.close_cover
      service_data:
        entity_id: cover.tapparelle_casa_gruppo
    type: button
    card_mod:
      style: |
        :host {
          --icon:
               {% if states('cover.tapparelle_casa_gruppo') == 'open' %}
                 mdi:window-shutter-open;
               {% else %}
                 mdi:window-shutter;
               {% endif %}
              }
  - entity: light.luci_casa_gruppo
    hold_action:
      action: more-info
    icon: 'mdi:lightbulb'
    icon_height: 100px
    name: Luci
    show_icon: true
    show_name: true
    show_state: false
    tap_action:
      action: call-service
      service: light.turn_off
      service_data:
        entity_id: light.luci_casa_gruppo
    type: button
type: horizontal-stack

```

From pc browser (in this moment is working):

![image](https://user-images.githubusercontent.com/57354320/110444545-7250bc00-80bd-11eb-8d72-5ef5f308d954.png)

From mobile app (not working):

![image](https://user-images.githubusercontent.com/57354320/110444741-ac21c280-80bd-11eb-945f-76930ed61d0b.png)

When it doesn't work from browser, I see the default icons like on mobile app.

Thx

Simone
