### ISSUE TITLE
Does not react to dynamic change

### ISSUE THREAD

**Issue by Wampukas** [thomasloven/lovelace-card-mod#12]
My Home Assistant version: 0.98.1

My Lovelace configuration method yaml:

What I am doing:
Trying to make dynamic image and icons color changes regarding status. It worked in version 3.

What I expected to happen:
Change background image and icons colors on status change.

What happened instead:
Nothing

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
            style: |
               ha-card {
                 --paper-item-icon-color: white;
                 --primary-text-color: white;
                 --secondary-text-color: white;
                 background-image: url("/local/lovelace/home/weather-background-[[ sun.sun.state ]].gif");
               }
or another example:

                style: |
                  ha-card {                
                    border-radius: 20px;
                    box-shadow: 3px 3px rgba(0,0,0,0.4);
                    overflow: hidden;
                    --paper-item-icon-color: [[ if(sensor.life360_vytautas_phone_charging_state == "True", "#64FE2E", if(sensor.life360_vytautas_battery <= 25, "red", if(sensor.life360_vytautas_battery <= 50, "orange", "green"))) ]];


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x ] Have made sure I am using the latest version of the plugin.

[x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
