### ISSUE TITLE
Browser running out of ressources with card_mod

### ISSUE THREAD

**Issue by Hooorny** [thomasloven/lovelace-card-mod#120]
My Home Assistant version: core-2021.3.4

My lovelace configuration method (GUI or yaml): tried both

What I am doing: Styling auto-entities card inside horizontal stack

What I expected to happen: Same fast browser interaction as always

What happened instead: Browser is getting slower until not responding

**Minimal** steps to reproduce:
![card](https://user-images.githubusercontent.com/1502201/111422631-43ef6400-86ef-11eb-8fd9-46a90d3ef0d4.png)
![inspektor](https://user-images.githubusercontent.com/1502201/111422636-45209100-86ef-11eb-8db3-5696cea4eada.png)

One of the sensors shows "live" consumption values and it seems the css stack grows with each change ...

```yaml
# The least amount of code possible to reproduce my error
type: horizontal-stack
cards:
  - type: 'custom:auto-entities'
    show_empty: false
    card:
      type: glance
      card_mod:
        style: |
            ha-card {
              box-shadow: none;
              background: transparent;
            }
      show_state: true
      show_name: false
      columns: 5
    filter:
      include:
        - entity_id: sensor.bwwp_status
        - entity_id: sensor.wgt_status
        - entity_id: device_tracker.oneplus_3t
        - entity_id: sensor.tv_status
        - entity_id: sensor.onkyo_status
      exclude:
        - state: aus
        - state: home
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
