### ISSUE TITLE
When used with auto-entities card, styling changes do not persist

### ISSUE THREAD

**Issue by akeslo** [thomasloven/lovelace-card-mod#122]
My Home Assistant version: Home Assistant 2021.3.4

My lovelace configuration method (GUI or yaml): GUI

What I am doing: 
- Using card-mod to change the background color of an auto entities card

What I expected to happen:
- Card background color changes and remains consistent

What happened instead:
- Card shows the correct background color on load but when the auto entities card updates in real time the background color reverts to the original color

![image](https://user-images.githubusercontent.com/3003773/112403604-1c972900-8ce5-11eb-9622-ead8d405bcc0.png)
![image](https://user-images.githubusercontent.com/3003773/112403628-26209100-8ce5-11eb-8b2c-1a7f4085bffd.png)

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
type: 'custom:auto-entities'
show_empty: false
card:
  type: entities
  state_color: false
  style: |
    ha-card {
      background-color: #C2F970;
      color: black;
    }
    .card-content {
      background-color: #C2F970;
      color: black;
    }
    :host {
      --paper-item-icon-color: black;
    }
filter:
  include:
    - domain: switch
      state: 'on'
    - domain: light
      state: 'on'
    - domain: group
      state: 'on'
    - domain: fan
      state: 'on'

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Your code example is not working.

**Comment by bcmitri** [comment]
I'm experiencing the same issue.  Here is a sample of my code, using entities from the Environment Canada integration:
`card:
  columns: 1
  show_icon: false
  show_name: false
  style: |
    ha-card {
      background-color: rgba(251,13,13,1);
      border-radius: 5px;
      --primary-color: white;
      --paper-item-icon-color: white;
    }      
  type: glance
filter:
  exclude:
    - state: ''
  include:
    - entity_id: sensor.advisories
    - entity_id: sensor.statements
    - entity_id: sensor.warnings
    - entity_id: sensor.watches
show_empty: false
type: 'custom:auto-entities'

**Comment by akeslo** [comment]
> Your code example is not working.

Updated the code to show the full card

**Comment by thomasloven** [comment]
I can reproduce this when using
```yaml
card:
  style: |
    ha-card {
      ...
```

But not with
```yaml
card:
  card_mod:
    style: |
      ha-card {
        ...
```
which is the new syntax.

So that's a wont-fix.

See release notes for card-mod 3.0 (https://github.com/thomasloven/lovelace-card-mod/releases/tag/3.0.0), but note that that is not the latest release.

**Comment by Sepulnation** [comment]
Hi, did you solve this problem? Thx

**Comment by maxi1134** [comment]
Hi there,

I have this same issue with the two following codes:

![image](https://github.com/thomasloven/lovelace-card-mod/assets/1342643/22170569-1af6-4d1b-9cb3-3654cd499179)
![image](https://github.com/thomasloven/lovelace-card-mod/assets/1342643/1fc00551-8fc0-408e-a7b1-7d14f545a532)


Any help would be welcomed!

**Comment by ildar170975** [comment]
Suggest you to always provide a code (not just a screenshot).

**Comment by maxi1134** [comment]
This seems to work:

```
type: custom:auto-entities
card:
  type: entities  
  card_mod:
    style: |
      ha-card {
        color: red;
      }
  cards: 
    type: entity
  layout_type: custom:grid-layout
  layout:
    grid-template-columns: 50% 50%
    grid-template-rows: auto
filter:
  include:
    - domain: '*'
      entity_id: '*motion_occupancy'
    - entity_id: '*entry'
sort:
  method: last_changed
  reverse: true
  ignore_case: false
  numeric: false
show_empty: true

```

![image](https://github.com/thomasloven/lovelace-card-mod/assets/1342643/677816fe-f596-4068-a11f-87eed8c2b03a)


Any idea on how to get it to work with the layout card?
