### ISSUE TITLE
Strange behavior when setting margins and using config-template-card together

### ISSUE THREAD

**Issue by Veuchez** [thomasloven/lovelace-card-mod#126]
My Home Assistant version:
core-2021.4.3

My lovelace configuration method (GUI or yaml): 
GUI

What I am doing:
I placed the button correctly with the styles

What I expected to happen:
I expect that once correctly positioned it will always stay in place.

What happened instead:
When I change state to a value the button moves and then returns to the position assigned with the styles.
In my opinion it depends on the simultaneous use with config-template-card.

![termostato](https://user-images.githubusercontent.com/59020055/114458782-f37d0080-9bdf-11eb-808c-59d5a99b2bee.gif)

**Minimal** steps to reproduce:

```yaml
type: 'custom:config-template-card'
variables:
  LANG_STATE: 'states[''input_select.smarther_studio_language''].state'
entities:
  - input_select.smarther_studio_language
card:
  color: auto
  confirmation:
      text: "${vars[0] === 'EN' ? 'Are you sure you want to enable/disable Webhooks?' : vars[0] === 'IT' ? 'Sei sicuro di voler attivare/disattivare i Webhooks?' : 'no language'}"
  style: |
    ha-card {
      margin-top: -4px;
      height: 25px !important;
      width: 165px !important;
      box-shadow: 0px 0px;
      #border-style: solid;
      border-radius: 0px !important;
      margin-left: -24px !important;
      padding-right: 5px !important;
    }
    ha-icon {
     color: {% if is_state('automation.smarther_webhook_update', 'on') %} green !important {% else %} red!important {% endif %};  
     margin-left: 5px !important;
    }
    #name {
      #max-width: 50%;
      margin-left: -20px !important;
      justify-self: left !important;
      /* margin: auto; */

    }
    #container {
      display: grid;
      #width: 100% !important;
      height: 15px !important;
      text-align: left !important;
      align-items: left !important;
      margin-top: 0px !important;
      #border-style: solid;
    }
  entity: sensor.smarther_webhookdelay_studio
  show_state: true
  show_name: true
  layout: icon_name_state
  icon: 'mdi:timer-sand'
  name: LAST DELAY
  tap_action:
    action: call-service
    service: automation.toggle
    service_data:
      entity_id: automation.smarther_webhook_update
  size: 30px
  styles:
    card:
      - font-size: 10px
  type: 'custom:button-card'

```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
