### ISSUE TITLE
HA 2021.6: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#128]
My Home Assistant version: 2021.6.0b0

My lovelace configuration method (GUI or yaml):
Yaml
What I am doing:
clicking for more-info on an entity
What I expected to happen:
no error in Inspector
What happened instead:

<img width="611" alt="Schermafbeelding 2021-05-27 om 23 09 02" src="https://user-images.githubusercontent.com/33354141/119897377-9b584e80-bf40-11eb-9da5-c34118d857fd.png">

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - type: entities
    title: Temp indices
    entities:
      - sensor.temp_current
      - sensor.mean_outdoor_temp
# End of code
```

Error messages from the browser console:
```
Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at HTMLElement.e.showDialog (card-mod.js?v=3.0.12:5)
    at o (app.e6fe3e32.js:34269)
```
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
