### ISSUE TITLE
Markdown and themes - style doesn't stick

### ISSUE THREAD

**Issue by matt8707** [thomasloven/lovelace-card-mod#130]
My Home Assistant version: 
2021.6.0

My lovelace configuration method (GUI or yaml): 
yaml

What I am doing: 
styling markdown from themes

What I expected to happen: 
style to be applied

What happened instead: 
style doesn't apply until I have the dashboard open, and call frontend.reload_themes from a different tab. Next time I open the dashboard the style is gone.

**EDIT:** Issue started on 2021.6.0, and styling from the card and not from themes works, but impacts performance 
https://user-images.githubusercontent.com/36163594/120754416-ea881b80-c50c-11eb-8e5e-2fcf54c446f7.mp4

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
views:
  - title: Home
    cards:
      - type: markdown
        content: |-
          red

          green

          blue


#themes.yaml
card-mod-view-yaml: |
  hui-masonry-view $ hui-markdown-card $ ha-markdown $: |
    p {
      color: green;
    }
    p:first-of-type {
      color: red;
    }
    p:last-of-type {
      color: blue;
    }
# End of code
```

Error messages from the browser console: 
none

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
