### ISSUE TITLE
new history-graph has issues with margin mod

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#140]
My Home Assistant version: 2021.8.8

My lovelace configuration method (GUI or yaml):
 Yaml

What I am doing:
 modding the margin of history-graph as entity in an entities card, which has been working for a long time, and started misbehaving since the new history-graph (or 2021.8, not 100% sure about that)

What I expected to happen:
 stay within the total entities card's width

What happened instead:

the mod changes to full width, and overlaps with other cards

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - type: entities
    entities:
      - 
      - type: custom:hui-element
        card_type: history-graph
        card_mod:
          style: |
            ha-card {
              box-shadow: none;
              margin: 0px -16px 0px -16px;
            }
        entities:

# End of code
```

Error messages from the browser console:
---
No errors.

see: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2098

with the mod the card now shows like:

<img width="494" alt="Schermafbeelding 2021-08-19 om 00 08 03" src="https://user-images.githubusercontent.com/33354141/130088971-7de6dab4-376e-4427-bf1e-907aa1b74355.png">

using smaller margin changes, work on the first reload, but a second reload immediately makes the entities card go beyond its border
happening in Safari and Chrome , and the iOS App

so only without mod I can have the card use the correct outer margins, but of course the graphs now are not optimally using their available width

<img width="415" alt="Schermafbeelding 2021-08-19 om 16 45 15" src="https://user-images.githubusercontent.com/33354141/130089667-78068a8c-63cf-44de-96ad-8ee2427a1b5e.png">

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
