### ISSUE TITLE
r.setconfig is not a function

### ISSUE THREAD

**Issue by IIIdefconIII** [thomasloven/lovelace-card-mod#141]
My Home Assistant version: 0.XX.X
Home Assistant 2021.8.8

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Adding a new card

What I expected to happen:
the card-mod to work, whenever i add the card im gettings this error, i tried another browser (read it from other forums), searched in youre repo for solved issues, but couldnt fint the real problem. many thanks for your hard work do!

What happened instead:
getting the error r.setconfig is not a functio

**Minimal** steps to reproduce:
install Home Assistant 2021.8.8
add card-mod.js to lovelace resources
create a card:
```
type: 'custom:card-mod'
style: |
  ha-card {
    --ha-card-background: teal;
    color: var(--primary-color);
  }
```

```yaml
# The least amount of code possible to reproduce my error
type: 'custom:card-mod'
style: |
  ha-card {
    --ha-card-background: teal;
    color: var(--primary-color);
  }
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- x Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- x Have made sure I am using the latest version of the plugin.

- x Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- x Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

![afbeelding](https://user-images.githubusercontent.com/9917659/131183763-c31e59c0-cc1a-4f67-a6ed-5cc629d0007c.png)
![afbeelding](https://user-images.githubusercontent.com/9917659/131183796-96a2eb0c-4cd1-49d7-a79e-edae2b3d536a.png)
![afbeelding](https://user-images.githubusercontent.com/9917659/131183962-9bd4f71c-6563-4093-9e61-86614b0c8415.png)
![afbeelding](https://user-images.githubusercontent.com/9917659/131219505-aec172fc-858e-4fb3-9358-7bfc14b46c4c.png)

**Comment by IIIdefconIII** [comment]
changed the card to:

```
type: picture-elements
elements:
  - type: state-label
    entity: sensor.tram_23
    attribute: name
    icon: mdi:tram
    style:
      top: 25%
      left: 10%
      '--paper-item-icon-color': white
  - type: state-icon
    entity: sensor.tram_23_future_4_templated
    icon: mdi:tram
    style:
      top: 65%
      left: 10%
      '--paper-item-icon-color': white
  - type: state-label
    entity: sensor.tram_23_templated
    style:
      top: 85%
      left: 10%
  - type: state-label
    entity: sensor.tram_23_future_1_templated
    style:
      top: 85%
      left: 25%
  - type: state-label
    entity: sensor.tram_23_future_2_templated
    style:
      top: 85%
      left: 40%
  - type: state-label
    entity: sensor.tram_23_future_3_templated
    style:
      top: 85%
      left: 55%
  - type: state-label
    entity: sensor.tram_23_future_4_templated
    style:
      top: 85%
      left: 70%
image: /local/images/tram.png
```
