### ISSUE TITLE
Errors in browser console after update HA to 0.101

### ISSUE THREAD

**Issue by bieniu** [thomasloven/lovelace-card-mod#15]
My Home Assistant version: 0.101.X

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
After update HA to 0.101 I have errors in browser console with card-mod:
![image](https://user-images.githubusercontent.com/478555/68011815-978f1800-fc88-11e9-8a7b-310ebd8b42cb.png)
and vertical-stack-in-card cards rendering is invalid (when I disable card-mod everything is normal)
![image](https://user-images.githubusercontent.com/478555/68012160-8eeb1180-fc89-11e9-8d71-92d1e49f470a.png)

What I expected to happen:
no errors, correct rendering vertical-stack-in-card cards

**Minimal** steps to reproduce:
- update HA to 0.101
- add some style from card-mod

```yaml
resources:
 - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
...
...
- type: custom:vertical-stack-in-card
  title: "Kuchnia"
  cards:
    - type: glance
      show_name: false
      entities:
        - sensor.temperature_kuchnia
        - sensor.humidity_kuchnia
    - type: entities
      show_header_toggle: false
      entities:
        - binary_sensor.window_kuchnia
        - climate.thermostat_kuchnia
        - entity: sensor.dishwasher_kuchnia
          style: |
            :host {
              --paper-item-icon-color:
                {% if states(config.entity) == "zmywanie" %}
                  var(--state-icon-active-color)
                {% else %}
                  var(--state-icon-color)
                {% endif %}
            }
```

Error messages from the browser console:
```
Uncaught (in promise) TypeError: Cannot read property 'style' of undefined
    at /community_plugin/lovelace-card-mod/card-mod.js:1
    at NodeList.forEach (<anonymous>)
    at HTMLElement.customElements.get.firstUpdated (/community_plugin/lovelace-card-mod/card-mod.js:1)
    at HTMLElement.performUpdate (/frontend_latest/app.34e7b19f.js:2)
    at HTMLElement._enqueueUpdate (/frontend_latest/app.34e7b19f.js:2)
```
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
