### ISSUE TITLE
Individual styling of entities does not work

### ISSUE THREAD

**Issue by i00** [thomasloven/lovelace-card-mod#16]
My Home Assistant version: 0.101.3

My lovelace configuration method (GUI or yaml):
```yaml
type: entities
entities:
  - entity: device_tracker.XXXX1
  - entity: device_tracker.XXXX2
style: |
  :host {
    color: {% if is_state(config.entity, 'Away') %}black{%else %}blue{% endif %};
  }
```

What I am doing:
Trying to color text in rows of an entities card

What I expected to happen:
Rows to be colored

What happened instead:
Rows are not colored

```yaml
# See Above
```

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
