### ISSUE TITLE
3.1.0: no more mod-card config

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#160]
My Home Assistant version: 0.XX.X
2021.11.5
My lovelace configuration method (GUI or yaml):
Yaml
What I am doing:
using a mod-card config
What I expected to happen:
show the mod-card config
What happened instead:
no show
**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - type: custom:mod-card
    card_mod:
      style: |
        ha-card {
          margin: -8px -16px -16px -16px;
        }
    card:
      type: custom:hui-element
      card_type: history-graph
      hours_to_show: 48
      refresh_interval: 60
      entities:
# End of code
```

Error messages from the browser console:

---
No error, though I briefly saw the error message in the frontend card, 'no mod-card available'

tried in Firefox, Safari and Chrome on Mac

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
