### ISSUE TITLE
Problem in Android / iOS app

### ISSUE THREAD

**Issue by altapo** [thomasloven/lovelace-card-mod#167]
My Home Assistant version: core-2021.12.1

My lovelace configuration method (GUI or yaml): yaml

What I am doing: In Android / iOS app the styles in the example do not work

What I expected to happen (works in browser):
![photo_2021-12-15_12-12-52](https://user-images.githubusercontent.com/837355/146140811-07c97900-e96e-4c88-8894-8ef13a01fe37.jpg)

What happened instead (doesn't work in Android / iOS app):
![photo_2021-12-15_12-05-12](https://user-images.githubusercontent.com/837355/146140831-fd421f44-a650-4b93-afa5-972f3daf61f6.jpg)

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - type: custom:multiple-entity-row
    entity: group.light_room
    name: Room
    icon: mdi:sofa-outline
    secondary_info:
      entity: group.light_room
      name: false
    state_color: true
    show_state: false
    card_mod:
      style:
        hui-generic-entity-row$:
          .: |
            :host {
              flex-wrap: wrap;
            }
            state-badge {
              line-height: 30px;
              break-after: always;
            }
            .info {
              margin-left: 0;
            }
          state-badge$:
            ha-state-icon$:
              ha-icon$: |
                ha-svg-icon {
                  width: 30px;
                  height: 30px;
                }
```

Error messages from the browser console: no

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by altapo** [comment]
Problem solved

```yaml
card_mod:
  style:
    hui-generic-entity-row$:
      .: |
        :host {
          flex-wrap: wrap;
        }
        state-badge {
            min-width: 100%; <--- ADD
            text-align: left; <--- ADD
            line-height: 30px;
            break-after: always;
        }
        .info {
          margin-left: 0 !important; <--- ADD IMPORTANT
        }
      state-badge$:
        ha-state-icon$:
          ha-icon$: |
            ha-svg-icon {
              width: 30px;
              height: 30px;
            }
```
