### ISSUE TITLE
card mod paper-item-icon-color does not change color on dark or custom theme (after HA upgrade to 2021.12.0)

### ISSUE THREAD

**Issue by kodifan** [thomasloven/lovelace-card-mod#168]
My Home Assistant version: 2021.12.0

My lovelace configuration method (GUI or yaml): GUI

Not sure that is connected with this integration or this happened after upgrading HA to 2021.12.0 version but on previous version all worked as expected but now color icon works only on light default theme - on dark theme or any custom theme icons are all the same color. 
What is more strange, it does not work only on buttons , on the list of entities there is no problem. 
I attach 2 screenshots with examlpes.

![light_theme](https://user-images.githubusercontent.com/7819312/146387768-6db91b90-91e9-4b01-bb97-508c4b2c85c3.png)
![dark_theme](https://user-images.githubusercontent.com/7819312/146387766-e246085a-1522-4400-bc58-96dd96fd1d16.png)
 ![custom_theme](https://user-images.githubusercontent.com/7819312/146389082-6d9cb907-189a-43f9-b8de-2afe7de4f600.png)

**Comment by nenadmilano** [comment]
The font color also seems to not adapt when switching themes (day / night) and always stays like it was bevore. Happens only to cards which I modify with card-mod.

**Comment by kodifan** [comment]
Yes definitely  2021.12.0 HA update broke something. On every device I use all is working fine until message "new fronted is available, please reload" . I updated lately to newest 2021.12.4 version but it did not helped. 
Either way i think this integration must be adapted to new HA fronted, they wont ix it...

**Comment by ildar170975** [comment]
Many pics & no code - how people are supposed to help?

**Comment by ildar170975** [comment]
> Happens only to cards which I modify with card-mod.

If you hardcoded some colors or font-sizes - no wonder they are not changing after switching themes.
We can only guess since you provided no code.

**Comment by ildar170975** [comment]
> What is more strange, it does not work only on buttons , on the list of entities there is no problem.

What buttons are you talking about?
If it is `custom:button-card` - do you use `card-mod` inside or it's own `style` feature?
If second - ask about it in `custom:button-card` repository.
Again, you provided no code.

**Comment by nenadmilano** [comment]
> > Happens only to cards which I modify with card-mod.
> 
> If you hardcoded some colors or font-sizes - no wonder they are not changing after switching themes. We can only guess since you provided no code.

So I hardcoded some font sizes with card-mod (code snippet below) but it seems that the change of the font color is somehow disabled since the last HA major release. I have two themes, one for night and one for day where the font color is either dark or light grey but this change is not triggered by the theme change - i manually have to refresh the Dashboards on my iPads (pull-down refresh) to get the font color changed.

```
            - entities:
                - entity: sensor.office_iaq_level
                  name: Air Quality
                - entity: sensor.netatmo_milkain_arbeitszimmer_temperature
                  name: Temperatur
                #- entity: sensor.temp_diff_az
                #  name: Temp. Diff.
                #- entity: sensor.lueften_az
                #  name: Lüften?
                - entity: sensor.netatmo_milkain_arbeitszimmer_humidity
                  name: Luftfeuchtigkeit
                - entity: sensor.netatmo_milkain_arbeitszimmer_co2
                  name: CO2
                - entity: fan.air_purifier
                #- entity: sensor.netatmo_milkain_arbeitszimmer_battery_percent
                #  name: Batterie
                - entity: sensor.total_energy_consumption
                  #icon: 'mdi:solar-power'
                  name: Energy need
                - entity: sensor.efriends_power_distribution
                  #icon: 'mdi:solar-power'
                  name: Source
              show_header_toggle: false
              title: "\U0001F4BB  Office  \U0001F321"
              state_color: true
              type: entities
              card_mod:
                style: |
                  ha-card {
                    font-size: 20px;
                  }
```

let me know if you need more code or logs for debugging.
Thanks for your support!
