### ISSUE TITLE
card-mod-themes: "class" is not set for a row

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-card-mod#172]
My Home Assistant version: 2021.12.7

My lovelace configuration method (GUI or yaml): yaml/GUI

What I am doing:
Trying to use these method:
https://github.com/thomasloven/lovelace-card-mod/wiki/Card-mod-Themes#classes
1. Specified a theme for rows of some class.
2. Set this class for some row.

What I expected to happen:
The style is applied to the row.

What happened instead:
The style is NOT applied to the row.
![изображение](https://user-images.githubusercontent.com/71872483/147709869-dac8f6c1-5ca7-4a7a-a922-6ab919a3320a.png)

**Minimal** steps to reproduce:
```
  card-mod-row: |
    :host(.class-row-red) {
      color: red;
      --paper-item-icon-color: red;
    }
```
```
  - type: entities
    entities:
      - entity: input_number.test_number
        class: class-row-red
```

What I see in Code Inspector:
![изображение](https://user-images.githubusercontent.com/71872483/147709896-6eedbba6-ce4d-4cf6-96bf-ee58905b9b32.png)

If I set the class manually:
![изображение](https://user-images.githubusercontent.com/71872483/147709913-f6558ee0-7331-42f8-8208-6997507eddb1.png)
then the style is applied:
![изображение](https://user-images.githubusercontent.com/71872483/147709922-bfa50988-535c-4f80-8e14-b507f9a0a401.png)

Error messages from the browser console:
none
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Got it working!
```
  - type: entities
    entities:
      - entity: input_number.test_number
        card_mod:
          class: class-row-cyan
```
Use the `class` under the `card_mod` keyword.
