### ISSUE TITLE
Errors in log & Code Inspector when using card-mod-theme

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-card-mod#180]
My Home Assistant version: 2022.2.9

My lovelace configuration method (GUI or yaml): yaml/storage

What I am doing:
Applying styles by card-mod theme.
The main idea is to highlight `unavailable` entities.
To simulate an `unavailable` entity, a template sensor is created.

What I expected to happen:
Styles are applied w/o errors.

What happened instead:
Styles are applied, there are errors in the log and in the Code Inspector.

**Minimal** steps to reproduce:
1) Create a theme:
```
cm_minimal:

  card-mod-row-yaml: |
    .: |

      :host(.class-row-red) {
        color: red;
        --paper-item-icon-color: red;
      }

      hui-generic-entity-row .text-content {
        {% if states(config.entity) in ['unavailable','unknown'] %}
          color: magenta;
        {% endif %}
      }
```

2) Create a template sensor:
```
sensor:
  - platform: template
    sensors:
      service_unavailable_value:
        icon_template: mdi:null
        value_template: "{{ 'unavailable' }}"
```

3) Create a card:
```
type: entities
entities:
  - entity: sun.sun
  - entity: zone.home
    card_mod:
      class: class-row-red
  - entity: sensor.service_unavailable_value
```

4) The card looks like:
![изображение](https://user-images.githubusercontent.com/71872483/154819401-0981ce66-e9ca-4df6-9453-0a5a49572af3.png)

5) Check that the styles are applied properly.
For the `unavailable` entity the style is applied as below:
![изображение](https://user-images.githubusercontent.com/71872483/154819639-c9fe08d0-b079-4032-9161-8cbe7176c44e.png)

6) See errors in the log:
```
2022-02-20 00:02:45 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'entity' when rendering ':host(.class-row-red) {
color: red;
--paper-item-icon-color: red;
}
hui-generic-entity-row .text-content {
{% if states(config.entity) in ['unavailable','unknown'] %}
color: magenta;
{% endif %}
}'
```

Error messages from the browser console:
![изображение](https://user-images.githubusercontent.com/71872483/154819424-650863c8-e4b1-4214-871d-e338a1ecdb72.png)

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
