### ISSUE TITLE
Detecting Dark Mode

### ISSUE THREAD

**Issue by fusionstream** [thomasloven/lovelace-card-mod#181]
Would be cool to be able to detect dark mode. That way one can have separate color palettes for light and dark mode

**Comment by ildar170975** [comment]
...or you can define different variables in your themes instantly:
```
my_theme:

  modes:
    light:
      user-bar-card-fill-color: red
      ...

    dark:
      user-bar-card-fill-color: green
      ...
```
