### ISSUE TITLE
entities cards need extra refesh for theme to load correctly (using card-mod-theming)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#183]
My Home Assistant version: 2022.4.0.dev20220226

My lovelace configuration method (GUI or yaml): Yaml
Card-mod 3.2.1 installed via
```
frontend:
  themes: !include_dir_merge_named /config/frontend_themes

  extra_module_url:
    - /local/lovelace/resources/lovelace-card-mod/card-mod.js
```

What I am doing:
related to https://github.com/home-assistant/frontend/issues/10988#issuecomment-1052134096

changing themes in Lovelace, and have card-mod-theme in place

What I expected to happen:

all cards changing theme

What happened instead:

when changing themes, entities cards need an extra refresh to load the new theme. A reload of the page solves this.
**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error, having 

Dark blue:

  <<: &generic
    card-mod-theme: custom-header
# rest of these settings
# End of code
```

Error messages from the browser console:

---

with card-mod-theme line, needs reload for theme change on entities:

![Feb-26-2022 16-51-41](https://user-images.githubusercontent.com/33354141/155849675-af155397-f23b-4bb6-a065-c7db806e25f6.gif)

without, direct theme change on all, including entities:

![Feb-26-2022 16-54-25](https://user-images.githubusercontent.com/33354141/155849754-50485e65-71ab-45cf-8629-23070cdfb7ec.gif)

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
