### ISSUE TITLE
mod-card needs resize before kicking in when used with auto-entities

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#184]
My Home Assistant version: 2022.4.0.dev20220228

My lovelace configuration method (GUI or yaml): YAML

What I am doing:

showing badge card which is auto-filled by auto-entities and justify the badges

What I expected to happen:

immediate effect (as before, somehow latest are releases frustrate correct operation)

What happened instead:

need a resize window in the browser to have the mod be effective, ast least showing the mod is ok.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
        entities:
          - type: custom:mod-card 
            card_mod:
              style:
                badge-card:
                  $: |
                    div#badges {
                      display: flex;
                      justify-content: space-around;
                    }
            card:
              type: custom:auto-entities
              card:
                type: custom:badge-card
# End of code
```

using a fixed set of badges:
```
  - type: custom:badge-card
    card_mod:
    style: |
      div#badges {
        display: flex;
        justify-content: space-around;
      }
    badges:
      - sensor.weather_animated_icon
      - sensor.badge_wind_compass
      - sensor.wind_bft
  ```

always works, proving the mod to be correct

Error messages from the browser console:

no errors

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
