### ISSUE TITLE
SyntaxError: The string did not match the expected pattern

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#199]
My Home Assistant version: 2022.6.0.dev20220430

My lovelace configuration method (GUI or yaml): Yaml

What I am doing:

card-mod-theming an icon in a view/tab

What I expected to happen:

icon change

What happened instead:

no icon change because of space in the view title

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
    card-mod-root-yaml: |
      paper-tab[aria-label='Weer & Klimaat'] ha-icon$: |
        ha-svg-icon {
          --card-mod-icon: {{states('sensor.weather_icon')}};
          color: {{states('sensor.temperature_color_name')}};
        }
# End of code
```

doesn't mater if I simply add `mdi:car`; its not about the icon template, its really about the view title, because:

```
      paper-tab[aria-label='Alarm'] ha-icon$: |
        ha-svg-icon {
          --card-mod-icon: {{states('sensor.alarm_panel_icon')}};
          color: {{states('sensor.alarm_panel_icon_color')}};
        }
```

woks perfectly.

Error messages from the browser console:
<img width="704" alt="Schermafbeelding 2022-04-30 om 10 42 03" src="https://user-images.githubusercontent.com/33354141/166098604-7b76af56-bdbd-4a49-b669-ede2ff9c5824.png">

I have also tested it under:
```
      .: |
        /* Set the color of individual tabs. */
        paper-tab[aria-label='Alarmclock'] {
          color: {{'red' if states('sensor.next_alarm') != 'Not set'}};
        }
but in that section, only the colors change, and not the icons.

Finally, I also tried the space indicator `&nbsp` to have it evaluate
```
 paper-tab[aria-label='Weer&nbsp&&nbspKlimaat']
```

but that took the instance down ....

Please have a look if this can be fixed
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
