### ISSUE TITLE
Not working with vertical stack

### ISSUE THREAD

**Issue by klejejs** [thomasloven/lovelace-card-mod#2]
My Home Assistant version: 0.95.4

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
I am trying to add green background to vertical stack

What I expected to happen:
Green background to vertical stack

What happened instead:
Nothing

This is my code:

```yaml
- type: vertical-stack
  style: |
    #root {
      background: green
    }
```
