### ISSUE TITLE
Can't select DOM elements inside state-history-charts

### ISSUE THREAD

**Issue by Madelena** [thomasloven/lovelace-card-mod#200]
My Home Assistant version: 2022.5.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
I'm attempting to theme the History Chart within a More Info dialog.

What I expected to happen:
I should be able to style the chart.

What happened instead:
Card-mod is not inserted into the DOM, because the DOM elements were not created when the dialog was first open.

**Minimal** steps to reproduce:

This will insert Card-mod under <state-history-charts> within a More Info dialog just fine.
```yaml
  card-mod-more-info-yaml: &card-mod-more-info-yaml |
    ha-more-info-history$state-history-charts: |
      .chartTooltip {
        margin-top: -200px;
      }
```

![DOM Preview](https://i.imgur.com/Zv1aWTc.png)

But it cannot find the shadow-root within if I add a $ in the path:
```yaml
  card-mod-more-info-yaml: &card-mod-more-info-yaml |
    ha-more-info-history$state-history-charts$: |
      .chartTooltip {
        margin-top: -200px;
      }
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
