### ISSUE TITLE
Styling of cards isn't applied until Edit/Save of dashboard

### ISSUE THREAD

**Issue by mwilky** [thomasloven/lovelace-card-mod#208]
My Home Assistant version: 0.XX.X

Home Assistant Core 2022.6.4

My lovelace configuration method (GUI or yaml):

GUI

What I am doing:
Worked perfectly fine before recent HA upgrade. The styling doesnt apply until you edit and then save your dashboard. Going to a second dashboard and then returning put the style back in its broke state. You have to edit and save again to fix

What I expected to happen:

![Working](https://user-images.githubusercontent.com/5043227/172825304-5b4fba45-1221-4cbe-8b99-e4d4bb23edfc.PNG)

What happened instead:

![Not Working](https://user-images.githubusercontent.com/5043227/172825339-b4d6f7fa-1ee2-410a-a3e4-1a5490bcc318.PNG)

**Minimal** steps to reproduce:

```yaml
content: |
  # Kitchen
style:
  .: |
    ha-card {
      --ha-card-background: none !important;
      box-shadow: none !important;
      margin-top: 50px;
      margin-bottom: -15px;
      margin-left: 15px;

    }
  ha-markdown:
    $: |
      ha-markdown-element {
        letter-spacing: 0;
      }
      h1 {
        font-size: 20px !important;
        font-weight: 400;
      }
type: markdown

```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
