### ISSUE TITLE
Need help dynamically changing my card based on HA theme (dark/light)

### ISSUE THREAD

**Issue by vaibhav2912** [thomasloven/lovelace-card-mod#209]
Hello,

I have created a card to show status of my washing machine. I used images instead of icons because I wanted to animate. I am currently using dark theme and so I created images with white color. Everything works perfectly.
But when I switch over to light theme, understandably, I can't see my picture at all because white picture on white background.

Is there a way to change the picture I use based on HA theme?

![2022-06-11_16-56-14](https://user-images.githubusercontent.com/20019445/173204672-f24bd251-d918-4a65-9d51-9ad3a2950fad.gif)
```
type: custom:button-card
entity: sensor.washer_switchbot_plug_2_energy_power
show_icon: false
triggers_update:
  - sensor.washer_switchbot_plug_2_energy_power
tap_action:
  action: none
entity_picture: /local/floor_plan/assets/washing-machine-clothes.png
show_entity_picture: true
name: |
  [[[
      if (states['sensor.washer_switchbot_plug_2_energy_power'].state > 4)
          return "Washing";
      else
          return "Idle";
  ]]]
state:
  - value: 4
    operator: <
    spin: 0
    styles:
      entity_picture:
        - top: 48%
        - left: 35%
        - width: 28%
      name:
        - font-size: 30px
        - height: 80%
      card:
        - width: 145px
        - height: 170px
      grid:
        - position: relative
      custom_fields:
        notification:
          - position: absolute
          - left: 0%
          - top: 0%
          - width: 140px
          - size: 40%
    custom_fields:
      notification: |
        [[[
          return `<img src='/local/floor_plan/assets/washing-machine_frame.png'"
                  style="width: 130px; height: 130px;">`
        ]]]
  - value: 4
    operator: '>'
    spin: 1
    styles:
      entity_picture:
        - top: 46%
        - left: 35%
        - width: 28%
      name:
        - font-size: 26px
        - height: 100%
      card:
        - width: 145px
        - height: 170px
      grid:
        - position: relative
      custom_fields:
        notification:
          - position: absolute
          - left: 0%
          - top: 0%
          - width: 140px
          - size: 40%
    custom_fields:
      notification: |
        [[[
          return `<img src='/local/floor_plan/assets/washing-machine_frame.png'"
                  style="width: 130px; height: 130px;">`
        ]]]
```

Thank you,
Vaibhav
