### ISSUE TITLE
Style only updates when I do a reload to lovelace

### ISSUE THREAD

**Issue by soloam** [thomasloven/lovelace-card-mod#21]
I have a rule to modify my style, but this is only updated when I reload lovelace, not on state change:

```
cards:
  - type: vertical-stack
    cards:
    - type: custom:layout-card
      layout: horizontal
      max_columns: 2
      max_width: [100%, 100%]
      cards:
        - type: entities
          title: Luzes
          entities:
            - entity: light.maindoor_light
            - entity: light.hallway_spotlight
            - type: custom:slider-entity-row
              entity: light.hallway_tablelight
              toggle: true
              style: |
                :host {
                  color: {% if is_state('binary_sensor.hallway_tablelight_autoon', 'on') %} green {% endif %};
                }
            - entity: light.christmas_light_1
```
