### ISSUE TITLE
How to change `energy-date-selection`?

### ISSUE THREAD

**Issue by Mrtenz** [thomasloven/lovelace-card-mod#220]
I'm trying to add some styles to an `energy-dete-selection` card, but it seems like the styles aren't being applied. I tried messing with the selector, shadow roots, etc., but I can't get it to work.

My card looks like this:

```yaml
- type: custom:mod-card
  card:
    type: energy-date-selection
  card_mod:
    style:
      hui-energy-date-selection-card $:
        hui-energy-period-selector $: |
          .row {
            flex-direction: row !important;
          }
```

What should the selector look like for this card? It looks like this in the DOM:

![image](https://user-images.githubusercontent.com/7503723/185912655-42629243-37f9-4816-9c23-91a477dca211.png)
