### ISSUE TITLE
Styles in Shadow-DOM are applied inconsistent

### ISSUE THREAD

**Issue by martiesim** [thomasloven/lovelace-card-mod#226]
**My Home Assistant version:** 2022.9.7

**My lovelace configuration method (GUI or yaml):** yaml

**What I am doing:**
I'm using card-mod to ~abuse~ highly customize my frontend. I'm using a markdown card to add a custom header to my dashboard but some styles are not applied on first load.

**What I expected to happen:**
I expect the font color to be applied just like the other styles are. 

**What happened instead:**
But when opening a page for the first time since the webapp was loaded, the color is not applied. Only when the page is selected for a second time, the color is applied.

First opening of a page:
![image](https://user-images.githubusercontent.com/43559844/194192270-769643a1-95ef-4e6b-814f-07938a04f95d.png)

Second opening (without refreshing):
![image](https://user-images.githubusercontent.com/43559844/194192331-a89d3f12-a37b-4c5f-92cc-60939a6e5c94.png)

**Minimal steps to reproduce:**

```yaml
- type: markdown
    content: |
        ## Flur
    style:
        .: |
            :host{
                position: absolute;
                top: -4px;
                left: 0px;
                width: 100%;
                box-sizing: border-box;
                background-color: var(--app-header-background-color);
                margin: 0 !important;
            }
            :host::before{
                position: absolute;
                left: -4px;
                top: 0;
                width: 4px;
                height: 100%;
                background-color: var(--app-header-background-color);
            }
            :host::after{
                position: absolute;
                right: -4px;
                top: 0;
                width: 4px;
                height: 100%;
                background-color: var(--app-header-background-color);
            }
            ha-card{
                box-shadow: none;
                background: transparent !important;
            }
        ha-markdown:
            $: |
                h2{
                    color: var( --app-header-selection-bar-color, var(--app-header-text-color, #fff) );
                }
```

Open the page. Select the view with the customized markdown card in the header.
Observe the text color not being applied.
Select another view in the header.
Select the view with the customized markdown card in the header again.
Observe the text color being applied.

**Error messages from the browser console:** none

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Additional:** As the text color is to be applied in a shadow-dom and it's the only style that is not properly applied on the first try, I suspect that the shadow-dom is not handled properly.

**Quick Summary of whats been found:**
```yaml
# option 1
style:
    element $:
# option 2
style:
    element:
        $:
```
For markdown cards, option 1 does work, but option 2 does not work properly (see error description above) but for hui-element it's switched and option 1 doesn't work properly while option 2 does.
Looking at the documentation, both options should be equivalent.
