### ISSUE TITLE
changing icon color by sensor state sometimes not working

### ISSUE THREAD

**Issue by Schampanja** [thomasloven/lovelace-card-mod#229]
Hi, I am David and i think i have a Issue or a little bug.
here comes the discription:

My Home Assistant version: 2022.10.5

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
I want to change the Color of an icon by the value of a input_select 
Sometimes it works, sometimes not. I checked the state of the input_select in de dev tools an it is correct.

What I expected to happen: 
when the state of the input select ist "läuft" (german for "running" the icon shold be green). Sometimes it works, sometimes not.
Sometimes i have the feeling, that it works more often when I open the card locally on my home network and not vie the internet. But i think that should not be relevant for these CSS things.

What happened instead: nothing, icon is white

**Minimal** steps to reproduce:

here is my yaml code:

```yaml
# The least amount of code possible to reproduce my error
type: glance
entities:
  - entity: input_select.washing_machine_status
    card_mod:
      style: |
        :host {
           --paper-item-icon-color:
           {% if states('input_select.washing_machine_status') == 'läuft' %}
              #3ef705;
           {% endif %}
          }
  - entity: input_select.dryer_status
    card_mod:
      style: |
        :host {
          --paper-item-icon-color:
          {% if states('input_select.dryer_status') == 'läuft' %}
             #3ef705;
          {% endif %}
          }
  - entity: input_select.dish_washer_status
    card_mod:
      style: |
        :host {
           --paper-item-icon-color:
           {% if states('input_select.dish_washer_status') == 'läuft' %}
              #3ef705;
           {% endif %}
          }
# End of code
```

Error messages from the browser console:
no error message
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
