### ISSUE TITLE
fire-dom-event works in browser but not on companion app

### ISSUE THREAD

**Issue by MarpleA** [thomasloven/lovelace-card-mod#232]
Hi,

I created a button card to open the browse media tab in latest version of Home assistant.
This does work in my browser but on the companion app it opens the pop up, but the is stuck at "loading data".

I assume that's a bug

```
            - type: custom:button-card
              name: Browse Media
              show_name: false
              icon: mdi:play-box-multiple-outline
              tap_action:
                haptic: heavy
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    title: Media Browser
                    hide_header: false
                    large: false
                    content:
                      type: iframe
                      url: /media-browser
                      aspect_ratio: 200%
              size: 60%
              styles:
                card:
                  - height: 70px
  ```
