### ISSUE TITLE
card-header style stopped working with version 3.2.0

### ISSUE THREAD

**Issue by stickpin** [thomasloven/lovelace-card-mod#233]
With the latest version 3.2.0, the card-header style is not working anymore.
It was working fine with version 3.1.5.

My Home Assistant version: 2022.11.4

This is how it looks with version 3.1.5:
![Screenshot 2022-11-27 at 11 09 57](https://user-images.githubusercontent.com/630000/204129812-1e0f8b8a-4911-4ce3-806d-b2ffe1789065.png)

This is how it looks after the update:
![Screenshot 2022-11-27 at 11 05 19](https://user-images.githubusercontent.com/630000/204129717-487dae74-bff7-4f8e-9a3a-25db7d5bc4fe.png)

My card code:
```yaml
entities:
  - entity: vacuum.wall_e
    style: |
      state-badge {
        margin: 0px !important;
        width: 90px !important;
      }
  - entity: binary_sensor.wall_e_bin_full
    style: |
      state-badge {
        margin: 0px !important;
        width: 90px !important;
      }
  - entity: sensor.wall_e_battery_level
    style: |
      state-badge {
        margin: 0px !important;
        width: 90px !important;
      }
show_name: false
show_state: true
style: |
  ha-card {
    line-height: 40px;
    display: flex;
    justify-content: space-between;
    flex-direction: row;
    overflow: hidden;
    padding: 4px 8px;
  }
  .card-header {
    font-size: 16px;
    flex-direction: row;
    font-weight: 500;
    padding: 18px 8px;
  }
  .entities {
    padding: 0px 0px 0px !important;
    flex-direction: row !important;
  }
  .entity {
    margin-bottom: 0px !important;
  }
  state-badge {
    margin: 0px !important;
  }
title: Wall-E
type: glance
view_layout:
  column: 3

```
Any suggestions?

Thanks a lot in advance!

**Comment by pbouna321** [comment]
Same!

**Comment by thomasloven** [comment]
There used to be a patch in card-mod that moved the `.card-header` element out of the shadow root of cards in order to make styling of it easier.
Unfortunately this had to be removed because it messed with other parts of Home Assistant.

Try:

```yaml
card_mod:
  style:
    .: |
      ha-card {
        ...
    $: |
      .card-header {
        ...
```

**Comment by stickpin** [comment]
Something is still not playing well for me.

This is my original code that works with version 3.1.5:
```yaml
cards:
  - entities:
      - entity: binary_sensor.bathroom_main_motion_sensor
        style: |
          state-badge {
            margin: 0px !important;
          }
      - entity: binary_sensor.bathroom_window_sensor
        icon: mdi:window-closed-variant
        style: |
          state-badge {
            margin: 0px !important;
          }
    show_name: false
    show_state: false
    style: |
      ha-card {

        line-height: 40px;
        display: flex;
        justify-content: space-between;
        flex-direction: row;
        overflow: hidden;
        padding: 4px 8px;
      }
      .card-header {
        font-size: 16px;
        flex-direction: row;
        font-weight: 500;
        padding: 8px 8px;
      }
      .entities {
        padding: 0px 0px 0px !important;
        flex-direction: row !important;
      }
      .entity {
        margin-bottom: 0px !important;
      }
      state-badge {
        margin: 0px !important;
      }
    title: Bathroom
    type: glance
  - entities:
      - entity: light.bathroom_light
        name: Main Light
    show_header_toggle: false
    type: entities
type: custom:stack-in-card
mode: vertical
view_layout:
  column: 4
```

and this how it looks like:
![Screenshot 2022-11-28 at 18 08 32](https://user-images.githubusercontent.com/630000/204340373-ebcc387b-7da1-4fa6-a62c-4ad1c62aff38.png)

After upgrading to v3.2.0 and modifying the code to this:
```yaml
cards:
  - entities:
      - entity: binary_sensor.bathroom_main_motion_sensor
        style: |
          state-badge {
            margin: 0px !important;
          }
      - entity: binary_sensor.bathroom_window_sensor
        icon: mdi:window-closed-variant
        style: |
          state-badge {
            margin: 0px !important;
          }
    show_name: false
    show_state: false
    style:
      .: |
        ha-card {

          line-height: 40px;
          display: flex;
          justify-content: space-between;
          flex-direction: row;
          overflow: hidden;
          padding: 4px 8px;
        }
      $: |
        .card-header {
          font-size: 16px !important;
          flex-direction: row !important;
          font-weight: 500 !important;
          padding: 8px 8px !important;
        }
        .entities {
          padding: 0px 0px 0px !important;
          flex-direction: row !important;
        }
        .entity {
          margin-bottom: 0px !important;
        }
        state-badge {
          margin: 0px !important;
        }
    title: Bathroom
    type: glance
  - entities:
      - entity: light.bathroom_light
        name: Main Light
    show_header_toggle: false
    type: entities
type: custom:stack-in-card
mode: vertical
view_layout:
  column: 4
```

It looks better but is still broken:
![Screenshot 2022-11-28 at 18 20 17](https://user-images.githubusercontent.com/630000/204341334-4db849a0-cbed-4fc6-962c-bd9bcfc5909e.png)

Any suggestion?
