### ISSUE TITLE
Card style not updated when hash changes

### ISSUE THREAD

**Issue by alex3305** [thomasloven/lovelace-card-mod#238]
_My Home Assistant version:_ 2022.11.5

_My lovelace configuration method (GUI or yaml):_ GUI

_What I am doing:_ I'm creating an tabbed view with [state-switch](https://github.com/thomasloven/lovelace-state-switch)'s hashes.

_What I expected to happen:_ When the hash changes, the style gets invalidated and redrawn

_What happened instead:_ When the hash changes, nothing happens. Except for when I refresh the page.

**Minimal** steps to reproduce:

```yaml
show_name: true
show_icon: true
type: button
tap_action:
  action: navigate
  navigation_path: '#climate'
entity: light.office
card_mod:
  style: |
    ha-card {
      background-color: {{ iif(hash == 'climate', 'red', 'green') }};
    }
```

_Error messages from the browser console:_ None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
