### ISSUE TITLE
Color in rgb-format is not applied

### ISSUE THREAD

**Issue by seanomat** [thomasloven/lovelace-card-mod#239]
My Home Assistant version: 2022.12

My lovelace configuration method (GUI or yaml): yaml

What I am doing: apply state-depending color to icon. Since the recent changes to state-colors in HA 2022.12, state-colors need to be defined as rgb-values, hex or names are no longer allowed.
When I try to apply a color in rgb-notation to an icon, the icon turns black. The default should be blue, but it turns black, so I guess the style is applied, but the color-format can not be interpreted.
When I change the css-definition of the color to hex-notation, the color is apllied as expected.
This would mean I have to define every color twice in different notations.
 

What I expected to happen: the color to be applied

What happened instead: color not being applied, turns black instead

**Minimal** steps to reproduce: 

```yaml
# The least amount of code possible to reproduce my error
THEME:
  accent-color-01: 255,193,7
#  accent-color-01: "#ff0000"

CARD:
      style: |
        :host {
          --paper-item-icon-color: var(--accent-color-01);
        }  


# End of code
```

Error messages from the browser console: No errors, just not applied

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
