### ISSUE TITLE
Allow multiple CSS classes to be assigned

### ISSUE THREAD

**Issue by solid-pixel** [thomasloven/lovelace-card-mod#242]
Hello, and thanks for this life-changing tool!

I was wondering if you'd consider adding support for multiple classes?

Right now, it seems that only one value can be assigned to `class:`. I've tried adding two separated by a space, but that will result in no classes being added to the element.

I've also tried nesting them like this:

```yaml
            card_mod:
              class: 
                - no-border
                - sticky
```

but that will result in the classes being comma-separated:

```html
<ha-card class="no-border,sticky type-markdown">
                         ⬆
```

Thank you ❤️
