### ISSUE TITLE
CSS is not applied on Android application

### ISSUE THREAD

**Issue by Fizcko** [thomasloven/lovelace-card-mod#244]
My Home Assistant version: 2023.1.4
Android Application version: 2022.12.0-full
Card-Mod: 3.2.0
Android 11.1.2.2

My lovelace configuration method (GUI or yaml): YAML

Hello,

Applying this code is working on my browser but not in the HASS Android Application (2022.12.0-full) :

```yaml
          type: picture-elements       
          image: /local/floor/salon/salon_v2.png
          elements:
            - type: state-label
              entity: climate.ac_salon
              attribute: temperature
              suffix: "°C"
              card_mod:
                style: |
                  :host {
                    background: #1779ba;
                    color: #fefefe;
                    border-radius: 42%;
                    text-align: center;
                    min-width: 1em;
                    padding: .3em;
                    box-shadow: 0 0 0 1px #1779ba;
                    border: 1px solid #fefefe;
                  }
              style:
                font: Arial, sans-serif
                top: 53%
                left: 50%
                font-size: 80%
                color: black
```
Here the result on my web browser (Brave):

![image](https://user-images.githubusercontent.com/20943860/212754170-c1f5819e-0b10-4339-924d-9b8478e48849.png)

Here the result on my Android App:

![image](https://user-images.githubusercontent.com/20943860/212754294-48009e49-a68e-430d-9597-c8af28071330.png)

I have already try to clean the the cache of the application.
If i use the default web browser of my mobile and browse the website the CSS is applied.

Any one have an idea to fix this problem ?

Thanks

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
