### ISSUE TITLE
Styling Logbook Entries

### ISSUE THREAD

**Issue by elwoodhouse** [thomasloven/lovelace-card-mod#248]
Hi,

I think styling elements that have multiple nested shadow-roots that are not ready when the page loads is not supported, but I wanted to check.

I would like to style the individual entries in a logbook card, so in the card yaml I've added:
```yaml 
card_mod:
  style:
    ha-logbook$ha-logbook-renderer$: |
      .entry {
        background-color: var(--chip-background-color);
      }
```
The entries are not styled on the initial render of the dashboard and I think this is because of what NOTE 2 in the DOM navigate states, as the entries take a bit of time to draw. Eventually, after a while, they do style with the above rule.

I've tried using the multiple step navigation into the shadow-root like:
```yaml
ha-logbook:
  $: |
    ha-logbook-renderer:
      $: |
        .entry {
          background-color: var(--chip-background-color);
        }
```
but that doesn't seem to find the right class. I've also tried with different combinations of | at the end of the lines.

Is what I'm trying to do possible on the initial render of the dashboard? 

Thanks, and thanks for the module in general, once you get the hang of it, it's quite useful.
Leon.

**Comment by ildar170975** [comment]
[Check if this can help you.](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/3055?u=ildar_gabdullin)

**Comment by elwoodhouse** [comment]
Thanks for the pointer. I've looked at your example and replicated it, but with:
``` yaml
card_mod:
  style:
    .content ha-logbook $ ha-logbook-renderer $: |
      .entry-container .entry {
        background-color: var(--chip-background-color);
      }
```
I'm still getting the same behavior that the initial render doesn't apply the style, but on the second render (after interacting with the dashboard), the style is applied.

I'm not sure why I would be getting a different behavior to your border-radius example, it seems like we're styling the same area. My core version is 2022.12.8, card-mod 3.2.0 and I'm running HA through a windows VM. Would any of those details make a difference?
