### ISSUE TITLE
Card-mod breaking automations for me, pull-down menu items don't work in entities

### ISSUE THREAD

**Issue by confuserated** [thomasloven/lovelace-card-mod#253]
My Home Assistant version: 2023.2.1

My lovelace configuration method (GUI or yaml):

GUI

What I am doing:

I am adding an automation that has a condition that is tested, in my example I am checking if the climate entity is on or off and I select the correct state I need from the pull down menu in the GUI, what gets written in YAML mode is uncapitalised when returned state and selected state is capitalised and then the trace shows that the desired and delivered state do not match so the automation does not run.

The should match though as the only difference is capitalisation of the first letter of the state.

I submitted a bug report on HA but it was caused by card-mod, since uninstalling card-mod fixes the problem and now everything works as expected.

https://github.com/home-assistant/frontend/issues/15201

What I expected to happen:

What happened instead:

Trace output shows:

Executed: 25 January 2023 at 15:12:22
Result:
result: false
entity_id/0
Executed: 25 January 2023 at 15:12:22
Result:
result: false
state: 'on'
wanted_state: 'On'

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

My automation:

alias: Startup Heating reset
description: Reset the scheduler after system restart
trigger:

platform: homeassistant
event: start
condition:
condition: state
entity_id: switch.schedule_79b82e
state: "on"
for:
hours: 0
minutes: 0
seconds: 0
action:
delay:
hours: 0
minutes: 2
seconds: 0
milliseconds: 0
service: switch.turn_off
data: {}
target:
entity_id: switch.schedule_79b82e
delay:
hours: 0
minutes: 0
seconds: 10
milliseconds: 0
service: switch.turn_on
data: {}
target:
entity_id: switch.schedule_79b82e
mode: single

PLEASE IGNORE THE WAY THE TEXT IS FORMATTED IN THE EDIT ABOVE, IT IS NOT SHOWING CORRECTLY IN THE BROWSER BUT THE SPACING IS CORRECT IN THE YAML, THAT IS NOT THE PROBLEM.

# End of code
```

Error messages from the browser console:

none seen, as automations fail to run because the tested state does not comply with the expected state.
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
