### ISSUE TITLE
No injection of card-mod styles beyond the first level of ha-markdown cards

### ISSUE THREAD

**Issue by parautenbach** [thomasloven/lovelace-card-mod#259]
My Home Assistant version: 2023.2.3

My lovelace configuration method (GUI or yaml):
YAML

What I am doing:
Applying a custom style by colouring alternating rows of a table in a markdown card. The example YAML below precedes the big UI changes of 2022.12. I know I'll need to change some variables. 

The problem seems to be that the `<card-mod>` element is only injected at the top. Usually, there will be a `<card-mod>` element at each level. 

<img width="378" alt="Screenshot 2023-03-07 at 21 40 11" src="https://user-images.githubusercontent.com/743320/223535593-9be3ba69-76d2-4f68-b711-54e3af765cbe.png">

What I expected to happen:
A blue header, with white text, and a table where every other row has a background colour. 

What happened instead:
Nothing.

**Minimal** steps to reproduce:

```yaml
        card_mod:
          style:
            ha-markdown:
              $:
                ha-markdown-element: |
                  table {
                    border-spacing: 0;
                    width: 100%;
                    padding: 8px;
                    border-radius: var(--ha-card-border-radius);
                  }
                  th {
                    background-color: var(--state-icon-color);
                    color: white;
                    padding: 4px;
                  }
                  th:first-child {
                    border-top-left-radius: min(var(--ha-card-border-radius)/2, 5px);
                  }
                  th:last-child {
                    border-top-right-radius: min(var(--ha-card-border-radius)/2, 5px);
                  }
                  td {
                    padding: 4px;
                  }
                  tr:nth-child(even) {
                    background-color: var(--table-row-background-color);
                  }
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
