### ISSUE TITLE
Code duplicates while using the UI editor after upgrading to 0.105.2

### ISSUE THREAD

**Issue by Unpuertomex** [thomasloven/lovelace-card-mod#26]
My Home Assistant version: 0.105.2

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Modifying the CSS of the entities card.

What I expected to happen:
The code to not self duplicate

What happened instead:
When the UI editor is open or closed the code duplicates itself

**Minimal** steps to reproduce:
The code I'm using is below. The part that it is adding and duplicating is 
 ``` 
 ha-card {
    background: none;
    box-shadow: none;
  }
```
Below is the code I'm using in the card through the UI editor

```yaml
type: 'custom:mod-card'
style: |


  ha-card {
     background: url(/local/pics/ui/small-master-bedroom.jpg);
   }
card:
  type: vertical-stack
  cards:
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          entity: script.good_night_all_lights_off
          name: Living room
          show_icon: false
          styles:
            card:
              - background: '#FF704D'
              - border-radius: 5%
              - width: 110px
              - height: 45px
              - border: 2px dashed
          tap_action:
            action: navigate
            navigation_path: '#p1'
        - type: 'custom:button-card'
          entity: light.garage
          name: Master
          show_icon: false
          styles:
            card:
              - background: '#FF704D'
              - border-radius: 5%
              - width: 110px
              - height: 45px
              - border: 2px dashed
          tap_action:
            action: navigate
            navigation_path: '#p2'
        - type: 'custom:button-card'
          entity: light.garage
          name: Andrew
          show_icon: false
          styles:
            card:
              - background: '#FF704D'
              - border-radius: 5%
              - width: 110px
              - height: 45px
              - border: 2px dashed
          tap_action:
            action: navigate
            navigation_path: '#p3'
    - type: vertical-stack
      cards:
        - type: 'custom:state-switch'
          entity: hash
          style: ''
          default: p1
          transition: slide-right
          states:
            p1:
              type: entities
              style: |
                ha-card {
                  background: none;
                  box-shadow: none;
                 }
              entities:
                - type: 'custom:slider-entity-row'
                  entity: light.livingroom_dimmer_level
                  icon: 'mdi:ceiling-light'
                - type: divider
                - type: 'custom:slider-entity-row'
                  entity: light.living_room_lamp
                  icon: 'mdi:floor-lamp'
                - type: 'custom:rgb-light-card'
                  entity: light.living_room_lamp
                  colors:
                    - rgb_color:
                        - 255
                        - 127
                        - 255
                    - rgb_color:
                        - 241
                        - 224
                        - 181
                    - rgb_color:
                        - 239
                        - 210
                        - 117
                    - rgb_color:
                        - 255
                        - 0
                        - 21
                      brightness: 255
                      transition: 1
            p2:
              type: entities
              entities:
                - light.dining_room
                - light.entrance




# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X ] Have made sure I am using the latest version of the plugin.

[X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
