### ISSUE TITLE
Browser variable

### ISSUE THREAD

**Issue by dimmanramone** [thomasloven/lovelace-card-mod#260]
**My Home Assistant version:** 2023.3.1

**My lovelace configuration method (GUI or yaml):** YAML

**What I am doing:** Use browser variable in a jinja2 template to have different css per device

**What I expected to happen:** When browsing from the the device with deviceID pixel7-app to have top: 2px;

**What happened instead:** Continues to the else statement

Not really sure that I'm using it right but it works for example with the user variable.

```yaml
card_mod:
  style: |
    :host {
      z-index: 999;
      position: sticky;
      position: -webkit-sticky;
      {% if browser == 'pixel7-app' %}
        top: 2px;
      {% else %}
        top: var(--header-height); 
      {% endif %}
    }
```
