### ISSUE TITLE
card-mod-sidebar-yaml no longer works

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#264]
My Home Assistant version: 2023.4.0b0

My lovelace configuration method (GUI or yaml): YAML

What I am doing:

modding the card-mod-sidebar-yaml

What I expected to happen: (this was before updating to ha 2023.4)

<img width="245" alt="Scherm­afbeelding 2023-03-30 om 09 33 18" src="https://user-images.githubusercontent.com/33354141/228866342-aaf4ffd6-3e31-4813-8f1d-1a196314127b.png">

and (see mod under Title)

![Scherm­afbeelding 2023-03-07 om 13 38 11](https://user-images.githubusercontent.com/33354141/228868280-1c2848b4-543c-4333-b098-9ede648fcc9b.png)

What happened instead:

before the card-mod update to 3.2.1, with update to 2023.4:

<img width="250" alt="Scherm­afbeelding 2023-03-30 om 09 27 30" src="https://user-images.githubusercontent.com/33354141/228866553-9933c5a4-66f1-441f-a115-3ce684726144.png">

after update to card_mod 3.2.1, HA 2023.4:
nothing sticks at all, (including the browser_mod sidebar title change):

<img width="255" alt="Scherm­afbeelding 2023-03-30 om 16 26 39" src="https://user-images.githubusercontent.com/33354141/228868568-502db4cf-93a0-4fad-bbc9-875c912d2e29.png">

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
theme-mods:

  card-mod-sidebar-yaml: |
    .: |

      .menu .title:after {
        content: "{% set count = states('sensor.marquee_alerts')|float(default=0) %}
                  {%- set phrase = 'Alert: '
                     if states('sensor.marquee_alerts')|float(default=0) == 1
                     else 'Alerts:' -%}
                  {{'\A ' + phrase + states('sensor.marquee_alerts') if count > 0 }}";
        white-space: pre;
        font-size: 12px;
        font-weight: bold;
        display: block;
        line-height: 4px;
        color: var(--alert-color);
      }

      a[data-panel='ui-overzicht'] paper-icon-item ha-icon {
          --card-mod-icon: {{'mdi:home-alert' if states('sensor.alerts_notifying')|int(default=0) > 0
                              else 'mdi:home'}};
          color: {{'var(--alert-color)' if states('sensor.alerts_notifying')|int(default=0) > 0
                   else 'green'}};
      }

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
