### ISSUE TITLE
card-mod-theme does nothing in 3.2.2 with HA 2023.4.0

### ISSUE THREAD

**Issue by ghost** [thomasloven/lovelace-card-mod#269]
I recently updated my HA to the latest version, which is 2023.4.0, and Custom Header had to go because of the update.

To mimic my previous setup as closely as possible, I'm attempting to migrate card-mod-theme.

However, despite installing card-mod 3.2.2 in HACS and editing theme.yaml, card-mod-theme isn't making any changes to the header.

Here is how my theme.yaml looks like
```
#
# iOS Dark Mode Theme
#
ios-dark-mode:
  # Global
  card-mod-theme: ios-dark-mode
  background-image: "center / cover no-repeat fixed url('/hacsfiles/themes/ios-themes/homekit-bg-light-green.jpg')"
  lovelace-background: var(--background-image)
  primary-color: "#ff9f09"  # from Apple systemOrange dark mode
  light-primary-color: "#B6B6C1"  # (icons on left menu) (light: systemGray5 from iOS dark mode, dark: XXX)
  primary-background-color: "#2c2c2e"  # systemGray5 dark mode
  secondary-background-color: rgba(25, 25, 25, 0.9)
  divider-color: rgba(152, 152, 157, 0.3)  # from Apple systemGray dark mode
  accent-color: rgba(255, 159, 9, 1)
  # Text
  primary-text-color: "#FFF"
  secondary-text-color: "#d3d3d3"
  text-primary-color: "#FFF"
  disabled-text-color: "#555"  # XXX: https://github.com/basnijholt/lovelace-ios-dark-mode-theme/issues/2
  text-dark-color: "#FFF"
  # Header
  card-mod-root-yaml: |
    ha-app-layout$: |
        /* This corrects top padding for the view. */
        #contentContainer {
          padding-top: 48px !important;
        }

    paper-tabs$: |
        /* This hides tab scroll arrows, remove next 3 lines if you want them. */
        paper-icon-button {
          display: none;
        }
        /* This makes it so arrows are only displayed when needed. */
        .not-visible {
          display: none;
        }
    .: |
      ha-menu-button {
        display: none !important;
      }
      action-items {
        dispaly: none !important;
      }

      @media (orientation: portrait) {
        a.menu-link[target="_blank"], ha-button-menu, [main-title] {
          display: none;
        }
        paper-icon-button[icon="paper-tabs:chevron-right"] {
          display: none;
        }
        paper-icon-button[icon="paper-tabs:chevron-left"] {
          display: none;
        }
      }
```

![11](https://user-images.githubusercontent.com/70864968/230313639-92c7d4b4-3adc-452c-95a4-e6d61efdac0d.JPG)
And as you can see, the top header remains unchanged from default.

![22](https://user-images.githubusercontent.com/70864968/230314275-7d1c84f4-f5b5-4a26-af49-bb29efdff8e4.JPG)
This is how I want my header to look. (This is the only screenshot I have of my previous dashboard)

Here is the old config of custom header:
```
custom_header:                               
  background: 'rgba(0, 0, 0, 0.5)'                                                
  compact_mode: true                                           
  stack_css: 'padding: 5px'                               
  elements_color: rgba(255, 255, 255, 1)                   
  active_tab_css: 'background: rgba(255, 255, 255, 0.2)'         
  tab_indicator_color: 'rgba(0, 0, 0, 0)'                                
  chevrons: false                                                                                  
  fit_tabs: true                                                                               
  menu_hide: true                                    
  options_hide: true                          
  tab_icons_and_text: false    
  tabs_css:                        
    0: '--mdc-icon-size: 40px'               
    1: 'font-size: 20pt'    
    2: 'font-size: 20pt'   
    3: 'font-size: 20pt'               
    4: 'font-size: 20pt'                
  tab_icons:      
    0: mdi:home   
```

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
