### ISSUE TITLE
Can't use card-mod with slider-entity-row

### ISSUE THREAD

**Issue by AnthonMS** [thomasloven/lovelace-card-mod#27]
My Home Assistant version: 0.XX.X
0.102.3

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
I am trying to add some custom css to the slider-entity-row. I wan't the slider to look more like the bar_card.

What I expected to happen:
I expected it to be able to change the styling of the slider, I have been fiddling around in the browser inspect element and changed the css to look like I want. But when I went to add in the stryling nothing happens.

What happened instead:
Nothing.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

          - type: entities
            style: |
              div { 
                padding: 0px !important;
                margin: 0px !important;
              }
            entities: 
              - type: custom:slider-entity-row
                style: |
                  #sliderContainer {
                    margin-left: 0px !important;
                    margin-right: 0px !important;
                  }
                entity: light.dinner_table_light
                name: hide_state
                full_row: true
                hide_when_off: false
                hide_state: true

# End of code
```

Error messages from the browser console:
No error message, nothing happens.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
