### ISSUE TITLE
Report size no longer works in 2023.4

### ISSUE THREAD

**Issue by scstraus** [thomasloven/lovelace-card-mod#272]
My Home Assistant version: 2023.4.2

My lovelace configuration method (GUI or yaml):
Yaml

What I am doing:

        - type: custom:mod-card
          report_size: 2
          card:

What I expected to happen:

The card to display

What happened instead:

Lovelace doesn't find mod-card any more

**Minimal** steps to reproduce:

Update to latest versions of hass and card-mod as of today, April 10 2023. 

```yaml
# The least amount of code possible to reproduce my error

        - type: custom:mod-card
          report_size: 2
          card:
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
