### ISSUE TITLE
i.setConfig is not a function

### ISSUE THREAD

**Issue by darth-aragoth** [thomasloven/lovelace-card-mod#274]
My Home Assistant version: 2023.4.2

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Trying to add picture to entities card.

What I expected to happen:
See picture in entities card

What happened instead:
Error:
```
i.setConfig is not a function
type: custom:card-mod
card:
  type: picture-glance
  entities:
    - camera.xiaomi_cloud_map_extractor
```

**Minimal** steps to reproduce:
Add card with code specified below.

```
type: entities
entities:
  - entity: vacuum.roborock_vacuum_s6
    type: custom:multiple-entity-row
    secondary_info: last-updated
  - entity: sensor.roborock_s6_battery
  - type: custom:card-mod
    card:
      type: picture-glance
      entities:
        - camera.xiaomi_cloud_map_extractor
show_header_toggle: false
state_color: true
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
