### ISSUE TITLE
Styles not applied on first page load

### ISSUE THREAD

**Issue by patrickli** [thomasloven/lovelace-card-mod#279]
I know this bug has been reported a couple of times https://github.com/thomasloven/lovelace-card-mod/issues/218, https://github.com/thomasloven/lovelace-card-mod/issues/208, https://github.com/thomasloven/lovelace-card-mod/issues/204#issuecomment-1149183795 (indirectly).

But
* I think I have written the style in the correct way.
* You can reproduce this with the test code shipped in this project https://github.com/thomasloven/lovelace-card-mod/blob/master/test/views/3_badges.yaml. The sun badges will not have the intended colour on the first page load.

My Home Assistant version: 2023.4.6

My lovelace configuration method (GUI or yaml): GUI with RAW yaml editor

What I am doing: trying to change the colour of the icon and border of badges.

What I expected to happen: The badge will show with the colour I specified via card-mod style.

What happened instead: The badge shows original colours. If navigate to a different page and go back, the specified colours then shows up.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
title: Home
views:
  - path: ''
    title: Home
    icon: mdi:home
    badges:
      - type: entity-filter
        entities:
          - entity: binary_sensor.entrances
            card_mod:
              style:
                ha-state-label-badge $: |
                  ha-label-badge {
                    --ha-label-badge-color: var(--label-badge-yellow) !important;
                  }
                  ha-state-icon {
                    color: var(--state-binary_sensor-door-on-color, var(--state-binary_sensor-on-color, var(--state-binary_sensor-active-color, var(--state-active-color))));
                  }
        state_filter:
          - 'on'
# End of code
```

Error messages from the browser console:
None
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
