### ISSUE TITLE
Unable to load card-mod due to missing card-tools file

### ISSUE THREAD

**Issue by Cludch** [thomasloven/lovelace-card-mod#28]
My Home Assistant version:

0.105.3

My lovelace configuration method (GUI or yaml):

yaml

What I am doing:

Installing card-mod and card-tools via HACS and view the developer console in my browser.

What I expected to happen:

No errors.

What happened instead: `Error resolving module specifier: card-tools/src/templates.js`

**Minimal** steps to reproduce:

Install

```yaml
# The least ammount of code possible to reproduce my error

- url: /local/community/lovelace-card-tools/card-tools.js
  type: module
- url: /local/community/lovelace-card-mod/card-mod.js
  type: module

# End of code
```

Error messages from the browser console:
`Error resolving module specifier: card-tools/src/templates.js`

I noticed that I am using card-mod.js from the `src` directory, which is the non-minified version.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
