### ISSUE TITLE
Unexpected indentation when adding secondary_info to modded entity

### ISSUE THREAD

**Issue by MaxVonEvil** [thomasloven/lovelace-card-mod#288]
My Home Assistant version: 2023.7.2 
Supervisor 2023.07.1 
Operating System 10.3 
Frontend 20230705.1 - latest 

My lovelace configuration method (GUI or yaml): Yaml

What I am doing: 
Adding "secondary_info: last-changed" to an entity after having added mods to remove icon and set left margin to 0.

What I expected to happen:
Text supposed to stay where it was at margin 0

What happened instead:
Text indented half way in. See screenshot:

![image](https://github.com/thomasloven/lovelace-card-mod/assets/19863636/172e1905-94fd-4e86-adb6-f5318181bbbe)

**Minimal** steps to reproduce:
Try pasting my Yaml code below into a new manual card and see if it does the same. Just add/remove the secondary_info line and see how it changes the indentation.

```yaml
# The least amount of code possible to reproduce my error

square: false
type: grid
cards:
  - type: entities
    entities:
      - entity: switch.valve_irr_zone1
        name: Z1 Back lawn E
        secondary_info: last-changed
        card_mod:
          style:
            hui-generic-entity-row:
              $: |
                state-badge {
                  display: none;
                }
                .text-content {
                  margin-left:0 !important;
                }
      - entity: switch.valve_irr_zone2
        name: Z2 Back lawn W
        secondary_info: last-changed
        card_mod:
          style:
            hui-generic-entity-row:
              $: |
                state-badge {
                  display: none;
                }
                .text-content {
                  margin-left:0 !important;
                }
      - entity: switch.valve_irr_zone3
        name: Z3 Front drips
        secondary_info: last-changed
        card_mod:
          style:
            hui-generic-entity-row:
              $: |
                state-badge {
                  display: none;
                }
                .text-content {
                  margin-left:0 !important;
                }
      - entity: switch.valve_irr_zone4
        name: Front lawn W
        secondary_info: last-changed
        card_mod:
          style:
            hui-generic-entity-row:
              $: |
                state-badge {
                  display: none;
                }
                .text-content {
                  margin-left:0 !important;
                }
  - type: entities
    entities:
      - sensor.sw_visual_studio_code_version
      - sensor.sw_visual_studio_code_newest_version
      - sensor.sw_samba_share_version
columns: 2

# End of code
```

Error messages from the browser console: 
None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
