### ISSUE TITLE
Light state

### ISSUE THREAD

**Issue by hekm77** [thomasloven/lovelace-card-mod#3]
My Home Assistant version: 0.95.4

My lovelace configuration method (GUI or yaml):
`yaml`

What I am doing:
The light is controlled from automation.

**Lovelace Card Mod**
The light switch vibrates and does not change the state.

```yaml
- title: Test Card Mod
  icon: mdi:home
  cards:
    - type: entities
      style: |
        ha-card {
          border-radius: 10px;
        }
      entities:
        - entity: light.bedroom
    - type: entities
      style: |
        ha-card {
          border-radius: 10px;
        }
      entities:
        - type: custom:slider-entity-row
          entity: light.bedroom
          toggle: true
          name: Bedroom
```
![card-mod](https://user-images.githubusercontent.com/22895433/60765930-3a9ca000-a0a2-11e9-93b1-3e946dd3c34c.gif)

**Lovelace Card Modder**
The light switch changes state without error.

```yaml
- title: Test card-modder
  icon: mdi:home
  cards:
    - type: custom:card-modder
      style:
        border-radius: 10px
      card:
        type: entities
        entities:
         - entity: light.bedroom
    - type: custom:card-modder
      style:
        border-radius: 10px
      card:
        type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.bedroom
            toggle: true
            name: Bedroom
```
![card-modder](https://user-images.githubusercontent.com/22895433/60765964-d7f7d400-a0a2-11e9-8091-a643ae7a8dae.gif)
