### ISSUE TITLE
Card mod completely broken.  Stopped by Uncaught TypeError from card-tools

### ISSUE THREAD

**Issue by Petro31** [thomasloven/lovelace-card-mod#30]
My Home Assistant version: 0.105.3

My lovelace configuration method (GUI or yaml):
Yaml

What I am doing:
Simply upgraded to the newest card mod.  Downgrading no-longer works either.

What I expected to happen:
This error is stopping all card-mod styles.  Cards still work without styles.  I'd expect the outcome would be to get styles back.

What happened instead:
No styles are applied.

**Minimal** steps to reproduce:
I don't know if I can.  This is the error that is being produced from card tools that causes card-mod to fail.  Removing card mod resources removes the error.

F12 Dev console (chrome):
```
Uncaught TypeError: Failed to resolve module specifier "card-tools/src/templates.js". Relative references must start with either "/", "./", or "../".
```

HA Logs:
```
2020-02-13 22:20:55 ERROR (MainThread) [frontend.js.latest.202001302] http://x:8123/lovelace/0:0:0 Uncaught TypeError: Failed to resolve module specifier "card-tools/src/templates.js". Relative references must start with either "/", "./", or "../".
```

# The least ammount of code possible to reproduce my error

This is my test card that I play around with when developing appdaemon apps.  I usually don't style it.  Just added the 'example style' and it produces the same error.
```yaml
  - id: testing
    icon: mdi:test-tube
    title: Testing
    style: |
      ha-card {
        color: red;
      }
    cards:
      - type: entities
        entities: 
          - switch.test_1
          - switch.test_2
          - light.test
          - light.test_1
          - light.test_2
```
Error messages from the browser console:
```
Uncaught TypeError: Failed to resolve module specifier "card-tools/src/templates.js". Relative references must start with either "/", "./", or "../".
```
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x ] Have made sure I am using the latest version of the plugin.

[x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
