### ISSUE TITLE
[Feature] Theming With HTML Elements That Unloads or Loads Late

### ISSUE THREAD

**Issue by Nerwyn** [thomasloven/lovelace-card-mod#302]
Is there any way to make it so that card-mod within themes reloads if the HTML on the page changes? Some elements unload and reload or load late, and the card-mod theme CSS does not apply if the element is not present on initial page load.

**Context:**
I've started using card-mod as part of [my theme](https://github.com/Nerwyn/material-rounded-theme) to transform the navbar from a header to a footer and make some other stylistic changes. While this works great it does break when I enter or exit edit dashboard mode.

How it looks with card-mod theming normally:
<img alt="image" src="https://github.com/thomasloven/lovelace-card-mod/assets/43071698/52d9258a-462b-4039-835c-9d2d054feeef">

After entering edit mode:
![image](https://github.com/thomasloven/lovelace-card-mod/assets/43071698/b5f79532-9a3f-4c26-af5a-9938e478c1b0)

And after exiting edit mode:
<img alt="image" src="https://github.com/thomasloven/lovelace-card-mod/assets/43071698/b0c27870-5736-42c5-a3b7-c0d6c06ac27a">

The reason for this is that the HTML around the navbar changes from `ha-tabs`:

<img alt="image" src="https://github.com/thomasloven/lovelace-card-mod/assets/43071698/e32d6691-1c02-4761-a611-1fb375c2f3c7">

to `paper-tabs`:
<img alt="image" src="https://github.com/thomasloven/lovelace-card-mod/assets/43071698/36103096-1b6a-45ee-9d83-4021ecaeb993">

While I was able to repeat the CSS for evenly spacing the icons for both of these, because entering and editing edit mode causes the HTML of the page to change it the card-mod theme CSS doesn't apply until the page is refreshed. Relevant card-mod CSS for reference:

```css
ha-tabs:
  $: |
    #tabsContent.scrollable {
      width: 100% !important;
      display: flex !important;
      justify-content: space-between !important;
      flex-shrink: 0;
    }
    paper-icon-button {
      display: none !important;
    }

paper-tabs:
  $: |
    #tabsContent.scrollable {
      width: 100% !important;
      display: flex !important;
      justify-content: space-between !important;
      flex-shrink: 0;
    }
```

The `frontend.reload_themes` service also fixes the CSS for new HTML elements. Is there any way to make it so that either the card-mod theme CSS is reloaded if the page HTML changes, or `frontend.reload_themes` is called? Alternatively is there a way to detect and automate calling `frontend.reload_themes` if any user enters or exits edit mode?
