### ISSUE TITLE
Mod styling not applied when loading/initializing the dashboard

### ISSUE THREAD

**Issue by coolbombom** [thomasloven/lovelace-card-mod#303]
My Home Assistant version: 
2023.10.4

My lovelace configuration method (GUI or yaml): 
yaml

What I am doing: 
setting width of a card

What I expected to happen: 
card width to be fixed and shown in that width

What happened instead:
styling is not applied to mushroom-light-card until window is resized and hit a width threshold.

In other words, the styling is not applied when loading/initializing the dashboard, but resizing the browser window resulting in hitting a media query (i think), causes the styling to be added. I can see that the CSS styling it is not applied, by investigating the elements using Firefox.

Example:
```yaml
type: custom:mod-card
style:
  .: |
    ha-card {
      border-width:0px;
    }
  hui-horizontal-stack-card$: |
    #root {
       display: unset !important;
    }
    mushroom-light-card {
       width: 167px !important;
    }
card:
  type: horizontal-stack
  cards:
    - type: custom:mushroom-light-card
      entity: light.sofa
      layout: vertical
      hide_state: false
      use_light_color: false
      show_brightness_control: true
      show_color_temp_control: false
      show_color_control: false
      collapsible_controls: true
      hold_action:
        action: more-info
      fill_container: false
      icon: mdi:lightbulb
      name: Sofa
    - type: custom:mushroom-light-card
      entity: light.other
      layout: vertical
      use_light_color: false
      hold_action:
        action: more-info
      show_brightness_control: true
      collapsible_controls: true
      show_color_control: false
      show_color_temp_control: false
      hide_state: false
      fill_container: false
    - type: custom:mushroom-light-card
      entity: light.dimmable_light_1_3
      layout: vertical
      hide_state: false
      use_light_color: false
      show_brightness_control: true
      show_color_temp_control: false
      show_color_control: false
      collapsible_controls: true
      hold_action:
        action: more-info
      fill_container: false
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
