### ISSUE TITLE
Styles not applied under Conditional card

### ISSUE THREAD

**Issue by paqpaqpaq** [thomasloven/lovelace-card-mod#306]
As previous issues have been closed, it seems for some it hasn't really been resolved.

On MacOS Chrome and Safari, as well as Android Fully Kiosk, the style is not applied when under a conditional card. 
In the browser's development tools the card-mod remains empty and seems to be wrongly mapped too.

```
  - type: conditional
    conditions:
      - entity: humidifier.zhimi_cb1_438c_humidifier
        state: 'on'
    elements:
      - type: icon
        show_icon: true
        icon: mdi:waves
        style:
          top: 19.5%
          left: 73%
          color: gainsboro
          transform: scale(0.7,0.7)
          '--divider-color': none
      - type: state-label
        entity: sensor.tankinhoud_humidifier_kantoor
        style:
          top: 21.5%
          left: 76%
          font-weight: bold
          font-size: 90%
        card_mod:
          style: |
            :host {
              color:
                  {% set inhoud = states('sensor.tankinhoud_humidifier_kantoor')|float %}
                  {% if inhoud <= 1 %}
                    #FFD700
                  {% elif inhoud > 1 %}
                    #DCDCDC
                  {% endif %}
                  }
```

This works only when the conditional card is removed. 
The above code outputs this in the browser:

<img width="763" alt="Scherm­afbeelding 2023-10-29 om 10 56 12" src="https://github.com/thomasloven/lovelace-card-mod/assets/34166264/b53810c0-5ddb-483c-b286-d1c1a5fbaeb2">

The card-mod tags doesn't end up under the div that it's regarding to.

Home Assistant 2023.10.2
Supervisor 2023.10.1
Frontend-versie: 20231005.0 - latest
Latest card-mod version
