### ISSUE TITLE
Picture-elements: styling some conditional element may cause styling other elements

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-card-mod#308]
HA 2023.10.2
card-mod 3.2.3

My lovelace configuration method (GUI or yaml): both

Consider this picture-elements card:

![изображение](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/bd54920b-11c4-48c1-a92e-2ea0dea6bbce)
```
type: picture-elements
image: /local/images/test/white.jpg
elements:
  - type: state-label
    entity: sun.sun
    style:
      top: 17%
      left: 25%
      
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: 'on'
    elements:
      - type: state-label
        entity: sun.sun
        style:
          top: 30%
          left: 25%
          
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: 'on'
    elements:
      - type: state-badge
        entity: sun.sun
        style:
          top: 7%
          left: 75%
      - type: state-label
        entity: sun.sun
        style:
          top: 17%
          left: 75%
    card_mod:
      style: |
        hui-state-label-element {
          color: red;
        }
```
Card-mod style is defined for one conditional element - particularly for a `state-label` sub-element.
I expect to see this style applied **for this `state-label` element only**.
Instead, this style is applied for all `state-label` elements on the card.

Note that the card-mod style is defined **w/o entering "shadowRoot"**.
Otherwise - the style is applied for a proper element only (as expected):

![изображение](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/f4a99822-f9b1-4d9a-a87d-06f061a1ed2a)
```
type: picture-elements
image: /local/images/test/white.jpg
elements:
  - type: state-label
    entity: sun.sun
    style:
      top: 17%
      left: 25%
      
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: 'on'
    elements:
      - type: state-label
        entity: sun.sun
        style:
          top: 30%
          left: 25%
          
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: 'on'
    elements:
      - type: state-badge
        entity: sun.sun
        style:
          top: 7%
          left: 75%
      - type: state-label
        entity: sun.sun
        style:
          top: 17%
          left: 75%
    card_mod:
      style:
        hui-state-label-element:
          $: |
            div {
              color: red;
            }
```
Unfortunately, when using card-mod styles with entering "shadowRoot" [another issue is observed](https://github.com/thomasloven/lovelace-card-mod/issues/201#issuecomment-1785879256).

Error messages from the browser console:
none

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Still in 3.4.5 & 2025.10.1.

<img width="957" height="809" alt="Image" src="https://github.com/user-attachments/assets/d3d48ecd-6cd9-49f9-bfe3-d65fb38b535a" />

**Comment by dcapslock** [comment]
Tested with v4.0.0-beta.1 and looks to be resolved with the correct patching of conditional element (hui-card root). (element positions adjusted to suit background which is 512x512px)

<img width="423" height="463" alt="Image" src="https://github.com/user-attachments/assets/ff6bfc0d-61cf-4c61-94c3-6c6c21b40ca8" />

<img width="423" height="463" alt="Image" src="https://github.com/user-attachments/assets/4467b701-039f-4def-ab01-99caae051b1e" />

**Comment by dcapslock** [comment]
[v4.0.0](https://github.com/thomasloven/lovelace-card-mod/releases/tag/v4.0.0) released

**Comment by ildar170975** [comment]
Still see the glitch in 4.0.0.
Code from the 1st post.

<img width="1733" height="890" alt="Image" src="https://github.com/user-attachments/assets/76af814d-089e-4311-9e7f-356122c7d4fe" />

From a config for `extra_module_url` (compare with a tag on a screenshot, they are same):
```
- /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524400
```
Browser cache is purged several times, HA was rebooted after editing `extra_module_url`.

**Comment by ildar170975** [comment]
It is "great" that a topic starter cannot reopen his own issue.

**Comment by dcapslock** [comment]
Reopening for further investigation.

**Comment by dcapslock** [comment]
This is similar to #535 with entities conditional rows. Conditional elements also are not in shadowRoot so their styles 'leak' to all rows. The fix will be a similar fix to #535 where the condtional config will not able to be styled, rather intriducing the ability to style the element directly itself.

**Comment by ildar170975** [comment]
> Conditional elements also are not in shadowRoot so their styles 'leak' to all rows. 

Interesting that in cases of styling in shadowRoot there is no such a leak, see 1st post.

**Comment by dcapslock** [comment]
> Interesting that in cases of styling in shadowRoot there is no such a leak, see 1st post.

I am not understanding this statement.

**Comment by dcapslock** [comment]
I think I may understand what you are saying, that for a conditional row you are able to style without shadowRoot, which is actually the issue. Card_mod is applied to an element without shadowRoot so the styles apply for all elements sharing the same light DOM. This is why styling fo conditional row/elements breaks in this way, with the fix to not style the condtional config but to style the elements directly, which is easier as well as the styles can be applied to the element's light DOM.

I have coded up a fix and testing is good.

**Comment by ildar170975** [comment]
Sorry, now I am not sure if I understood you properly.
I meant the 2nd example from the 1st post.
If a style is defined like
```
  - type: conditional
    conditions: ...
    elements:
      - type: state-badge
        ...
      - type: state-label
        ...
    card_mod:
      style:
        hui-state-label-element:
          $: |
            div {
              color: red;
            }
```
then only THIS state-label element is styled, not all state-label elements in a card.
May be it is about the same what you said ))

**Comment by dcapslock** [comment]
Yes, that is the a workaround, as that makes sure styles are set to the elemenet specified in shadowRoot (same as per conditional rows). With v3.4.x/4.0.0 you need to do this as styling the element directly will not work (same as conditional rows).

The fix will allow

```yaml
  - type: conditional
    conditions: ...
    elements:
      - type: state-badge
        ...
      - type: state-label
        ...
        card_mod: # <- move card_mod to element. Not possible with 3.4.x/4.0.0
          style: | # <- style now in element light dom. Does not leak
            div {
               color: red;
            }
```

**Comment by ildar170975** [comment]
I think this is a very practical addition.
So, `card-mod` elements will be created "on a fly" along with inner sub-elements inside a conditional element?
Now `card-mod` elements are hanging here (condition = false, sub-elements are not present in dom):
<img width="272" height="119" alt="Image" src="https://github.com/user-attachments/assets/1a6fc700-74ba-47a6-8c06-36b700fc75f9" />

**Comment by dcapslock** [comment]
> So, `card-mod` elements will be created "on a fly" along with inner sub-elements inside a conditional element?

Yes. Already done for conditional rows in 4.0.1-beta.3. Same to be done for conditional elemets.

**Comment by dcapslock** [comment]
@ildar170975 While taking on user feedback on conditional rows, and whether to block card_mod at the conditional config level, I think it is wise to leave as is, which allows for your example below.

```yaml
  - type: conditional
    conditions: ...
    elements:
      - type: state-badge
        ...
      - type: state-label
        ...
    card_mod:
      style:
        hui-state-label-element:
          $: |
            div {
              color: red;
            }
```

Styling of the conditional elements themselves will still be added. 

This will leave your original issue here as one to document why it happens, and encourage users to migrate to styling the elements directly when available.
