### ISSUE TITLE
Where to put card_mod

### ISSUE THREAD

**Issue by udouble** [thomasloven/lovelace-card-mod#309]
Fearly new to HA. I created a dashboard, with sensor-info of last clean by my robot vacuum. This font of the text is too large:

<img width="964" alt="Scherm­afbeelding 2023-11-01 om 14 01 37" src="https://github.com/thomasloven/lovelace-card-mod/assets/15670896/56e8918d-8265-4f09-9e11-32cfe6f4ec9b">

Tried to paste the card_mod on several places within the code, without succes.

```
square: false
type: grid
cards:
  - square: false
    type: grid
    cards:
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.buienradar
        forecast_type: daily
        theme: skynet_dark_v2
      - type: custom:mushroom-media-player-card
        entity: media_player.keuken_4
        name: Muziek - Keuken
        icon: mdi:music-note
        show_volume_level: true
        use_media_info: true
        volume_controls:
          - volume_mute
          - volume_set
          - volume_buttons
        media_controls:
          - on_off
          - shuffle
          - previous
          - play_pause_stop
          - next
          - repeat
    columns: 1
  - square: false
    type: grid
    cards:
      - type: custom:mushroom-media-player-card
        name: Water bijvullen?
        icon: mdi:water
        show_volume_level: false
        use_media_info: false
        volume_controls: []
        media_controls:
          - repeat
        layout: horizontal
        fill_container: true
        entity: binary_sensor.roborock_s7_maxv_water_shortage
    columns: 3
  - square: false
    type: grid
    cards:
      - graph: none
        type: sensor
        entity: sensor.roborock_s7_maxv_last_clean_end
        detail: 1
        hours_to_show: 1
        name: Laatste schoonmaak
    columns: 1
  - square: false
    type: grid
    cards:
      - type: custom:xiaomi-vacuum-map-card
        map_source:
          camera: camera.roborock_s7_maxv_map
        calibration_source:
          camera: true
        entity: vacuum.roborock_s7_maxv
        vacuum_platform: humbertogontijo/homeassistant-roborock
        map_locked: true
    columns: 1
columns: 1
```

Can you help me out? (Sorry if my language is not as technical as it should be. I'll learn and eventually rephrase "Tried to paste the card_mod on several places within the code":-).
