### ISSUE TITLE
CSS Align lost after refresh or spent time. 

### ISSUE THREAD

**Issue by colethegamer123** [thomasloven/lovelace-card-mod#315]
My Home Assistant version: 2023.11.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing: CSS Align to Center a Logo and a Title of the Card.
Im using Card-mod, Vertical-Stack-in-Card

What I expected to happen: Align the logo and title of the card to middle.

What happened instead: Align the logo and the title of the card to middle and after refresh or minutes later it goes back to wrong place.

Good Frontend: As you can see the logo and the title of the card is aligned to the middle
![image](https://github.com/thomasloven/lovelace-card-mod/assets/62310407/f58d213a-1dd2-4037-8208-e684e53e880f)

Bad Frontend: As you can see the logo and the title of the card is not aligned
![image](https://github.com/thomasloven/lovelace-card-mod/assets/62310407/c47aeaa9-ba02-440f-b44c-93be2880282e)

Extra Info: The issue comes on Tablet, IOS Phone and Browser Google Chrome so everywhere on every device I use.

**Minimal** steps to reproduce: F5 refresh of the page

**Short description about the card for easier understanding:**
 - Im using Vertical-Stack-In-Card to make two card in a same rectangle without borders so it looks one rectangle not two.
 - Im using Card-mod for CSS Styling
 - The first card is a markdown card, where I add a picture. With Style I make the markdown card transparent and align the title next to the icon also to center and changing Font-size and other font changes. with the 'img' part of the ha-markdown I also put the icon image aligned to center just like the font.
 - The second card is a glance card, where I show financial datas, 4 entity in total. with style I also change this card to transparent so now both looks transparent and looks like one.
 
```yaml
type: custom:vertical-stack-in-card
cards:
  - type: markdown
    content: >-
      # <img width="70" height="70" src='/local/dashboard/finance.png'/> Pénzügyek
    style:
      .: |
        ha-card {
          background-color: transparent !important;
          box-shadow: none !important;
          }
      ha-markdown:
        $: |
          h1 {
            font-size: 30px;
            font-weight: bold;
            text-align: center;
            letter-spacing: '-0.02em';
            }
          img {
            vertical-align: -25px;
              }
    name: Financial Datas
  - type: glance
    entities:
      - entity: sensor.web_scrape
        name: EUR / HUF
        image: /local/dashboard/eur.png
      - entity: sensor.web_scrape_3
        name: USD / HUF
        image: /local/dashboard/dollar.png
      - entity: sensor.benya
        image: /local/dashboard/benzin95.png
        name: Benzin
      - entity: sensor.meme
        image: /local/dashboard/coin.png
        name: MEME Coin
    theme: Caule Black Gray Glass
    style:
      .: |
        ha-card {
          background-color: transparent !important;
          box-shadow: 2px !important;
        } 
    show_icon: true
    show_name: true
    show_state: true

```

Error messages from the browser console: 
![image](https://github.com/thomasloven/lovelace-card-mod/assets/62310407/8a4940a0-865a-423a-8ed9-df8770685d50)

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

Thank you Sir!
