### ISSUE TITLE
Remove breaks between entities

### ISSUE THREAD

**Issue by isidrology** [thomasloven/lovelace-card-mod#32]
I've been using the card mod and sliders and they are great!. however I don't really like the vast amount of space between each entity. E.g. between the title to the actual entity. 

Is there a css code I can use in order to remove the spacing between the entities? 

```
cards:
  - entities:
      - entity: light.entry_8
        icon: 'mdi:lightbulb-outline'
        toggle: true
        type: 'custom:slider-entity-row'
    show_header_toggle: false
    title: Entry
    type: entities
    style: |
      .card-header {
      font-size: 20px;
      }
  - entities:
      - entity: sensor.temperature_sensor_1_43
      - entity: sensor.humidity_sensor_1_45
        icon: 'mdi:water-percent'
      - entity: sensor.light_sensor_1_44
        icon: 'mdi:brightness-5'
      - entity: sensor.entry_motion
        icon: 'mdi:motion-sensor'
      - entity: sensor.entry_door
        icon: 'mdi:door-closed-lock'
    show_icon: true
    show_name: false
    show_state: true
    type: glance
type: 'custom:vertical-stack-in-card'
```
![Annotation 2020-02-17 141259](https://user-images.githubusercontent.com/49630575/74621094-a0501f00-518f-11ea-831d-726e87ea3ba0.jpg)

refer to the highlighted areas in screencap.
