### ISSUE TITLE
Bar_width not working with mushroom default/horizontal 

### ISSUE THREAD

**Issue by tungmeister** [thomasloven/lovelace-card-mod#320]
the Bar_width setting isn't being respected with the card configured in mushroom mode default/horizontal for example:
```
type: custom:timer-bar-card
entity: timer.heatingboost
name: Heating boost
icon: mdi:thermometer
bar_radius: 4px
text_width: 4em
bar_width: 50%
invert: true
mushroom:
  layout: horizontal
  color: orange
```
I've tried percentage, em and px but none have any impact.
