### ISSUE TITLE
reoccurrence of issue in ticket 275

### ISSUE THREAD

**Issue by snigehere** [thomasloven/lovelace-card-mod#321]
My Home Assistant version: 0.XX.X
Version	core-2023.12.1
Installation Type	Home Assistant OS
Python Version	3.11.6
Operating System Family	Linux
Operating System Version	6.1.63-haos
CPU Architecture	x86_64

card mod 3.3.0

My lovelace configuration method (GUI or yaml):

What I am doing:
I am using the power flow plus card and get the same error as described in this ticket which is marked closed as fixed
https://github.com/thomasloven/lovelace-card-mod/issues/275
In the power flow plus card repository this issue is tagged as being caused by the card mod package
![Snap8](https://github.com/thomasloven/lovelace-card-mod/assets/104912027/ad0ee452-5f75-48d3-9b4b-bc764b78c77d)

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
Ypu will need the power flow card plus add on

type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.smart_meter_electricity_power

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- x[] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
