### ISSUE TITLE
Card mod styled buttons not consistently working

### ISSUE THREAD

**Issue by robertboccia** [thomasloven/lovelace-card-mod#328]
My Home Assistant version: 2023.12.4

My lovelace configuration method (GUI or yaml): yaml

What I am doing: buttons styled with card mod with colours

What I expected to happen: buttons displayed with colour

What happened instead: buttons displayed in grey (no colour) 

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
card_mod: 
style: |
    ha-card {
         --ha-card-background: rgb(30,30,40);
         --card-mod-icon-color: red
      }
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
