### ISSUE TITLE
Failed to load card-mod - SOLVED REINSTALLING BOTH PLUGINS

### ISSUE THREAD

**Issue by antivirus68** [thomasloven/lovelace-card-mod#33]
My Home Assistant version: 0.105.4

My lovelace configuration method (GUI or yaml): yaml

What I am doing: basic test to see if card-mod works

```
- type: entities
          title: Family
          show_header_toggle: false
          style: |
            ha-card {
              color: red;
            }          
          entities:
            - entity: sensor.my_street
              name: John
```

What I expected to happen:

I expect "John" to be red

What happened instead:

Nothing happens.

**Minimal** steps to reproduce:

I've installed both card-mod and card-tools.

```yaml
# The least ammount of code possible to reproduce my error

- type: entities
     title: Family
     show_header_toggle: false
     style: |
         ha-card {
           color: red;
         }          
     entities:
       - entity: sensor.my_street
          name: John

# End of code
```

Error messages from the browser console:

`0:1 Uncaught TypeError: Failed to resolve module specifier "card-tools/src/templates.js". Relative references must start with either "/", "./", or "../".`

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
