### ISSUE TITLE
3.4.0 breaks mods on card-mod-sidebar-yaml: ?

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#330]
As title.
not sure this is caused by HA 2024.1 (Bram said nothing changed regarding to the side bar) or card mod, and if the latter, dont understand why the listed change would impact it.

hope anyone finding this can help out solving if a config error, or Author if resource error

My Home Assistant version: 2024.1.0b0

My lovelace configuration method (GUI or yaml): Yaml

What I am doing:

modding the side bar icons and adding some extra notifications, see https://community.home-assistant.io/t/card-mod-super-charge-your-themes/212176/1448?u=mariusthvdb

What I expected to happen:

icons colored and added notification

![Scherm­afbeelding 2023-06-29 om 15 43 22](https://github.com/thomasloven/lovelace-card-mod/assets/33354141/653e5b0b-d77c-4a7c-9049-6cd76a4ff07a)

What happened instead:

nothing.....
**Minimal** steps to reproduce:

add a notification under the menu title
```yaml
# The least amount of code possible to reproduce my error
      .menu .title:after {
        content: "{%- set count = states('sensor.marquee_alerts')|int(default=0) %}
                  {%- set phrase = 'Alert: ' if count == 1 else 'Alerts:' -%}
                  {{'\A ' ~ phrase ~ count if count > 0 }}";
        white-space: pre;
        font-size: 12px;
        font-weight: bold;
        display: block;
        line-height: 4px;
        color: var(--alert-color);
      }
# End of code
```

or mods like this on menu items:

```
      a[data-panel='ui-overzicht'] paper-icon-item ha-icon {
        --card-mod-icon: {{'mdi:home-alert' if alerts else 'mdi:home'}};
        color: {{'var(--alert-color)' if alerts else 'green'}};
      }
```

Error messages from the browser console:

no errors

More-info:

Ive had issues before, see https://community.home-assistant.io/t/card-mod-super-charge-your-themes/212176/1425?u=mariusthvdb, but then the element that needed modding was changed and after doing so, these mods were rock solid on previous version.

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
