### ISSUE TITLE
 3.4.0:  outdated signature for <code>applyElement</code>

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#338]
My Home Assistant version: 2024.1.0b02

My lovelace configuration method (GUI or yaml):Yaml

What I am doing:

using custom:fold-entity-row

What I expected to happen:
no error
What happened instead:
see screen below

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
      card_mod:
        style: |
          .label {
            margin-left: 0px !important;
          }

# End of code

```

Error messages from the browser console:

<img width="851" alt="Scherm­afbeelding 2023-12-30 om 22 38 14" src="https://github.com/thomasloven/lovelace-card-mod/assets/33354141/8eef87a3-c3f4-476a-9ce0-7b0b7e032330">

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
