### ISSUE TITLE
Heap/memory problem with own room card

### ISSUE THREAD

**Issue by sonyboypatrick** [thomasloven/lovelace-card-mod#343]
My Home Assistant version: 2023.12.4

My lovelace configuration method (GUI or yaml): GUI with Yaml Code

What I am doing: I use cardmod in combination with the custom:mushroom-template-card to create a "room card" (I copied some parts from the internet and it exactly looks like i want it to be)

What I expected to happen: everything should work and the browser shouldnt "freeze"

What happened instead:  the browser "freezes" after some minutes, I'm not able to click on settings or anything like that

If I remove all cardmod related code from this single view the page doesnt freeze. I allreadytried to use the dev tools of chrome and i can see the memory/heap usage seams to increase if I wait some time. I dont really know how to debug/go on.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

type: custom:vertical-stack-in-card
cards:
  - type: custom:mushroom-template-card
    entity: light.licht_im_wohnzimmer
    icon: mdi:sofa
    icon_color: >
      {{ '#%02x%02x%02x' % state_attr(entity, 'rgb_color') if states(entity) ==
      'on' else 'light-green' }}
    primary: Wohnzimmer
    layout: horizontal
    tap_action:
      action: navigate
      navigation_path: /lovelace-locations/living-room
    double_tap_action:
      action: navigate
      navigation_path: /lovelace-locations/living-room
    hold_action:
      action: toggle
    card_mod:
      style:
        mushroom-state-info$: |
          .container {
            position: absolute;
            left: 0;
            top: 70px;
            width: 100%;
            text-align: center;
          }
          .primary {
            font-size: 25px !important;
            width: 100%;
            color: var(--primary-text-color) !important;
          }
        mushroom-shape-icon$: |
          .shape {
            position: relative;
            left: -35px;
            top: 63px;
          }
        .: |
          :host {
            --mush-icon-size: 130px;
          }
        style: |
          ha-card {
            width: 100%; !important;
            background: none;
          }
  - type: custom:mushroom-template-card
    primary: none
    icon_color: disabled
    icon: mdi:lightbulb
    secondary: none
    entity: light.licht_im_wohnzimmer
    tap_action:
      action: navigate
      navigation_path: /dashboard-lights/living-room
    hold_action:
      action: toggle
    double_tap_action:
      action: more-info
    card_mod:
      style:
        mushroom-shape-icon$: |
          .shape {
            {% if is_state(config.entity, 'on') %}
              {% if state_attr(config.entity, 'rgb_color') == none %}
                --icon-color: rgb(255,190,137) !important;
                --shape-color: rgb(255,190,137, 0.2 ) !important;
              {% else %}
                {% set r = state_attr(config.entity, 'rgb_color')[0] %}
                {% set g = state_attr(config.entity, 'rgb_color')[1] %}
                {% set b = state_attr(config.entity, 'rgb_color')[2] %}
                --icon-color: rgb( {{r}}, {{g}}, {{b}} ) !important;
                --shape-color: rgba( {{r}}, {{g}}, {{b}}, 0.2 ) !important;
              {% endif %}
            {% endif %}
          }
        .: |
          ha-card {
            width: 66px;
            position: absolute;
            top: 0;
            right: 0;
            background: none;
          }
          :host {
            --mush-icon-size: 38px;
          }
  - type: custom:mushroom-template-card
    primary: none
    icon_color: |
      {{ 'light-green' if states(entity) ==  'playing' else 'disabled' }}
    icon: phu:echo-show-8-gen-2
    secondary: none
    entity: media_player.echo_show_wohnzimmer
    tap_action:
      action: navigate
      navigation_path: /dashboard-media/echo-show-wohnzimmer
    card_mod:
      style:
        .: |
          ha-card {
            width: 66px;
            position: absolute;
            top: 45px;
            right: 0px;
            background: none;
          }
          :host {
            --mush-icon-size: 38px;
          }
  - type: custom:mushroom-template-card
    primary: none
    icon_color: |
      {{ 'light-green' if states(entity) ==  'on' else 'disabled' }}
    icon: mdi:television
    secondary: none
    entity: media_player.tv_wohnzimmer
    tap_action:
      action: more-info
    card_mod:
      style:
        .: |
          ha-card {
            width: 66px;
            position: absolute;
            top: 90px;
            right: 0px;
            background: none;
          }
          :host {
            --mush-icon-size: 38px;
          }
  - type: custom:mushroom-chips-card
    chips:
      - type: entity
        entity: sensor.ble_temperature_sensor_kuche
        icon: mdi:thermometer
      - type: entity
        entity: sensor.ble_humidity_sensor_kuche
        icon: mdi:water
      - type: template
        entity: light.tv_wohnzimmer_ambilight
        icon_color: |
          {{ 'light-green' if states(entity) ==  'on' else 'disabled' }}
        icon: mdi:television-ambient-light
        tap_action:
          action: more-info
      - type: template
        icon: mdi:television-guide
        tap_action:
          action: navigate
          navigation_path: /dashboard-media/tvguide
      - type: template
        icon: mdi:movie
        tap_action:
          action: navigate
          navigation_path: /dashboard-media/trakt
    card_mod:
      style:
        .: |
          ha-card {
            width: 80%;
            position: absolute;
            left: 12px;
            top: 12px;
            background: none;
            --chip-border-width: 0;
            --chip-box-shadow: none;
          }
          :host {
            --mush-icon-size: 20px;
            --mush-chip-spacing: 5px;
            --mush-chip-background: none;
            --mush-chip-box-shadow: none;
          }
card_mod:
  style: |
    ha-card {
      height: 178px !important;
      width: 100%; !important;
      {% if is_state('light.licht_im_wohnzimmer', 'on') %}
      {% if state_attr('light.licht_im_wohnzimmer', 'rgb_color') == none %}
      background: rgb(255,190,137, 0.2 ) !important;
      {% else %}
      {% set r = state_attr('light.licht_im_wohnzimmer', 'rgb_color')[0] %}
      {% set g = state_attr('light.licht_im_wohnzimmer', 'rgb_color')[1] %}
      {% set b = state_attr('light.licht_im_wohnzimmer', 'rgb_color')[2] %}
      background: rgba( {{r}}, {{g}}, {{b}}, 0.2 ) !important;
      {% endif %}
      {% else %}
      background: rgba(139, 195, 74, 0.1);
      {% endif %}
    }
view_layout:
  grid-area: livingroom


# End of code
```

![image](https://github.com/thomasloven/lovelace-card-mod/assets/1961296/3378945f-e403-4a77-b6d0-d4af7c908f81)

Error messages from the browser console:

Code Hung Up or if I use more cards of this type I get an out of memory error

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- X[] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

Thanks in advance

Patrick
