### ISSUE TITLE
Cards Loading Slower in card-mod 3.4.1

### ISSUE THREAD

**Issue by Anashost** [thomasloven/lovelace-card-mod#346]
### My Home Assistant version:
2023.12.4 / 2024.1.2

### My lovelace configuration method (GUI or yaml):
GUI

### What I expected to happen:
how card used to load in `Card-mod 3.4.0`

<img src="https://github.com/thomasloven/lovelace-card-mod/assets/41167157/a61a119e-a66f-4233-a91d-10f394c66875" width=75% height=75%>

### What happened instead:
how cards are loading in `Card-mod 3.4.1`
same issue in android HA app and browser (tested chrome/ brave)

<img src="https://github.com/thomasloven/lovelace-card-mod/assets/41167157/7e472a9f-efc2-44c6-a206-c1af764a69da" width=75% height=75%>

**Minimal** steps to reproduce:

`yaml of the cards above`:

Note: the slowness is only visible in a crowded page.

```yaml
type: custom:stack-in-card
card_mod:
  style: |
    ha-card {
       {% if is_state('group.office_lights', 'on') %}
       background: rgba(255, 152, 0, 0.1);
       {% endif %}
      }
mode: vertical
keep:
  outer_padding: false
cards:
  - type: custom:mushroom-template-card
    card_mod:
      style:
        mushroom-shape-icon$: |
          @keyframes ping {
            0% { box-shadow: 0 0 1px 1px rgba(var(--rgb-{{ config.icon_color }}), 0.7); }
            100% { box-shadow: 0 0 5px 15px transparent; }
          }
        .: |
          mushroom-shape-icon {
            --icon-size: 76px;
            display: flex;
            margin: -20px 0px 0px -20px !important;
          }
          ha-card {
            clip-path: inset(0 0 0 0 round var(--ha-card-border-radius, 12px));
          }
    primary: Office
    secondary: ''
    icon: mdi:bed
    layout: horizontal
    entity: group.office_lights
    icon_color: |-
      {% if is_state('group.office_lights','on')%}
       amber
      {%endif%}
    tap_action:
      action: navigate
      navigation_path: office
    hold_action:
      action: toggle
    double_tap_action:
      action: none
    badge_color: ''
    badge_icon: ''
    fill_container: true
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        tap_action:
          action: none
        state:
          - operator: default
            color: grey
          - value: 'on'
            color: orange
        icon: mdi:lightbulb-group
        entity: group.office_lights
        styles:
          icon:
            - width: 19px
          grid:
            - position: relative
          custom_fields:
            notification:
              - border-radius: 50%
              - position: absolute
              - left: 50%
              - top: 3%
              - height: 20px
              - width: 20px
              - font-size: 10px
              - line-height: 20px
              - font-weight: bold
          card:
            - border-radius: 50%
            - width: 40px
            - height: 40px
        custom_fields:
          notification: |
            [[[
               if (states['sensor.office_lights_of_count'].state == '0')
                return ' '
               return `${states['sensor.office_lights_of_count'].state}`
            ]]]
        name: ' '
      - type: custom:button-card
        state:
          - value: 'on'
        icon: mdi:thermometer
        entity: sensor.office_temperature
        styles:
          icon:
            - color: |
                [[[
                    return `${states['sensor.office_temp_color'].state}`
                ]]]
            - width: 15px
            - position: relative
            - top: 4px
            - right: 12px
          card:
            - border-radius: 80%
            - width: 40px
            - height: 40px
          name:
            - color: white
            - font-size: 10px
            - position: relative
            - bottom: 10px
            - left: 5px
            - font-weight: bold
        name: |
          [[[
            if (states['sensor.office_temperature'].state == 'unknown')
             return '-'
            return `${states['sensor.office_temperature'].state}°`
          ]]]

```

### Error messages from the browser console:

none
