### ISSUE TITLE
Icons in Tile cards no longer change color based on the state of another entity, after Update 3.4.0 - 3.4.1

### ISSUE THREAD

**Issue by Fullmetal11** [thomasloven/lovelace-card-mod#347]
My Home Assistant version: 2024.1.2

My lovelace configuration method (GUI or yaml):

What I am doing: change the color of the icon of a tile card based on the state of another entity

What I expected to happen: when i pressed the tile card, i expect to change the color of the tile card like this: red if the input boolean "example" is on, white if it is off.

What happened instead: nothing

Before the update to 3.4.0 it worked great :(
I have lots of tiles card that change the color of their icons based on the value of another entity... they're all screwed up now..

**Minimal** steps to reproduce:

```yaml

type: tile
entity: sensor.any_sensor_you_want
icon_tap_action:
  action: call-service
  service: input_boolean.toggle
  target:
    entity_id: input_boolean.example
  data: {}
card_mod:
  style: |
    .tile {
      {% if is_state("input_boolean.example", "on") %}
        --tile-color:red;
      {% else %}  
        white;
      {% endif %}  
    }

# End of code
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
