### ISSUE TITLE
mod-card injecting styles

### ISSUE THREAD

**Issue by Gluwc** [thomasloven/lovelace-card-mod#35]
**My Home Assistant version:** 0.105.5

**My lovelace configuration method (GUI or yaml):**
GUI

**What I am doing:**
Using mod-card.

**What I expected to happen:**
Not inject styles into my lovelace config.

**What happened instead:**
It injects styles into my lovelace config. ;)
```yaml
      - type: 'custom:mod-card'
        style: |-

          ha-card {
            background: none;
            box-shadow: none;
          }
          ha-card {
            background: none;
            box-shadow: none;
          }
          ha-card {
            background: none;
            box-shadow: none;
          }
          ha-card {
            background: none;
            box-shadow: none;
          }
```

****Minimal** steps to reproduce:**
Use card-mod to modify a vertical stack.

```yaml
- type: 'custom:mod-card'
  style: |-
    ha-card {
      padding: 2px;
    }
  card:
    type: 'vertical-stack'
    cards:
    ...
```

**Error messages from the browser console:**
None

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
