### ISSUE TITLE
Icon color mod doesn't work in Android app after latest updates

### ISSUE THREAD

**Issue by JaybeRF** [thomasloven/lovelace-card-mod#350]
My Home Assistant version: 2024.1.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing:

I created auto-entities card, if battery is > 69% or has state high, icon should be green. If battery state is numeric everything is ok, for high/low state i use card mod.

What I expected to happen:

Icons of entities should be green in both web and app

What happened instead:

After some updates (can't say what exactly) icons on web are green as usual but in android app they are default blue, so card mod is not working for HA companion

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

type: custom:auto-entities
show_empty: false
card:
  type: entities
  state_color: true
filter:
  include:
    - entity_id: '*batt*'
      state: '> 69'
    - entity_id: '*batt*'
      state: high
      options:
        style: |
          :host {
            --card-mod-icon-color: #4caf50;
          }
sort:
  method: state
  numeric: true


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
