### ISSUE TITLE
Frontend 20240131.0 issues

### ISSUE THREAD

**Issue by jeremynoesen** [thomasloven/lovelace-card-mod#355]
My Home Assistant version: 2024.1.6

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Modifying the margins of cards (mainly in horizontal stacks)

What I expected to happen: Margins would be modified and the correct size (behavior before frontend 20240131.0)

What happened instead: Due to new changes to lovelace card margins, [mainly from this commit](https://github.com/home-assistant/frontend/pull/19563/commits/8d973bc7a94c7f1b635e9ee766d64e83d3f9a102#diff-86cd35ed0527176dedd9492bb7408a3c3ef7a92041a6b93293ed92d84db49192), margins are not correct when modifying horizontal margins. They are now smaller than actual and inconsistent.

**Minimal** steps to reproduce: Create a mod-card, put a horizontal stack as the card, put 2-3 cards in the stack, and set the margin to something larger than normal.

```yaml
# The least amount of code possible to reproduce my error
views:
  - title: Test
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              --horizontal-stack-card-margin: 0 24px 0 0 !important;
            }
        card:
          type: horizontal-stack
          cards:
            - show_name: true
              show_icon: true
              type: button
              name: Test
              icon: mdi:test-tube
            - show_name: true
              show_icon: true
              type: button
              name: Test
              icon: mdi:test-tube
            - show_name: true
              show_icon: true
              type: button
              name: Test
              icon: mdi:test-tube
# End of code
```

Error messages from the browser console: None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
