### ISSUE TITLE
primary-text-color no longer working?

### ISSUE THREAD

**Issue by walk0080** [thomasloven/lovelace-card-mod#356]
My Home Assistant version: Core 2024.1.6 | Frontend 20240104.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing:

Setting primary text colour as red or green.

What I expected to happen:

Certain text should be colour coded green (for yes) and red (for no).
This was working yesterday. Seems to be an issue on iOS/iPadOS Companion App, mobile and desktop browsers.

What happened instead:

As of today, the text just stays white and does not change based on state.
Not sure if this is specifically an issue with card-mod, or mushroom-template (both are using latest versions installed via HACS).

**Minimal** steps to reproduce:

Loaded up HA in Companion App this morning and text colours no longer change.

```yaml
# The least amount of code possible to reproduce my error
          - type: custom:mushroom-template-card
            primary: |-
              {% set state=states('input_boolean.dog_henry_feeding_required') %}
              {% if state=='on' %}
                Yes
              {% else %}
                No
              {% endif %}
            secondary: Feed Reqd?
            icon: ''
            entity: input_boolean.dog_henry_feeding_required
            icon_color: white
            tap_action:
              action: more-info
            hold_action:
              action: more-info
            double_tap_action:
              action: more-info
            multiline_secondary: false
            fill_container: false
            card_mod:
              style:
                mushroom-state-info $: |
                  .container {
                    --card-secondary-font-size: 14px;
                    --card-primary-font-size: 16px;
                  }
                .: |
                  ha-card {
                    {% set state=states('input_boolean.dog_henry_feeding_required') %}
                    {% if state=='on' %}
                      --primary-text-color: red
                    {% else %}
                      --primary-text-color: green
                    {% endif %}
                    }
# End of code
```

Error messages from the browser console:

No errors in HA logs or in Chrome browser Console.

Was able to get a screen cap from phone before it refreshed:
![IMG_1727](https://github.com/thomasloven/lovelace-card-mod/assets/22773927/ad9dd6e2-c50b-4d6b-9451-69381c9a7fd1)

Screen cap from tablet this morning:
![IMG_1794](https://github.com/thomasloven/lovelace-card-mod/assets/22773927/aa5c595b-03ca-4e44-9e94-108f6bb40168)

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
