### ISSUE TITLE
Extremly Slow and Stuck

### ISSUE THREAD

**Issue by milandzuris** [thomasloven/lovelace-card-mod#359]
HA: 2024.2+
Card Mod: 3.4.2
Logs: Clear
Cache: clear
Chrome
Same problem on Phones

From new Update HA 2024.2+ every Card where is Customized with Card Mod extremly slow load i mean few seconds 5-20, i dont know is this problem in Card Mod or HA Frontend, or after few minutes Dashboard it gets stuck and freezes

**Comment by ToViNi** [comment]
Same here.  Heavy use of card-mod.  Complex pages.  Gone from 3-4 seconds update time to a 30-60 seconds.  Often the pages stops without finishing loading all elements, or finish "modding".  All browsers.  Good HW and network.  Revert to 2024.1.x solves the problem. Profiler shows that scripting uses up "all" the time, card-mod js.  Lovelace seems to be a bit slower on 2024.2.x on pages not using card-mod too, but not sure about that.  HA is not eating CPU, but the browser uses a lot!

**Comment by milandzuris** [comment]
> Same here. Heavy use of card-mod. Complex pages. Gone from 3-4 seconds update time to a 30-60 seconds. Often the pages stops without finishing loading all elements, or finish "modding". All browsers. Good HW and network. Revert to 2024.1.x solves the problem. Profiler shows that scripting uses up "all" the time, card-mod js. Lovelace seems to be a bit slower on 2024.2.x on pages not using card-mod too, but not sure about that. HA is not eating CPU, but the browser uses a lot!

I have exactly the same thing, and I'm already really dialed in. today Dashboard didn't work at all through my PC

**Comment by effelle** [comment]
Holy crap...
I'm on HA: 2024.3 and Card Mod: 3.4.2 too and I spent literally a day to try to understand what card was causing the issue.
In my case I saw the browser became unresponsive until showing an out of memory issue. The server works fine as expected, just the browsers, Chromium on linux and Chrome for Windows, are killed. 
Didn't realize it could be a possible issue with Card Mod. As a test I replaced the customized cards (mostly mushroom) with some stock cards and the lags disappeared.  I know CSS mod and templating can hammer the CPU but I think that's really too much.
Here is a YAML snippet of a card causing the lag issue, perhaps  @thomasloven  could find some useful tip:
```yaml
- type: custom:vertical-stack-in-card
  cards:
    - type: custom:mushroom-template-card
      entity: null
      icon: null
      icon_color: null
      picture: '{{ state_attr(''sensor.forecast_d5'', ''picture'') }}'
      primary: '{{ states.sensor.forecast_d5.state }}'
      secondary: '{{ state_attr(''sensor.forecast_d5'', ''condition'') }}'
      layout: vertical
      card_mod:
        style:
          mushroom-state-info$: |
            .primary {
              font-size: 22px !important;
              position: relative;
              top: -130px;
              left: 0px;
              overflow: visible !important;
              white-space: normal !important;
            }
            .secondary {
              font-size: 22px !important;
              position: relative;
              overflow: visible !important;
              top: -15px;
              left: 0px;
            }
          mushroom-shape-avatar$: |
            .picture {
              top: 16px;
              left: -50px;
              position: relative;                    
            }
          .: |
            :host {
              --mush-icon-size: 120px;
            }
    - type: custom:mushroom-template-card
      primary: '{{ state_attr(''sensor.forecast_d5'', ''temperature'') }}°C'
      icon: mdi:thermometer
      icon_color: gray
      secondary: none
      card_mod:
        style:
          mushroom-state-info$: |
            .primary {
              font-size: 15px !important;
              position: relative;
              top: 8px;
              left: 0px;
              overflow: visible !important;
              white-space: normal !important;
            }
          .: |
            ha-card {
              width: 66px;
              margin-left: 50%;
              top: -163px;
              background: none;
              text-align: right !important;
            }
            :host {
              --mush-icon-size: 35px;
            }
    - type: custom:mushroom-template-card
      primary: '{{ state_attr(''sensor.forecast_d5'', ''humidity'') }}%'
      icon: mdi:water-percent
      icon_color: gray
      secondary: none
      card_mod:
        style:
          mushroom-state-info$: |
            .primary {
              font-size: 15px !important;
              position: relative;
              top: 8px;
              left: 0px;
              overflow: visible !important;
              white-space: normal !important;
            }
          .: |
            ha-card {
              width: 66px;
              margin-left: 50%;
              top: -194px;
              background: none;
            }
            :host {
              --mush-icon-size: 35px;
            }
    - type: custom:mushroom-template-card
      primary: >-
        {{ state_attr('sensor.forecast_d5', 'rain_probability')
        }}%
      icon: mdi:weather-pouring
      icon_color: gray
      secondary: none
      card_mod:
        style:
          mushroom-state-info$: |
            .primary {
              font-size: 15px !important;
              position: relative;
              top: 8px;
              left: 0px;
              overflow: visible !important;
              white-space: normal !important;
            }
          .: |
            ha-card {
              width: 66px;
              margin-left: 50%;
              top: -225px;
              background: none;
            }
            :host {
              --mush-icon-size: 35px;
            }
  card_mod:
    style: |
      ha-card {
        height: 180px !important;
        width: 264px !important;
        --ha-card-border-width: 0;
      }
```
I'm really hoping the cause of the issue is my bad CSS styling...  :P
This card is part of a collection I have in a dashboard for my display in the living room (WIP):

![meteo](https://github.com/thomasloven/lovelace-card-mod/assets/7702766/5a306191-8298-4fb0-aa0f-85ae246850d2)

Since are all new cards, I can't really say if the browsers  were responsive before the latest updates.
