### ISSUE TITLE
custom:mod-card is broken in 0.106.0 due to Lovelace changes

### ISSUE THREAD

**Issue by Knapoc** [thomasloven/lovelace-card-mod#36]
My Home Assistant version: 0.106.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Applying custom styles on vertical-stack-in cards.

What I expected to happen:
No errors

What happened instead:
Errors due to recent Lovelace changes: https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/

**Minimal** steps to reproduce:

```yaml
- type: custom:mod-card
              style: |
                ha-card {
                  background-color: var(--primary-background-color);
                  border-radius: 15px;
                  box-shadow: 
                    {% if is_state('sun.sun', 'above_horizon') %}
                      -4px -4px 4px 0 rgba(255,255,255,.5),4px 4px 4px 0 rgba(0,0,0,.03);
                    {% else %}
                      -4px -4px 4px 0 rgba(50, 50, 50,.5),4px 4px 4px 0 rgba(0,0,0,.15);
                    {% endif %}
                }
              card:
                type: custom:vertical-stack-in-card
                cards:
                  - type: glance
                    title: Home Assistant
                    columns: 7
                    show_name: false
                    entities:
                      - entity: sensor.count_automations
                      - entity: sensor.count_binary_sensors
                  - type: entities
                    show_header_toggle: false
                    entities:
                      - entity: sensor.potential_breaking_changes
                      - entity: input_select.log_level
            
```

Error messages from the browser console:
[Error] mod-card
TypeError: Attempted to assign to readonly property.
setConfig — card-mod.js:1:7794
o — hui-warning-element.ts:18
_createCardElement — hui-horizontal-stack-card.ts:21
_rebuildCard — hui-horizontal-stack-card.ts:21
(anonymous function) — hui-horizontal-stack-card.ts:21
dispatchEvent
r — fire_event.ts:76
(anonymous function) — hui-warning-element.ts:18
promiseReactionJob
	o (chunk.a7f86c7205b90ff898cc.js:2212:232412)
	_createCardElement (chunk.a7f86c7205b90ff898cc.js:2696:328273)
	_rebuildCard (chunk.a7f86c7205b90ff898cc.js:2696:328458)
	(anonymous function) (chunk.a7f86c7205b90ff898cc.js:2696:328389)
	dispatchEvent
	r (app.83a8dbf7.js:2:45042)
	(anonymous function) (chunk.a7f86c7205b90ff898cc.js:2212:232735)
	promiseReactionJob

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
