### ISSUE TITLE
Debug showing (Re)connecting over and over again in 

### ISSUE THREAD

**Issue by rubin110** [thomasloven/lovelace-card-mod#363]
My Home Assistant version: 2024.2.5

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Attempting to debug issues possibly related to #354, where after some reloads of the page none of my custom styles are loading, I enabled `debug:` in order to get some logs.

What I expected to happen:
Honestly I don't know.

What happened instead:
My browser's debug console is flooded with `CardMod Debug: (Re)connecting`, multiple per second. Concerned this isn't normal behavior and that something is stuck in a loop somewhere. Searching the repo for this error only turned up the [bit of code that produces it](https://github.com/thomasloven/lovelace-card-mod/blob/4de5148a02d748d400bb4599c17020ca951bb64f/src/card-mod.ts#L159), and I'm having a hard time deciphering it's intent, I cannot find any other documentation about it.

My apologies if what's happening here is normal and common knowledge.

**Minimal** steps to reproduce:

```yaml
type: custom:mushroom-climate-card
entity: climate.thermostat
layout: vertical
fill_container: true
show_temperature_control: true
hvac_modes:
  - heat
  - cool
  - fan_only
  - 'off'
collapsible_controls: true
icon: ''
card_mod:
  debug: true
  style: |
    :host {
      --mush-icon-size: 2.87em !important;
      --mush-icon-symbol-size: 2.5em !important;
      --mush-badge-size: 1.6em !important;
      --mush-badge-icon-size: 1.1em !important;
    }
```

Error messages from the browser console:

```
card-mod.js?hacstag=190927524342:1 CardMod Debug: (Re)connecting <card-mod slot=​"none" card-mod-type=​"card" style=​"display:​ none;​">​…​</card-mod>​
card-mod.js?hacstag=190927524342:1 CardMod Debug: (Re)connecting <card-mod slot=​"none" card-mod-type=​"card" style=​"display:​ none;​">​…​</card-mod>​
card-mod.js?hacstag=190927524342:1 CardMod Debug: (Re)connecting <card-mod slot=​"none" card-mod-type=​"card" style=​"display:​ none;​">​…​</card-mod>​
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
