### ISSUE TITLE
Cardmod lose setting

### ISSUE THREAD

**Issue by duczz** [thomasloven/lovelace-card-mod#364]
My Home Assistant version: 24.3.1

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Cardmod lose setting when i try to edit the second card_mod setting

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Proxmox
    subtitle: Proxmox v{{ state_attr('update.proxmox_ve_update', 'installed_version') }}
    card_mod:
      style: |
        ha-card {
         --title-spacing: 10px 10px 10px;
         margin-bottom: -10px;
         }
  - type: custom:mushroom-chips-card
    chips:
      - type: entity
        entity: sensor.processor_use
        icon_color: blue
        use_entity_picture: false
      - type: entity
        entity: sensor.qemu_homeassistant_107_prozentsatz_genutzter_arbeitsspeicher
        icon_color: orange
      - type: entity
        entity: sensor.disk_use_percent_config
        icon_color: grey
  - type: entities
    entities:
      - entity: binary_sensor.node_proxmox_status
        name: Status
        state_color: true
      - type: custom:bar-card
        entities:
          - entity: sensor.qemu_homeassistant_107_cpu_auslastung
            name: CPU
            min: 0
            max: 100
        decimal: 2
        positions:
          icon: outside
          name: inside
          value: inside
          indicator: inside
          title: inside
          minmax: inside
        severity:
          - color: '#d32f2f'
            from: 90
            to: 100
          - color: '#ffa000'
            from: 75
            to: 90
          - color: '#388e3c'
            from: 0
            to: 75
        card_mod:
          style: |
            ha-card {
              padding: 0px;
              border-width: 0px !important;
              background: none
            }
            ha-card { 
              background: var(--card-background-color);
              margin-left: -16px;
              margin-right: -16px;
              margin-top: -20px;
              margin-bottom: -20px;
              }
            bar-card-backgroundbar {
              border-radius: 8px;
            }
            bar-card-currentbar {
              border-radius: 8px;
            }
      - entity: sensor.qemu_homeassistant_107_freier_arbeitsspeicher
        name: Arbeitsspeicher
        icon: mdi:memory
        state_color: true
        type: custom:multiple-entity-row
        show_state: false
        column: true
        entities:
          - entity: sensor.qemu_homeassistant_107_freier_arbeitsspeicher
            name: Frei
            format: precision2
          - entity: sensor.qemu_homeassistant_107_prozentsatz_freier_arbeitsspeicher
            name: Genutzt
            format: precision2
      - entity: sensor.storage_local_prozentsatz_belegter_speicherplatz
        name: Speicher
        icon: mdi:memory
        state_color: true
        type: custom:multiple-entity-row
        show_state: false
        column: true
        entities:
          - entity: sensor.storage_local_prozentsatz_belegter_speicherplatz
            name: Frei
            format: precision2
          - entity: sensor.storage_local_lvm_prozentsatz_belegter_speicherplatz
            name: Genutzt
            format: precision2
      - entity: sensor.node_proxmox_freier_arbeitsspeicher
        name: Arbeitsspeicher
        icon: mdi:memory
        state_color: true
        type: custom:multiple-entity-row
        show_state: false
        column: true
        entities:
          - entity: sensor.node_proxmox_freier_arbeitsspeicher
            name: Frei
            format: precision2
          - entity: sensor.node_proxmox_genutzter_arbeitsspeicher
            name: Genutzt
            format: precision2
      - entity: binary_sensor.node_proxmox_updates_packages
        name: Arbeitsspeicher
        icon: mdi:memory
        state_color: false
        type: custom:multiple-entity-row
        show_state: false
        column: true
        entities:
          - entity: binary_sensor.node_proxmox_updates_packages
            name: false
          - entity: sensor.node_proxmox_total_updates
            name: 'Updates:'
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.qemu_homeassistant_107_status
            state_color: true
            name: Status
          - entity: sensor.qemu_homeassistant_107_cpu_auslastung
            name: CPU-Auslastung
          - entity: sensor.qemu_homeassistant_107_freier_arbeitsspeicher
            name: Arbeitsspeicher
            icon: mdi:memory
            state_color: true
            type: custom:multiple-entity-row
            show_state: false
            column: true
            entities:
              - entity: sensor.qemu_homeassistant_107_freier_arbeitsspeicher
                name: Frei
                format: precision2
              - entity: sensor.qemu_homeassistant_107_genutzter_arbeitsspeicher
                name: Genutzt
                format: precision2
        title: 'VM HomeAssistant '
      - type: entities
        entities:
          - entity: binary_sensor.lxc_tasmoadmin_104_status
            state_color: true
            name: Status
          - entity: sensor.lxc_tasmoadmin_104_cpu_auslastung
            name: CPU-Auslastung
          - entity: sensor.lxc_tasmoadmin_104_freier_arbeitsspeicher
            name: Arbeitsspeicher
            icon: mdi:memory
            state_color: true
            type: custom:multiple-entity-row
            show_state: false
            column: true
            entities:
              - entity: sensor.lxc_tasmoadmin_104_freier_arbeitsspeicher
                name: Frei
                format: precision2
              - entity: sensor.lxc_tasmoadmin_104_genutzter_arbeitsspeicher
                name: Genutzt
                format: precision2
        title: LXC TasmoAdmin
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [] Have made sure I am using the latest version of the plugin.

- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
