### ISSUE TITLE
Issue styling Card Header

### ISSUE THREAD

**Issue by Jab2870** [thomasloven/lovelace-card-mod#366]
My Home Assistant version: 2024.3.0

My lovelace configuration method (GUI or yaml): Mixture of both

What I am doing: Trying to style card-header

What I expected to happen: header to go green

What happened instead: Nothing

**Minimal** steps to reproduce:

The following is mostly taken from one of the [test cases in the repo](https://github.com/thomasloven/lovelace-card-mod/blob/f59abc785eabb689ac42a9076197254421f96c60/test/views/1_cards.yaml#L111), although for a different card type

```yaml
type: custom:hourly-weather
entity: weather.pirateweather
icons: true
show_precipitation_amounts: true
show_precipitation_probability: true
card_mod:
  style: |
    ha-card {
      color: red;
    }
    .card-header {
      color: green;
    }
```

![image](https://github.com/thomasloven/lovelace-card-mod/assets/1909202/da141be1-0fb0-4552-9afd-0654dc7840df)

I would expect the card-header here to be green.

Confirmation here that the card is using the standard "card-header" class which I would have thought the css selector would be selecting.

![image](https://github.com/thomasloven/lovelace-card-mod/assets/1909202/f4238784-c378-4823-99de-c25ceab6c556)

Error messages from the browser console: none relevant

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
