### ISSUE TITLE
Border radius not applying to mod-card

### ISSUE THREAD

**Issue by jeremynoesen** [thomasloven/lovelace-card-mod#369]
My Home Assistant version: 2024.4.0b3

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Using a theme, I am applying a border radius to all cards.

What I expected to happen: All cards should have said border radius.

What happened instead: Cards placed within a mod card do not have the border radius, and instead have a 0px border radius.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
# No border radius
views:
  - type: panel
    path: default
    icon: ''
    theme: test
    cards:
      - type: custom:mod-card
        card:
          type: vertical-stack
          cards:
            - type: button
              icon: mdi:ab-testing
            - type: button
              icon: mdi:ab-testing

# Border radius present
views:
  - type: panel
    path: default
    icon: ''
    theme: test
    cards:
      - type: vertical-stack
        cards:
          - type: button
            icon: mdi:ab-testing
          - type: button
            icon: mdi:ab-testing

# Theme
test:
  ha-card-border-radius: 28px
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by mcv93us** [comment]
Same problem for me also with version 2024.4.1 of Home Assistant.

**Comment by ildar170975** [comment]
2024.4.1
3.4.3

What am I missing here?
See no issues.

```
type: custom:mod-card
card:
  type: vertical-stack
  cards:
    - type: button
      icon: mdi:ab-testing
    - type: button
      icon: mdi:ab-testing
```

default theme:

![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/405213e7-f0f5-4616-b58b-9cd64a20c56c)

![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/bbf241d2-512e-48e8-b0bf-a218b7b28ba5)

![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/0be5caf8-83e5-47f7-91c4-c5ab24f551c3)

custom theme:
```
test_minimal:
  ha-card-border-radius: 28px
```
![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/4dce4193-af43-4fb0-95f2-464c3c48bff1)

![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/3114eaad-16ef-4472-8c46-f7b4a9abc2ed)

![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/06337ba9-ac95-43f5-84bf-e89ddbdbefa3)
