### ISSUE TITLE
Outdated signature on Home Assistant entity card

### ISSUE THREAD

**Issue by dhoeben** [thomasloven/lovelace-card-mod#377]
My Home Assistant version: 2024.5.4

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Using a Home Assistant standard card

What I expected to happen: To not get this error

What happened instead: I got this error

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - type: entities
    card_mod:
      style: |
        ha-card {
          --switch-checked-track-color: rgb(var(--yellow));
        }
        #states div {
          margin: 0px 0px;
        }
    entities:
    - entity: light.boven
      state_color: false

# End of code
```

Error messages from the browser console:
```

You are using a custom card which relies on card-mod, and uses an outdated signature for applyToElement.
card-mod.js:1 The outdated signature will be removed at some point in the future. Hopefully the developer of your card will have updated their card by then.
card-mod.js:1 The card used card-mod to apply styles here: 
<hui-toggle-entity-row class=​"undefined">​</hui-toggle-entity-row>​
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
