### ISSUE TITLE
Using mod-card breaks lovelace auto arranging into columns

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [thomasloven/lovelace-card-mod#38]
My Home Assistant version: 0.106.0.dev20200210

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Trying to use `mod-card` to get a background color.

What I expected to happen:
I expect my cards to be split into three columns on my desktop.

What happened instead:
If I use a `mod-card` as a wrapper to anything the lovelace just stacks everything into one column.

**Minimal** steps to reproduce:
Create few cards with and without using `mod-card`:

```
views:

  - title: test1
    id: test1
    cards:
      - type: entities
        title: Entities card sample
        show_header_toggle: true
        header:
          image: 'https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png'
          type: picture
        entities:
          - sensor.date
          - sensor.date
          - sensor.date
          - sensor.date
          - sensor.date
      - type: entities
        title: Entities card sample
        show_header_toggle: true
        header:
          image: 'https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png'
          type: picture
        entities:
          - sensor.date
          - sensor.date
          - sensor.date
          - sensor.date
          - sensor.date
      - type: entities
        title: Entities card sample
        show_header_toggle: true
        header:
          image: 'https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png'
          type: picture
        entities:
          - sensor.date
          - sensor.date
          - sensor.date
          - sensor.date
          - sensor.date

  - title: test2
    id: test2
    cards:
      - type: custom:mod-card
        card:
          type: vertical-stack
          cards:
            - type: entities
              title: Entities card sample
              show_header_toggle: true
              header:
                image: 'https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png'
                type: picture
              entities:
                - sensor.date
                - sensor.date
                - sensor.date
                - sensor.date
                - sensor.date
      - type: custom:mod-card
        card:
          type: vertical-stack
          cards:
            - type: entities
              title: Entities card sample
              show_header_toggle: true
              header:
                image: 'https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png'
                type: picture
              entities:
                - sensor.date
                - sensor.date
                - sensor.date
                - sensor.date
                - sensor.date
      - type: custom:mod-card
        card:
          type: vertical-stack
          cards:
            - type: entities
              title: Entities card sample
              show_header_toggle: true
              header:
                image: 'https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png'
                type: picture
              entities:
                - sensor.date
                - sensor.date
                - sensor.date
                - sensor.date
                - sensor.date
```

![1](https://user-images.githubusercontent.com/12136404/75616700-e1174300-5b54-11ea-945c-7f4f9db89cff.PNG)
![2](https://user-images.githubusercontent.com/12136404/75616702-e1afd980-5b54-11ea-8b2d-5147109b5027.PNG)

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
