### ISSUE TITLE
2024.8 style badge styling doesn't work

### ISSUE THREAD

**Issue by mikosoft83** [thomasloven/lovelace-card-mod#391]
My Home Assistant version: 2024.8

My lovelace configuration method (GUI or yaml): GUI

What I am doing: using card mod in theme to style badges

What I expected to happen: style badges :D

What happened instead: nothing

**Minimal** steps to reproduce: try anything in card-mod-badge-yaml:

```yaml
  card-mod-badge-yaml: |
    .badge: {
        padding: 2px 8px !important;
        border-radius: 0px !important;
    }
```
Doesn't get attached to badge shadow root at all

I also tried:

```yaml
  card-mod-view-yaml: |
    "hui-masonry-view $": 
        "hui-view-badges $": 
          "hui-entity-badge $": |
            .badge: {
              padding: 2px 8px !important;
              border-radius: 0px !important;
            }
```
This gets attached but does nothing. It works for other elements within hui-view-badges.

Error messages from the browser console:
```
VM13847:1  Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at s.<anonymous> (card-mod.js:1:48199)
    at d (card-mod.js:1:2813)
    at Generator.<anonymous> (card-mod.js:1:4159)
    at Generator.next (card-mod.js:1:3242)
    at y (card-mod.js:1:8728)
    at a (card-mod.js:1:8931)
    at card-mod.js:1:8990
    at new Promise (<anonymous>)
    at s.<anonymous> (card-mod.js:1:8871)
```
Not sure if the error is relevant but I included it anyways.

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
