### ISSUE TITLE
2024.8: card_mod does not work for new mushroom-template-badge

### ISSUE THREAD

**Issue by felixmueller** [thomasloven/lovelace-card-mod#393]
My Home Assistant version: 2024.8.0

My lovelace configuration method (GUI or yaml): GUI

What I am doing: trying to style new mushroom-template-badge

What I expected to happen: card_mod works

What happened instead: card_mod not supported

**Minimal** steps to reproduce:
Add mushroom-template-badge to badges area, try to add card_mod in code editor

```yaml
# The least amount of code possible to reproduce my error
type: custom:mushroom-template-badge
content: Hello
icon: mdi:mushroom
color: red
card_mod:
  style: |
    ha-card {
      margin: 10px;
    }
# End of code
```

Error messages from the browser console:
At path: card_mod -- Expected a value of type `never`, but received: `[object Object]`

<img width="823" alt="mushroom-template-badge-card_mod" src="https://github.com/user-attachments/assets/fb0c0fda-a5da-479e-aa45-4c31bcd16d1f">

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
