### ISSUE TITLE
Cards render without corner radius and outline under certain conditions

### ISSUE THREAD

**Issue by stleusc** [thomasloven/lovelace-card-mod#395]
My Home Assistant version: 2024.8.1

My lovelace configuration method (GUI or yaml): GUI

What I am doing: simply updated HA to 2024.8.1

What I expected to happen: no visual changes

What happened instead: cards lost corner radius and outline

**Minimal** steps to reproduce:

```yaml
type: custom:mod-card
card_mod:
  style: |
    ha-card {
      padding: 8px;
      border: 0px;
    }
card:
  type: grid
  columns: 1
  square: false
  cards:
    - type: entities
      entities:
        - entity: scene.good_night
    - square: false
      type: grid
      columns: 4
      cards:
        - type: custom:slider-button-card
          entity: light.kitchen_light
          name: Kitchen
  ```

View must be set to Panel (1 card).

When removing
```yaml
type: custom:mod-card
card_mod:
  style: |
    ha-card {
      padding: 8px;
      border: 0px;
    }
card:
```

from the config then the cards all render correctly again!

This seems to be related to View type as well since changing it to Masonry makes it render correctly again!

This is a new issue. Running on older HA version before today's update worked fine. 

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
