### ISSUE TITLE
Card-Mod does not work in Chrome or Webkit but does in Firefox

### ISSUE THREAD

**Issue by mhentschke** [thomasloven/lovelace-card-mod#397]
My Home Assistant version: 2024.7.3

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Using any mods in Firefox and in Chrome/Webkit

What I expected to happen: Mods to apply

What happened instead: Firefox works flawlessly. Chrome and Webkit do not work at all even after cleaning the cache in multiple different devices (Windows, Mac, Android Tablet and Android Phone

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

type: custom:mushroom-entity-card
entity: person.myperson
card_mod:
  style: |
    ha-state-icon {
      color: orange;
    }

# End of code
```

Error messages from the browser console:

No relevant error message in either browser. Browser consoles look the same when it works and when it does not
---

Other maybe relevant info:

- Installed using HACS
- Version 3.4.3

What I tried:

- Clearing Cache
- Switching devices
- Changing Webkit to Beta and Canary 128.0.6613 and 129.0.6666
- Added a random number after the card-mod.js file: /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524343 -> /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524343000 to force re-download
- Added javascript_version: latest to my frontend config

No changes were seen in any of these trials

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
