### ISSUE TITLE
unwanted `class="undefined"` added => layout changed (without any styles applied)

### ISSUE THREAD

**Issue by SVNKoch** [thomasloven/lovelace-card-mod#404]
My Home Assistant version: core-2024.9.2

My lovelace configuration method (GUI or yaml):
GUI
What I am doing:
Recoloring buttons, but it happens even without applying any style and just using card-mod
What I expected to happen:
nothing
What happened instead:
layout changes due to added `class="undefined"`
**Minimal** steps to reproduce:
before:
```yaml
type: entities
entities:
  - entity: script.my_script
    name: Script
    icon: mdi:script-text
  - entity: lock.my_lock
    name: Lock
  - entity: button.my_button
    name: Button
    icon: mdi:button-pointer
```
=>
_(on images buttons highlighted by holding clicking on them, photoedited composed multiple to highlight all buttons)_
![good](https://github.com/user-attachments/assets/bbe6c943-4905-46a0-903e-e583f37b5861)

afterwards:
```yaml
type: entities
entities:
  - entity: script.my_script
    name: Script
    icon: mdi:script-text
    card_mod:
      style:
        hui-generic-entity-row:
  - entity: lock.my_lock
    name: Lock
    card_mod:
      style:
        hui-generic-entity-row:
  - entity: button.my_button
    name: Button
    icon: mdi:button-pointer
    card_mod:
      style:
        hui-generic-entity-row:
```
=>
![wrong](https://github.com/user-attachments/assets/ed1ed103-2602-43d7-ab29-814438499ed0)

As we can see now the buttons are not right aligned anymore in the row. The RUN and PRESS button have moved left by roughly 1 space (` `) to the left I would say.

I verified that the only thing that changed in the html code is the mentioned undefined class.
![grafik](https://github.com/user-attachments/assets/a3d5c403-4676-4c56-adeb-1ffe2f4efe4e)

<details><summary>html code for comparing before formatting received via:</summary>

```javascript
function extractHTML(node) {
    if (!node) return '';
    if (node.nodeType === 3) return node.textContent.trim();
    if (node.nodeType !== 1) return '';

    let html = '';
    let outer = node.cloneNode();
    if (node.shadowRoot) {
        html += '<!--#shadow-root (open)-->'; // Add a comment for open shadow root
        node = node.shadowRoot;
    } else {
        node = node;
    }

    if (node.children.length || node.childNodes.length) {
        for (let n of node.childNodes) {
            if (n.nodeName === 'SLOT') {
                let assignedNodes = n.assignedNodes();
                if (assignedNodes.length > 0) {
                    for (let assignedNode of assignedNodes) {
                        html += extractHTML(assignedNode);
                    }
                } else {
                    html += n.outerHTML;
                }
            } else {
                html += extractHTML(n);
            }
        }
    } else {
        html = node.innerHTML;
    }
    outer.innerHTML = html;
    return outer.outerHTML;
}
```

</details>

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Do you know that
```
    card_mod:
      style:
        hui-generic-entity-row:
```
is a wrong code which may cause unexpected results ?)

**Comment by SVNKoch** [comment]
@ildar170975 are you referring to the fact that there are no styles specified beneath?
**If yes**: the problem persists when providing some, I just reduced the code to the minimal problematic code. 

<details><summary>example style</summary>
```yaml
type: entities
entities:
  - entity: script.my_script
    name: Script
    icon: mdi:script-text
    card_mod:
      style:
        hui-generic-entity-row:
          mwc-button $: |
            .mdc-button {
              padding-right: 16px !important;
              color: green !important;
              --mdc-ripple-color: green !important;
            }
```
</details> 
<br>

**if no**: how should above snippet look like instead? I have oriented myself at eg. [this posting](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1349)
