### ISSUE TITLE
Not updating colors in Entity Badge

### ISSUE THREAD

**Issue by EinSchwerd** [thomasloven/lovelace-card-mod#406]
My Home Assistant version: 2024.9.3

My lovelace configuration method (GUI or yaml):
GUI (with YAML where GUI not supported)

What I am doing:
Using card mod to change the color of the entity badge based on the displayed sensor state

What I expected to happen:
Based on the state of a sensor, the color of the text should change

What happened instead:
No color change

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
type: entity
show_name: true
show_state: true
show_icon: true
entity: sensor.uv_level
style: |
  :host {
    {% if states(sensor.uv_level) == "Low" %}
      color: green;
    {% elif states(sensor.uv_level) == "Medium" %}
      color: yellow;
    {% elif states(sensor.uv_level) == "High" %}
      color: orange; 
    {% elif states(sensor.uv_level) == "Very High" %}
      color: red;
    {% elif states(sensor.uv_level) == "Extreme" %}
      color: purple;
    {% else %}
      color: grey;
    {% endif %};
  }
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [] Have made sure I am using the latest version of the plugin.

- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
