### ISSUE TITLE
Cannot get changes to consistently display on Dashboard. Keeps defaulting to stock/current theme.

### ISSUE THREAD

**Issue by Sonny-Crockett** [thomasloven/lovelace-card-mod#416]
My Home Assistant version: 2024.11.3

My lovelace configuration method (GUI or yaml): GUI, from HACS, with frontend js reference added to config.yaml

What I am doing: Shifting icon color based on input.select helper.

What I expected to happen: This to work every time.

What happened instead: Only sometimes does it work, either in Edge, Chrome, FullyKioskBrowser. Refresh does not help. 

**Minimal** steps to reproduce: Several times throughout the day, the default icons/colors will load, instead of my changes. Whether using default theme or custom themes. Cannot ever forcibly recreate it. If it is not working, going into edit mode seems to fix it. 

```yaml
show_name: true
show_icon: true
type: button
card_mod:
  style: |
    ha-card {
      {% if is_state(config.entity, 'Out of the Office') %}
      --card-mod-icon: mdi:car-side;
      --card-mod-icon-color: blue;
      {% elif is_state(config.entity, 'Available') %}
      --card-mod-icon: mdi:account-check;
      --card-mod-icon-color: green;
      {% elif is_state(config.entity, 'Busy') %}
      --card-mod-icon: mdi:account-cancel;
      --card-mod-icon-color: red;
      {% elif is_state(config.entity, 'Phone Call') %}
      --card-mod-icon: mdi:phone-cancel;
      --card-mod-icon-color: yellow;
      {% endif %}
    }
tap_action:
  action: perform-action
  perform_action: input_select.select_next
  target:
    entity_id: input_select.person1_status
  data:
    cycle: true
entity: input_select.person1_status
show_state: true
hold_action:
  action: none
grid_options:
  columns: full
  rows: 3

```

---
