### ISSUE TITLE
"Color" Variable not working at all

### ISSUE THREAD

**Issue by b7-afonso** [thomasloven/lovelace-card-mod#417]
My Home Assistant version:

- Core: 2024.11.3
- Supervisor: 2024.11.4
- Operating System: 13.2
- Frontend: 20241106.2

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Trying to add some custom styling to the default tile card. Specifically, the card is transparent when off, and white when on. All styles work except for changing the font color

What I expected to happen:
I am expecting that when I add a color tag to the relevant classes that it will respond by showing the styling

What happened instead: 
All styles worked except changing the color of the text

**Minimal** steps to reproduce:
Add a tile card through GUI
Add custom code with color tags

```yaml
# The least amount of code possible to reproduce my error
type: tile
entity: fan.fan_br2_2
tap_action:
  action: toggle
hold_action:
  action: more-info
card_mod:
  style: |
    ha-card {
      background: transparent;
      transition: background 0.3s ease-in-out;
      color: red
    }

    ha-card.active {
      background: rgba(255, 255, 255, 0.3);
      color: red;
    }

    ha-card .primary {
      color: red;
    }

# End of code
```

Error messages from the browser console:
No errors in console
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
