### ISSUE TITLE
Custom element doesn't exist: hui-picture-elements-card

### ISSUE THREAD

**Issue by tlpbu** [thomasloven/lovelace-card-mod#42]
My Home Assistant version: 0.107.5

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
To load modded picture-elements card in dashboard

What I expected to happen:
Card loaded without help of `lovelace-card-preloader` custom plugin

What happened instead:
Card is not loaded, instead in Dashboard red message appears with title "Custom element doesn't exist: hui-picture-elements-card."

If `lovelace-card-preloader` custom plugin is installed and configure in lovelace yaml file a la
```yaml
preload:
  - picture-elements
```
then card is loaded.
**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

      - type: custom:mod-card
        style: |
          ha-card {
            --paper-card-background-color: #155c9d;
            --primary-text-color: white;
            font-size: 1.3rem;
            font-style: bold
          }
        card:
          type: picture-elements
          image: /local/images/transparent_background.png
          elements:
            - type: image
              entity: vacuum.servantess
              camera_image: camera.servantess_map
              style:
                top: 50%
                left: 50%
                width: 100%
            ...

# End of code
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
