### ISSUE TITLE
Style does not get applied correctly on Mobile for some cards.

### ISSUE THREAD

**Issue by Mqxx** [thomasloven/lovelace-card-mod#421]
My Home Assistant version (on Desktop): `2024.12.0` (Core), `20241127.4` (Frontend)
My Home Assistant version (on Mobile): `2024.12.7` (Companion App)

### My lovelace configuration method (GUI or yaml):
Script successfully loaded via GUI.

### What I am doing:
Displaying a custom styled card.

### What I expected to happen:
That it looks the same on Mobile and Desktop.

#### How it looks on Desktop:
![desktop](https://github.com/user-attachments/assets/dbddd3ce-6f19-4ce5-8481-5aa70d3d279b)

### What happened instead:
Style does not get applied for that card on Mobile.

#### How it looks on Mobile:
![tablet](https://github.com/user-attachments/assets/7eee5785-0f76-4126-8721-29a98b4f1f9b)

> The card should be extended to fill to the blue striped lines.

### **Minimal** steps to reproduce:
```yaml
# The least amount of code possible to reproduce my error
card_mod:
  style:
    .: |
      :host {
        height: 100% !important;

        ha-card {
          height: 100% !important;
          
          .mmp-player {
            display: flex !important;
            height: 100% !important;
            flex-direction: column !important;
            justify-content: space-between !important;
          }
        }
      }
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
