### ISSUE TITLE
Sensor card no longer allows styling in 2025.1.0 / 3.5.0

### ISSUE THREAD

**Issue by richhollis** [thomasloven/lovelace-card-mod#425]
My Home Assistant version: 2025.1.0

My lovelace configuration method (GUI or yaml): GUI Dashboard

What I am doing:
I have a sensor card that I use card-mod to simply set the value colour and min-height, but this now isn't working since 3.5.0. It is using the ha-card selector.

What I expected to happen:
The sensor to apply the styles and change the colours as previously

What happened instead:
No styles are applied, sensor value text remains the standard text colour in the dashboard

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
type: sensor
entity: sensor.octopus_energy_electricity_xxx_current_demand
graph: none
detail: 1
name: Electricity Demand
state_precision: 0
card_mod:
  style: |
    ha-card {
      min-height: 131px;
    }
    ha-card .value { 
      line-height: 60px;
      font-size: 60px;
    }
    ha-card {          
      color: 
        {% if states('sensor.octopus_energy_electricity_xxx_current_demand') | int < 530 %}
          green;
        {% elif states('sensor.octopus_energy_electricity_xxx_current_demand') | int > 2000 %}
          red;
        {% else %}
          orange;
        {% endif %};
    }
# End of code
```

Error messages from the browser console:

None - No errors visible in the console 

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

Thanks for your time.
