### ISSUE TITLE
ha-card styles not applied to mushroom chips in 3.5.0

### ISSUE THREAD

**Issue by Pivens** [thomasloven/lovelace-card-mod#426]
When changing to card-mod 3.5.0, the ha-card styles seem not correctly applied to any mushroom chip, when these are applied to individual chips inside the mushroom chips card.
Specifically, applying e.g. --chip-backround works when used globally for the chips card like this:
```yaml
_type: custom:mushroom-chips-card
card_mod:
  style: |
    ha-card {
      --chip-background: blue;
    }_
```

However, when used for individual chips, the card-mod styles are NOT working:
```yaml
type: custom:mushroom-chips-card
chips:
  - type: conditional
    conditions:
      - entity: light.office_desk_lamp
        state: 'on'
    chip:
      type: template
      entity: light.office_desk_lamp
      icon: mdi:lightbulb
      card_mod:
        style: |
          ha-card {
            --chip-background: blue;
          }
```
