### ISSUE TITLE
My entities no longer show the color for just the value and the respective unit of measurement

### ISSUE THREAD

**Issue by WRoss7** [thomasloven/lovelace-card-mod#428]
My Home Assistant version: 2025.1

My lovelace configuration method (GUI or yaml): mix of the two

What I am doing:
I can no longer color just the values and respective units of entities.

What I expected to happen:
color only the values and respective units of the entities.

What happened instead:
already since before 2025.1 (perhaps since 2024.11?) I can no longer color just the values and respective units of entities.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
type: entities
show_header_toggle: false
state_color: false
entities:
  - entity: binary_sensor.rpi_power_status
    name: Alimentazione
  - entity: sensor.processor_use
    name: CPU
    card_mod:
      style: >-
        {% if states('sensor.processor_use') | float(0) > 10 %}
          div {
            color: gold;
            font-weight: bold;
          }
        {% endif %}
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
