### ISSUE TITLE
lost modification on Tile with 3.5.0

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#429]
My Home Assistant version: 2025.1.0

My lovelace configuration method (GUI or yaml):
Yaml
What I am doing:

modding a Tile card, and purposely post a somewhat more fleshed out config to touch most of the elements

What I expected to happen:
successful modification ;-)
What happened instead:
the modification is not applied at all, probably because of targeting the wrong elements.
so, we need to find the correct syntax/elements

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  type: tile
  show_entity_picture: true
  state_content:
    - state
    - last-changed
  entity: person.[[id]]
  card_mod:
    style:
# Make this work in Safari too ;-)
      ha-tile-image $: |
        .image {
          {% set zones = states.zone|map(attribute='name')|list %}
          filter: {{'grayscale(1)' if is_state(config.entity,'not_home') else 'none'}};
        }

      .: |
        {% set id = '[[id]]' %}
        {% set zones = states.zone|map(attribute='name')|list %}
        ha-card {
          border: solid {{states('sensor.'~id~'_background_color')}} 2px;
          background: var(--background-color);
          background-image: url("{{states('sensor.'~id~'_overlay_image')}}");
          background-size: 35px;
          background-position: 95% 50%;
          background-repeat: no-repeat;
        }
        .icon-container {
          border-radius: 24px;
          border: solid {{states('sensor.'~id~'_background_color')}} 3px;
        }

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
