### ISSUE TITLE
box-shadow and margin no longer set in 3.5.0

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#430]
My Home Assistant version: 2025.1

My lovelace configuration method (GUI or yaml): Yaml

What I am doing:
setting box-shadow and margins on several cards (see yaml) in stacks and entities cards, so they appear as 1 big card

What I expected to happen:

have the mod applied
What happened instead:

they are no longer applied

<img width="540" alt="Scherm­afbeelding 2025-01-06 om 23 21 55" src="https://github.com/user-attachments/assets/c09f2712-c0e7-4aeb-8dad-0a043f0aecbb" />

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
      - type: custom:hui-element
        card_type: markdown
        card_mod:
          style: |
            ha-card.type-markdown {
              box-shadow: none;
              margin: -16px;
              pointer-events: none;
            }

      - type: custom:auto-entities
        card:
          type: entities
          card_mod:
            style: |
              ha-card {
                box-shadow: none;
                margin: -8px;
              }
# End of code
```

given the fact several other mods on the same cards ha-card element still work, like 
```
  - type: entities
    card_mod:
      style: |
        ha-card {
          border-top: var(--primary-color) 2px solid;
        }
```
I was hoping for some assistance and pointers in the right direction.
If this should still work, please consider a true issue....

thanks for any help.

Error messages from the browser console:
no errors
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
3.5.0 has been removed for now
Please upgrade to 3.4.4

**Comment by Mariusthvdb** [comment]
fwiw
Ive been continuing to use the 3.5.0 resource against better knowledge, and got everything working, including all of the new features and niceties you started out with. Very nice indeed, and no more mod-card at all.

Two caveats:

**Auto-entities**. the card_mods set on the card inside auto-enties are no longer respected. Be it class like

```
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Beweging!
          state_color: true
          card_mod:
            class: class-header-margin
        filter:
          include:
            - entity_id: binary_sensor.*_sensor_motion
              state: 'on'

```

or direct modifications like:

```
    entities:
      - type: custom:auto-entities
        card:
          type: entities
          card_mod:
            style: |
              ha-card {
                box-shadow: none;
                margin: 16px;
              }
        filter:
          include:
            - entity_id: sensor.*_sensitivity
```

as in the opening post a mod with a type specification
```
      - type: custom:hui-element
        card_type: markdown
        card_mod:
          style: |
            ha-card.type-markdown {
              box-shadow: none;
              margin: -16px;
              pointer-events: none;
            }
```

or  to the core card
```
      - type: markdown
        card_mod:
          style: |
            ha-card.type-markdown {
              box-shadow: none;
              margin: -16px;
              pointer-events: none;
            }
```
no longer works. have to leave the `type-markdown` out for I to work again, which in itself is fine. However, we used the type for a reason, to restrict the mods to that particular card, and not make it work on the containing card.

that behavior now is back...

If you are still developing this resource in the background, I would hope you could see to these 2 effects
