### ISSUE TITLE
Card_mod styling disappearing after ugrade to 3.4.4

### ISSUE THREAD

**Issue by storebatfar** [thomasloven/lovelace-card-mod#431]
My Home Assistant version: 2025.1.0

My lovelace configuration method (GUI or yaml):
Both

Looking at my dashboards all looks fine. When I edit a card that has card_mod styling and look at the yaml code, the card_mod styling has disappearing / is deleted from the code.

Downgraded to 3.4.3, but the problem is still there. All was working before the upgrade to 3.4.4.

Solution is to delete card_mod completely and then re-install version 3.4.3.

**Comment by evanwyatt** [comment]
From what I can tell this is only effecting non-chormium browsers (in my case safari & firefox) - Added color: red to make it really obvious.

**Chrome:**
<img width="813" alt="image" src="https://github.com/user-attachments/assets/c62fe829-01d2-4256-a31b-cc8cdad0ffec" />

**Firefox:**
<img width="813" alt="image" src="https://github.com/user-attachments/assets/697a6c3a-7e50-42ee-ac13-2698655e3b3d" />

Relevant config:
`
- type: custom:digital-clock
  firstLineFormat: HH:mm
  secondLineFormat: |
    EEEE,
    dd LLL
  card_mod:
    style: |
      ha-card {
        font-size: 65px;
        color: red;
        border-width: 0px !important;
        background: none;
        text-shadow: 1px 1px 2px #101010;
      }
`

**Comment by Mariusthvdb** [comment]
well, without any yaml, no-one is going to be able to help you out

**Comment by storebatfar** [comment]
> well, without any yaml, no-one is going to be able to help you out

I'm not really looking for help, as I can just keep running version 3.4.3.
However, I think it's important to share when something is not working.

As an example the following card_mod yaml disappears when I edit my dashboard.

`card_mod:
  style: |
    ha-card {
      --title-font-size: 50px;
    }`

The happens for all card_mod sections for my entire dashboard.

**Comment by scoutcow** [comment]
I had the same. Both when opening in Chrome, but also in the Android app. (I cleared cache, deleted site data).
While still in version 3.4.4 (whith styling disappeared) I installed it as a frontend module by adding it to my configuration.yaml:

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    
    That also didn't change anything, so I rolled back to 3.4.3, which fixed the problem.
    After that I upgraded to 3.4.4 again and it al kept working somehow, so now all is working fine for me in version 3.4.4

**Comment by Kourai** [comment]
Hello ! I have the same problem !

Yesterday : using 3.4.3 , my dashboard were fine, I upgraded to 3.4.4, and lost all my color customization made with card_mod. (tested on Firefox)

However, a simple rollback to 3.4.3 was enough for me to solve the problem!

**Comment by dMopp** [comment]
Downgraded to 3.4.3 and Button Colors are back, too.

**Comment by dMopp** [comment]
```
      - type: custom:mushroom-chips-card
        chips:
          - type: template
            content: Erdgeschoss
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen
            card_mod:
              style: |
                ha-card {
                  --chip-background:grey;
                }
            icon: ""
          - type: template
            content: Obergeschoss
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen/Obergeschoss
            icon: ""
          - type: template
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen/gerateverbrauch-und-kosten
            content: Geräte
          - type: template
            content: PV-Anlage
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen/pv-anlage
          - type: template
            content: Heizung
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen/heizung
          - type: template
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen/staubsauger
            content: Staubsauger
          - type: template
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen/garten
            content: Garten
          - type: template
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen/wallbox-v2
            content: Wallbox
```

This is just one snipp from my yaml which will not work (in app or firefox) with 3.4.4

**Comment by dustinschroder** [comment]
I have the same issue. reverted and all is good now.

```
type: custom:button-card
show_state: true
custom_fields:
  tesla_image1:
    card:
      type: picture
      image: local/512x512.png
      card_mod:
        style: |
          ha-card {
            background-color: transparent;
            border: none;
          } 
      tap_action:
        action: call-service
        service: input_number.set_value
        target:
          entity_id: input_number.tesla_card_height
        data:
          value: 500
  tesla_image2:
    card:
      type: picture
      image: /local/teslaTopDown.png
      card_mod:
        style: |
          ha-card {
            background-color: transparent;
            border: none;
          }  
      tap_action:
        action: call-service
        service: input_number.set_value
        target:
          entity_id: input_number.tesla_card_height
        data:
          value: 260
  tesla_battery_image:
    card:
      type: picture
      image: local/battery2.gif
      card_mod:
        style: |
          ha-card {
            background-color: transparent;
            border: none;
          }              
  tesla_charge_limit:
    card:
      type: custom:mushroom-template-card
      primary: "Charge Limit: {{states('sensor.tesla_charge_limit_soc')}}"
      secondary: ""
      multiline_secondary: false
      fill_container: false
      card_mod:
        style:
          mushroom-state-info$: |
            .primary {
              font-size: 12px !important;
              position: relative;
              overflow: visible !important;
              text-align:left;
            }
            .secondary {
              font-size: 12px !important;      
              position: relative;
              overflow: visible !important;
              text-align:left;
            }
          .: |
            ha-card {
              background-color: transparent;
              border: none;
            }
styles:
  card:
    - align-self: start
    - width: 470px
    - height: |
        [[[ return states['input_number.tesla_card_height'].state + 'px'; ]]]
    - opacity: 1
    - background-color: black
    - border: none
  custom_fields:
    tesla_image1:
      - position: absolute
      - top: "-40px"
      - left: "-20px"
      - width: 500px
    tesla_battery_image:
      - position: absolute
      - top: 2px
      - left: 355px
      - width: 65px
    tesla_charge_limit:
      - position: absolute
      - top: 160px
      - left: 10px
      - width: 150px
    tesla_image2:
      - position: absolute
      - top: 275px
      - left: 300px
      - width: 150px
  name:
    - justify-self: start
    - align-self: start
    - font-size: 24px
    - font-weight: 500
    - color: white
  state:
    - min-height: 80px
    - justify-self: start
    - align-self: start
    - font-size: 18px
    - opacity: "0.7"
```


<img width="540" alt="Screenshot 2025-01-07 at 08 05 21" src="https://github.com/user-attachments/assets/9f5d6cf4-c2d4-4c42-b083-a3007ae8ce6e" />
<img width="540" alt="Screenshot 2025-01-06 at 21 08 57" src="https://github.com/user-attachments/assets/8eb53ed8-7ac4-44e6-9ec3-f31beb0b3171" />

**Comment by Mariusthvdb** [comment]
> Ive shortened the code for the example.

well shortened.....


please provide a single failing section, as it looks it the combination with mushroom? specifically mushroom, or, only as embedded card inside the button.

if you want help. please make it easier for us to do so. maybe even open a dedicated issue for these specifics alone, so others can find it based on the correct title in detail

**Comment by storebatfar** [comment]
Here is a very simple example of code from my dash, where the card-mod section disappears when I edit the code.

`type: custom:mushroom-title-card
title: >
  {{ (states('sensor.strom_energi_data_service_daglig_gennemsnitspris') | float
  | round(2)) | string | replace('.', ',') }}
subtitle: ""
alignment: center
card_mod:
  style: |
    ha-card {
      --title-font-size: 50px;
    }
`

**Comment by Mariusthvdb** [comment]
and with disappear, you mean the yaml in the UI editor? (please screenshot that)

or the effect it should have I the Frontend

**Comment by nephrotranz** [comment]
I only had a small problem - all border around my stacked in mushroom-cips-card were back after the update.
I also rolled back to 3.4.3 - everything fine again.

**Comment by RogerSelwyn** [comment]
3.4.3 seems to work fine, 3.4.4 on 2025.1.1 does not apply styling to my cards. I'll try to see if there are console errors when I can run it on a proper browser tomorrow.

**Comment by Mariusthvdb** [comment]
> This is just one snipp from my yaml which will not work (in app or firefox) with 3.4.4

please define 'will not work' ?

also, there is but 1 tiny card_mod in that config, so if that is the bit not working, just leave out the rest of the yaml, it makes helping you much easier for us

**Comment by dMopp** [comment]
> > This is just one snipp from my yaml which will not work (in app or firefox) with 3.4.4
> 
> @dMopp please define 'will not work' ?
> 
> also, there is but 1 tiny card_mod in that config, so if that is the bit not working, just leave out the rest of the yaml, it makes helping you much easier for us

Sorry, copied way to much:

‘’’
chips:
          - type: template
            content: Erdgeschoss
            tap_action:
              action: navigate
              navigation_path: /dashboard-homescreen
            card_mod:
              style: |
                ha-card {
                  --chip-background:grey;
                }
            icon: ""
‘’’

it’s not changing the background of that specific chip with 3.4.4

**Comment by Mariusthvdb** [comment]
yes, I see that too in 3.5.0, but are you sure this config worked before?
given the changes in card-mod 3.4.4 it could hardly be caused by that, so might be an issue with mushroom in HA 2025.1. Or the config of course ;-)
check the mushroom repo for issues and the community three https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily-part-2/693055/1364

**Comment by sysmoon14** [comment]
I'll add my issue here too. Basically the below is not working when I upgrade to 3.4.4
```type: custom:button-card
name: Living Room
icon: mdi:sofa
tap_action:
  action: navigate
  navigation_path: "#living-room"
entity: sensor.living_room_temperature
show_state: true
custom_fields:
  btn:
    card:
      type: custom:mushroom-chips-card
      chips:
        - type: template
          entity: light.living_room_lights
          icon: mdi:lightbulb-group
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          double_tap_action:
            action: none
          content_info: none
          card_mod:
            style: |
              ha-card {
                --chip-background: {{ 'rgb(233, 196, 106, 0.8)' if is_state('light.living_room_lights', 'on') else 'rgba(170, 170, 170, 0.3)'}};
                padding: 5px!important;
                border-radius: 100px!important;
              }
        - type: template
          entity: climate.living_room
          icon: mdi:thermometer
          tap_action:
            action: more-info
          hold_action:
            action: more-info
          double_tap_action:
            action: none
          content_info: none
          card_mod:
            style: |
              ha-card {
                --chip-background: {{ 'rgb(232, 92, 13, 0.8)' if is_state_attr('climate.living_room', 'hvac_action', 'heating') else 'rgba(170, 170, 170, 0.3)'}};
                padding: 5px!important;
                border-radius: 100px!important;
              }
styles:
  grid:
    - grid-template-areas: "\"n btn\" \"s btn\" \"l btn\""
    - grid-template-columns: 1fr min-content
    - grid-template-rows: min-content min-content 1fr;
  img_cell:
    - justify-content: start
    - position: absolute
    - width: 100px
    - height: 100px
    - left: 0
    - bottom: 0
    - margin: 0 0 -20px -20px
    - background: rgb(37, 113, 128)
    - border-radius: 200px
  icon:
    - width: 60px
    - color: white
    - opacity: "0.7"
  card:
    - padding: 22px 8px 22px 22px
  custom_fields:
    btn:
      - justify-content: end
      - align-self: start
  name:
    - justify-self: start
    - align-self: start
    - font-size: 14px
    - font-weight: 500
    - color: white
  state:
    - min-height: 80px
    - justify-self: start
    - align-self: start
    - font-size: 14px
    - opacity: "0.7"
              }```

The above YAML looks like this with card-mod 3.4.3
![Screenshot 2025-01-08 at 08 57 59](https://github.com/user-attachments/assets/c166ddf7-86c4-40f2-a0be-8bce5cb4e38a)

and looks like this when I upgrade to 3.4.4
![Screenshot 2025-01-08 at 08 59 05](https://github.com/user-attachments/assets/b774692b-c71f-444b-aced-c365bc039fd0)

**Comment by sysmoon14** [comment]
but why would it be a mushroom issue when the only thing changed between my two screenshots is the version of card-mod being used?

Screenshot 1 is HA 2025.1.1, Mushroom 4.2.1, card-mod 3.4.3

Screenshot 2 is HA 2025.1.1, Mushroom 4.2.1, card-mod 3.4.4

**Comment by RogerSelwyn** [comment]
> 3.4.3 seems to work fine, 3.4.4 on 2025.1.1 does not apply styling to my cards. I'll try to see if there are console errors when I can run it on a proper browser tomorrow.

Some reason it said I had 3.5.0 installed (I don’t see a release for that so I guess it was withdrawn).  Downgrading to 3.4.3 and back to 3.4.4 has it working fine.

**Comment by sambeetm** [comment]
3.4.4 screwed-up my margins. Staying in 3.4.3 for now.

**Comment by FortranFour** [comment]
3.4.4 has failed to apply styling for me with thermostat card, room-card, and android-tv-card, whereas 3.4.3 and before all worked fine. I did not notice problems with Mushroom cards.

**Comment by claire-peacock** [comment]
The following fails for me for custom:layout-card in 3.4.4, but works fine with 3.4.3.

```
card_mod:
      style: |
        .entities {
         margin-top: -25px !important;
         margin-bottom: -25px !important;
         }

        ha-card {
          --state-switch-on-color: #52b04a;
          --state-switch-off-color: #f04135;

         }
```

I have rolled back to 3.4.3 for now, unless there are any suggestions as to a fix for this.

**Comment by fgamache1** [comment]
Same. But I redownloaded with the 3.4.3. Reboot, And reinstalled 3.4.4. And now work fine.. Just saying.

**Comment by nephrotranz** [comment]
> Same. But I redownloaded with the 3.4.3. Reboot, And reinstalled 3.4.4. And now work fine.. Just saying.

Tried it twice yesterday as I already read somewhere that it could help, but didn't work for me unfortunately.

**Comment by claire-peacock** [comment]
That didn't work for either unfortunately, but welcome the suggestion. Thank you.

**Comment by storebatfar** [comment]
> Same. But I redownloaded with the 3.4.3. Reboot, And reinstalled 3.4.4. And now work fine.. Just saying.

Also no luck here following you steps.

**Comment by ildar170975** [comment]
The 1st post:
> Looking at my dashboards all looks fine. When I edit a card that has card_mod styling and look at the yaml code, the card_mod styling has disappearing / is deleted from the code.

And what is a difference from https://github.com/thomasloven/lovelace-card-mod/issues/337 ?

Starting from some post, almost all posts are not related to the issue and are just about "card-mod does not affect ..."

**Comment by storebatfar** [comment]
> The 1st post:
> 
> > Looking at my dashboards all looks fine. When I edit a card that has card_mod styling and look at the yaml code, the card_mod styling has disappearing / is deleted from the code.
> 
> And what is a difference from #337 ?
> 
> Starting from some post, almost all posts are not related to the issue and are just about "card-mod does not affect ..."

Yes, I am experiencing that the code is disappearing when using the UI editor. This is the issue reported.
Using v. 3.4.3 all is good. Upgrading to 3.4.4 causes the issue.

**Comment by ildar170975** [comment]
> Yes, I am experiencing that the code is disappearing when using the UI editor. This is the issue reported.
Using v. 3.4.3 all is good. Upgrading to 3.4.4 causes the issue.

There is only ONE difference between 3.4.3 & 3.4.4 - and it cannot cause this behaviour.
Here is a screenshot from untouched 3.4.3:
![image](https://github.com/user-attachments/assets/8dce56b7-7054-4fa3-add2-ad804937fd22)
```
      - type: tile
        entity: sun.sun
        card_mod:
          style: |
            ha-card { background: red; }
```
That is why I said that your issue is a duplicate of the present https://github.com/thomasloven/lovelace-card-mod/issues/337.
But if you want to have your own issue about the same glitch - no problem ))
