### ISSUE TITLE
card-mod not working anymore with custom:button-card

### ISSUE THREAD

**Issue by sparis** [thomasloven/lovelace-card-mod#434]
My Home Assistant version: 2025.1.1

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Using card-mod on a custom:button-card

What I expected to happen: The style to change

What happened instead: The style does not change. In the example below, the background is not green. But if the mushroom card inside the button card is on its own with the same code, the background is green. It used to work until recently.

**Minimal** steps to reproduce:

```yaml
type: custom:button-card
styles:
  grid:
    - grid-template-areas: " 'c' "
    - grid-template-columns: 100%
  card:
    - padding: 0
custom_fields:
  c:
    card:
      type: custom:mushroom-light-card
      entity: light.ceiling_light_office_1
      card_mod:
        style: |
          ha-card {
            background: green;
          } 
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
