### ISSUE TITLE
2 Lines in History

### ISSUE THREAD

**Issue by H4X0-R** [thomasloven/lovelace-card-mod#439]
My Home Assistant version: 2025.1.4

My lovelace configuration method (GUI or yaml): YAML

What I expected to happen:

One line for the history of my entity

What happened instead:

Since the update from mapcard 1.11 to 1.12 there are 2 lines when the history_start is set to an entity. If i manually set history_start the to state of my variable, it only shows 1 line as its supposed
Installing an old version (1.11) works with the same yaml and there are only 1 line again. Updating to the newest version brings back the second line.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

type: custom:map-card
entities:
  - entity: person.xxx
    use_base_entity_only: true
    history_start: sensor.date

# End of code
```

State of "sensor.date" is "2025-01-27"

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
