### ISSUE TITLE
Styles not working anymore

### ISSUE THREAD

**Issue by PierreScerri** [thomasloven/lovelace-card-mod#44]
My Home Assistant version: 0.108.2

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Added style to change icon colour of stock sensor card depending on the state of a sensor.
This was working until recently.  

What I expected to happen:
Continue to work as before.

What happened instead:
Stopped working probably after recent HA upgrade.

**Minimal** steps to reproduce:
Recent HA upgrade?

```yaml
# The least ammount of code possible to reproduce my error
        entity: sensor.sdm230import
        graph: none
        icon: 'mdi:import'
        name: Import
        state_color: true
        style: |
          :host {
            --paper-item-icon-color:
              {% if states.sensor.import_power.state|int > 0 %}
                red
              {% else %}
                rgb(138, 185, 45)
              {% endif %}
              ;
        type: sensor


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
