### ISSUE TITLE
card mod more info last changed value inconsistent from theme file

### ISSUE THREAD

**Issue by deepakkoirala** [thomasloven/lovelace-card-mod#441]
My Home Assistant version:2025.1.4

My lovelace configuration method (GUI or yaml):
No gui configuration because added from the theme

What I am doing:
I am trying to change the more info dialog box light, switches, lock, cover etc by hiding the last changed value from the theme file for that particular user for my Fully Kiosk Samsung Galaxy A7 Lite tab.

Here is the screenshot.
https://prnt.sc/SOxy5K5mE3Ks

What I expected to happen:
It should have hide before loading the modal box, and it shouldn't have shown the hiding affect once its loaded. But on faster PC and laptops, this is working fine.

What happened instead:
After modal box is opened, after few seconds the last changed time is getting hidden on my Fully Kiosk Samsung Galaxy A7 Lite tab. Once it hides for first entity of same type like switch, the second one I do not see the affect. I am also hiding things for that modal box using Kiosk Mode plugin as well, but I do not see this behavior.

**Minimal** steps to reproduce:
Click the device and look for the last changed value.

```yaml
# The least amount of code possible to reproduce my error

wallpanel-theme:
  # Define your theme colors
  # Card-Mod settings to customize specific cards
  card-mod-theme: wallpanel-theme
  
  ha-dialog:
    animation:none !important;
  ha-dialog::backdrop:
    animation:none !important;
  ha-card:
    animation:none !important;
  
  modes:
    dark:
      primary-color: "#0288D1"
      background-color: "#121212"
      text-color: "#FFFFFF"
      
  card-mod-more-info-yaml: |
    ha-more-info-info$:
      more-info-content$:
        more-info-light$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-switch$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-lock$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-cover$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
        more-info-alarm_control_panel$:
          ha-more-info-state-header$: |
            .last-changed {
              visibility: hidden !important;
            }
      state-card-content$:
        state-card-display$:
          state-info$: |
            .time-ago {
              visibility: hidden !important;
             }

# End of code
```

Error messages from the browser console:
I guess there is no error. Haven't checked.
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
