### ISSUE TITLE
Styling of secondary info (text color) not working anymore.

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [thomasloven/lovelace-card-mod#444]
My Home Assistant version: 2025.02.03

My lovelace configuration method (GUI or yaml): Yaml.

What I am doing:
I am trying to change the color of the secondary text by sensor. Different Colors for posiitv/negativ values. (state 'off' means red/pink, 'on' = green)

What I expected to happen:
Value below zero causes secondary text to be green, values above zero makes text red.

What happened instead:
Instead of the desired color, the default color is used. This used to work until HA 2025.01

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

      - type: custom:template-entity-row
        entity: sensor.indoor_temperature
        name: Temperatur
        state: >
          {{states(config.entity)}} {{state_attr(config.entity,
          'unit_of_measurement')}}
        secondary: "Outdoor-Gradient: {{states('sensor.wohnzimmerlft')}} °C"
        active: "{{ is_state('binary_sensor.wzluften', 'on') }}"
        card_mod:
          style: |
            {% if states('binary_sensor.wzluften') == 'off' %}
                 .info.pointer .secondary {
                   color: lightpink
                 }
            {% else %}
                 .info.pointer .secondary {
                   color: green
                 }
            {% endif %}

# End of code
```

Error messages from the browser console: None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
