### ISSUE TITLE
Card Mod does not work with custom template entity row card & after update to 2025.2.4

### ISSUE THREAD

**Issue by RobusX** [thomasloven/lovelace-card-mod#445]
My Home Assistant version: 2025.2.4

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Upgraded from 2024.12.5 to 2025.2.4

What I expected to happen: card mod modifications should work (color, icon changes, etc)

What happened instead: default colors, icon sizes remained

**Minimal** steps to reproduce:

```yaml

type: entities
entities:
  - type: custom:template-entity-row
    entity: binary_sensor.contact_sensor
    name: Main Door
    toggle: false
    secondary_info: last-updated
    card_mod:
      style: |
        :host {
          --mdc-icon-size: 40px;    
          --paper-item-icon-color: 
          {% if is_state('binary_sensor.contact_sensor', 'off') %}
            green;
          {% elif is_state('binary_sensor.contact_sensor', 'on') %}
            red;
          {% else %}
            grey;
          {% endif %};
        }
# The least amount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by RobusX** [comment]
I have read this link about paper icon color abandoned (why it stopped after yet atfer latest upgrade...no not know):

https://community.home-assistant.io/t/picture-elements-paper-item-icon-active-color-not-working-on-some-entities/458326

and this:

https://github.com/home-assistant/frontend/blob/f1393e5f00690287a78665faf88ca6145d4aaf48/src/resources/ha-style.ts#L136

So i tried with this but no success:

```yaml

type: entities
entities:
  - type: custom:template-entity-row
    entity: binary_sensor.contact_sensor
    name: Main Door
    toggle: false
    secondary_info: last-updated
    card_mod:
      style: |
        :host {
          --mdc-icon-size: 40px;    
          {% if is_state('binary_sensor.contact_sensor', 'off') %}
            --rgb-state-binary-sensor-color: 255,0,0;
          {% elif is_state('binary_sensor.contact_sensor', 'on') %}
            --rgb-state-binary-sensor-color: 0,255,0;
          {% else %}
            --rgb-state-binary-sensor-color: 128,128,128;
          {% endif %}
        }

**Comment by ildar170975** [comment]
![Image](https://github.com/user-attachments/assets/c3306e8c-e4b4-423d-9207-0acb47594142)

**Comment by RobusX** [comment]
@ildar170975

Thank you very much for your response...but I am still struggling.
I Tried this:
```yaml
type: entities
entities:
  - type: custom:template-entity-row
    entity: binary_sensor.contact_sensor
    name: Main Door
    toggle: false
    secondary_info: last-updated
    card_mod:
      style: |
        :host {
          --mdc-icon-size: 40px;
          --paper-item-icon-color: red;
        }
```
And no change ... also command for icon size should make change, but it is not.

![Image](https://github.com/user-attachments/assets/ad94fb50-19ba-4db8-bebf-4ad9cb3b2e48)

**Comment by ildar170975** [comment]
1. (unrelated) The `secondary_info: last-updated` is wrong, check Docs.
2. Check if you have card-mod version 3.4.4 (the latest).

**Comment by RobusX** [comment]
Thanks for reminding me to update...I was using 3.2.4 card-mod.

Now after an update, and HA reboot and a row with "secondary_info: last-updated" removal, sadly issue still persist.

With custom-fold entity row card is no such issue, so card-mod there works OK.

How is possible that on your card all works OK...do you have the same HA versions ? 
What should be the issue here...hmmm

**Comment by ildar170975** [comment]
running 2025.2.3

**Comment by RobusX** [comment]
ok, version not far away.
For example, this works OK, if placed outside template-entity, row, but is not useful for me...
i have nested cards, it should be inside template-entitiy row card:

```yaml
type: entities
entities:
  - type: custom:template-entity-row
    entity: binary_sensor.contact_sensor
    name: Main Door
card_mod:
  style: |
    :host {
      --mdc-icon-size: 40px !important;
      --paper-item-icon-color: red !important;
    }
```
