### ISSUE TITLE
Error: disallowed MIME type (“text/plain”) when using within Compass Card

### ISSUE THREAD

**Issue by 512catspaw** [thomasloven/lovelace-card-mod#446]
My Home Assistant version: 2025.2.5

My lovelace configuration method (GUI or yaml):YAML

What I am doing: attempting to use CSS style to change a font size

What I expected to happen: Font size change.  

What happened instead:
No font size change

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
# In Compass-Card:
type: custom:compass-card
indicator_sensors:
  - sensor: sensor.the_bluff_wind_direction
    indicator:
      type: arrow_inward
value_sensors:
  - sensor: sensor.the_bluff_wind_speed
  - sensor: sensor.the_bluff_wind_gust
    card_mod:
      style: |
        ha-card .value-sensor:last-child .value {
          font-size: 12px !important; /* Adjust size as needed */
        }
# End of code
```

Error messages from the browser console:
`Loading module from “http://homeassistant.local:8123/homeassistant/www/community/lovelace-card-mod/card-mod.js” was blocked because of a disallowed MIME type (“text/plain”).`

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
