### ISSUE TITLE
chips animation combined with ha-card not working

### ISSUE THREAD

**Issue by Marwxne** [thomasloven/lovelace-card-mod#450]
My Home Assistant version: 2025.3.4

My lovelace configuration method: GUI & yaml

What I am doing:
Trying to combine ha-card style with mushroom-template-chip:nth-child

What I expected to happen:
Having this animation
![Image](https://community-assets.home-assistant.io/original/4X/4/9/0/49002210f9fef06f48f37e71e7f7f21ac9c99ace.gif)

but with that kind of space around the chip
![Image](https://github.com/user-attachments/assets/d588c824-3b2d-4098-9b12-3177fc340d51)

What happened instead:
As you can see, there is no padding at all
![Image](https://github.com/user-attachments/assets/e75d4e3c-f30a-4977-aac2-65b6235a8bdc)

**Minimal** steps to reproduce:
For exemple, this is working well
```yaml
square: false
type: grid
cards:
  - type: custom:vertical-stack-in-card
    cards:
      - type: custom:mushroom-template-card
        primary: Salon
        secondary: "{{ states(entity) }}°C"
        icon: mdi:sofa
        entity: sensor.thermometre_salon_temperature
        layout: horizontal
        fill_container: false
        tap_action:
          action: none
        double_tap_action:
          action: none
        icon_color: >-
          {% if states(entity) | float < 18 %}
            #0044CC
          {% elif states(entity) | float >= 18 and states(entity) | float < 19
          %}
            #007FFF
          {% elif states(entity) | float >= 19 and states(entity) | float < 19.5
          %}
            #00BFFF
          {% elif states(entity) | float >= 19.5 and states(entity) | float < 20
          %}
            #FFD27F
          {% elif states(entity) | float >= 20 and states(entity) | float < 21.5
          %}
            #FFD700
          {% elif states(entity) | float >= 21.5 and states(entity) | float < 25
          %}
            #FF8C00
          {% elif states(entity) | float >= 25 %}
            #FF4500
          {% endif %}
      - type: custom:mushroom-chips-card
        chips:
          - type: template
            icon: mdi:cctv
            icon_color: deep-purple
            tap_action:
              action: none
            hold_action:
              action: none
            double_tap_action:
              action: none
            entity: camera.salon
        alignment: end
        card_mod:
          style: 
            mushroom-template-chip:nth-child(1)$: |
              ha-state-icon {
                animation: flip 8s ease-in-out infinite alternate;
              }
              @keyframes flip {
              50% { transform: rotateY(180deg); }
              }
title: 📍 Pièces
columns: 2
```

However, this is not working
```yaml
square: false
type: grid
cards:
  - type: custom:vertical-stack-in-card
    cards:
      - type: custom:mushroom-template-card
        primary: Salon
        secondary: "{{ states(entity) }}°C"
        icon: mdi:sofa
        entity: sensor.thermometre_salon_temperature
        layout: horizontal
        fill_container: false
        tap_action:
          action: none
        double_tap_action:
          action: none
        icon_color: >-
          {% if states(entity) | float < 18 %}
            #0044CC
          {% elif states(entity) | float >= 18 and states(entity) | float < 19
          %}
            #007FFF
          {% elif states(entity) | float >= 19 and states(entity) | float < 19.5
          %}
            #00BFFF
          {% elif states(entity) | float >= 19.5 and states(entity) | float < 20
          %}
            #FFD27F
          {% elif states(entity) | float >= 20 and states(entity) | float < 21.5
          %}
            #FFD700
          {% elif states(entity) | float >= 21.5 and states(entity) | float < 25
          %}
            #FF8C00
          {% elif states(entity) | float >= 25 %}
            #FF4500
          {% endif %}
      - type: custom:mushroom-chips-card
        chips:
          - type: template
            icon: mdi:cctv
            icon_color: deep-purple
            tap_action:
              action: none
            hold_action:
              action: none
            double_tap_action:
              action: none
            entity: camera.salon
        alignment: end
        card_mod:
          style: |
            ha-card {
              padding-top: 0px;
              margin-top: -8px;
              padding-bottom: 8px;
              padding-left: 8px;
              padding-right: 8px;
            }
            mushroom-template-chip:nth-child(1)$: |
              ha-state-icon {
                animation: flip 8s ease-in-out infinite alternate;
              }
              @keyframes flip {
              50% { transform: rotateY(180deg); }
              }
title: 📍 Pièces
columns: 2
```
In this 2nd example, the ha-card style is working but not the animation. Is there a special way to make that working or you can't combine ha-card style with nth-child ?

Error messages from the browser console:
No error message.
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
