### ISSUE TITLE
Page requires a refresh to display the colors injected via card-mod

### ISSUE THREAD

**Issue by ziffusion** [thomasloven/lovelace-card-mod#454]
My Home Assistant version: 2025.5.1

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Changing the background color of a card based on value.

What I expected to happen: Color should be as programmed.

What happened instead: The page requires a refresh before the colors will take effect.

**Minimal** steps to reproduce: Configure a card as shown in the yaml excerpt below.

```yaml
# The least amount of code possible to reproduce my error
          - type: tile
            entity: sensor.days_since
            features_position: bottom
            vertical: false
            name: Foobar
            tap_action:
              action: none
            icon_tap_action:
              action: more-info
            card_mod:
              style: |
                ha-card {
                  {% if states(config.entity)|float(0) < 2 %}
                    --ha-card-background: #769800;
                  {% elif states(config.entity)|float(0) < 3 %}
                    --ha-card-background: #f99502;
                  {% else %}
                    --ha-card-background: #c35353;
                  {% endif %}
                }
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
