### ISSUE TITLE
Icon color change stop to work. Size continue to work properly

### ISSUE THREAD

**Issue by markchang80** [thomasloven/lovelace-card-mod#455]
My Home Assistant version: 0.XX.X 2025.5.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Change icon size and color

What I expected to happen: Change icon size and color

What happened instead: Changes only size, and before color works too 90% of the time, and in the other 10%, only two or tree refresh was ok to obtain size and color changes

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
type: picture-elements
layout_options:
  grid_columns: 2
  grid_rows: 2
elements:
  - type: state-icon
    entity: button.calefaccion_programado
    icon: mdi:home-clock-outline
    state_color: true
    tap_action:
      action: toggle
    style:
      left: 20%
      top: 60%
      border-radius: 50%
    card_mod:
      style: |
        :host{
           --paper-item-icon-color: var(--deep-orange-color);
           --mdc-icon-size: 40px;
            background: none !important;
                  }
  - type: state-icon
    entity: button.calefaccion_ahorro
    icon: mdi:home-thermometer-outline
    state_color: true
    tap_action:
      action: toggle
    style:
      left: 50%
      top: 60%
      border-radius: 50%
    card_mod:
      style: |
        :host{
           --paper-item-icon-color: var(--green-color);
           --mdc-icon-size: 40px;
            background: none !important;
                  }
  - type: state-icon
    entity: button.calefaccion_antifrost
    icon: mdi:snowflake-thermometer
    state_color: true
    tap_action:
      action: toggle
    style:
      left: 80%
      top: 60%
      border-radius: 50%
    card_mod:
      style: |
        :host{
           --paper-item-icon-color: var(--light-blue-color);
           --mdc-icon-size: 40px;
            background: none !important;
                  }
image: https://placeholder.pics/svg/150x70/1c1c1c/1c1c1c


# End of code
```

Error messages from the browser console:
No errors, at least at my knowledge level of HA
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
