### ISSUE TITLE
can't access DOM when styling simple markdown-card

### ISSUE THREAD

**Issue by klauskirchmayr** [thomasloven/lovelace-card-mod#457]
My Home Assistant version: 2025.5.2     card_mod: 3.4.4

My lovelace configuration method (GUI or yaml): yaml

What I am doing: try to do a table with markdown-card

What I expected to happen: i can apply color and borders to table elements

What happened instead: no colors or borders possible

**Minimal** steps to reproduce:
i used a minimal test setup of home assistant. basically only card-mod is loaded and only one dashboard/view/card ist used.

```yaml
# The least amount of code possible to reproduce my error

title: TEST
views:
  - title: TESTBENCH
    type: panel
    cards:
      - type: vertical-stack
        cards:
          - type: markdown      #no colors or borders on this one
            card_mod:
              style:
                $: |
                  ha-card {
                    background-color: lightcoral !important;
                    border: 5px solid deeppink !important; /* Andere Farbe für den Rahmen zum erneuten Testen */
                    padding: 10px !important; /* Etwas Padding hinzufügen */
                  }
            content: |
              | Spalte A | Spalte B |
              | :------- | :------- |
              | Wert 1   | Wert 2   |

          - type: markdown      #this one shows the red background, what could be expected
            card_mod:
              style: |
                ha-card {
                  background-color: red !important;
                }
            content: |
              | Header a | Header 2 |
              | :------- | :------- |
              | Cell 1   | Cell 2   |
              | Cell 3   | Cell 4   |



# End of code
```

Error messages from the browser console:

no errors to be seen

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
