### ISSUE TITLE
Eliminate border and shadow around auto-entities card using mod-card workaround

### ISSUE THREAD

**Issue by drew-kun** [thomasloven/lovelace-card-mod#46]
My Home Assistant version: 0.110.1

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
I am trying to get rid of shadow and border around auto-entities card using mod-card workaround

What I expected to happen:
Flattening the view due to shadow and border to be gone

What happened instead:
The shadow around the Brightness and Temperature box (auto-entities card) is not disappearing.
![Screen Shot 2020-05-24 at 1 32 02 PM](https://user-images.githubusercontent.com/10493450/82757845-9f143b00-9deb-11ea-8460-cb86f47d91b8.png)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
cards:
- type: vertical-stack
  title: Kitchen Controls
  cards:
  - type: entities
    title: Kitchen Lights
    entities:
    - light.kitchen_intelite
    - type: custom:mod-card
      style: |
        ha-card {
          border: 0px;
          background: none;
          box-shadow: none;
        }
      card:
        type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          show_header_toggle: false
        filter:
          template: |
            {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','off')%}
             input_number.kitchen_intelite_brightness
              input_number.kitchen_intelite_temperature
            {% endif %}
            {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','on')%}
             input_number.kitchen_intelite_brightness_dark_mode
            {% endif %}
    footer:
      type: buttons
      entities:
      - entity: switch.kitchen_intelite_mourn_mode
      - entity: switch.kitchen_intelite_noon_mode
      - entity: switch.kitchen_intelite_eve_mode
      - entity: switch.kitchen_intelite_dark_mode


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
