### ISSUE TITLE
iron-icon-fill-color no longer working since 0.110

### ISSUE THREAD

**Issue by Noahnc** [thomasloven/lovelace-card-mod#48]
My Home Assistant version: 0.110.4

My lovelace configuration method (GUI or yaml): GUI

What I am doing: 
Create a entities card with a battery sensor which I want to change the icon color.

What I expected to happen:
The batterie icon should change its color to green.

What happened instead:
The icons is still displayed in the color of the Lovelace Theme.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

entities:
  - entity: sensor.openclose_5_battery_level
    name: Name
    style: |
      :host {   
         --iron-icon-fill-color: green ;
      }
type: entities

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
