### ISSUE TITLE
box shadow does not get away

### ISSUE THREAD

**Issue by philipp089** [thomasloven/lovelace-card-mod#50]
Hi Thomas, 

first of all, thank you for your effort and work in this community and for your plug-ins, greatly appreciate that.

My Home Assistant version: 0.110.4

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
I am trying to get rid of the box shadow of Mini-Media-Player to suite my UI-Design:
see: https://community.home-assistant.io/t/google-inspired-home-assistant-on-mobile/202191

What I expected to happen:
i expect to get rid of the box shadow with following code:

```
entity: media_player.sonos_wohnzimmer
show_header_toggle: false
icon: 'mdi:play-box-outline'
name: Sonos Play One Wohnzimmer
artwork: full-cover
style: |
  ha-card {
    box-shadow: none;
    webkit-box-shadow: none;
  } 
type: 'custom:mini-media-player'
```

What happened instead:
nothing

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

entity: media_player.sonos_wohnzimmer
show_header_toggle: false
icon: 'mdi:play-box-outline'
name: Sonos Play One Wohnzimmer
artwork: full-cover
style: |
  ha-card {
    box-shadow: none;
    webkit-box-shadow: none;
  } 
type: 'custom:mini-media-player'


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
