### ISSUE TITLE
Select the element under two nested shadow roots

### ISSUE THREAD

**Issue by bsrdjan** [thomasloven/lovelace-card-mod#51]
Probably not a bug, only I can't find a way to select the `ha-icon`, below two nested shadow roots, and change its color. A hint which selector should work in this case would be very appreciated:

**DOM**
<img width="680" alt="Element" src="https://user-images.githubusercontent.com/1697847/83974559-7a8d8800-a8ee-11ea-8eca-fdf1d8692208.png">

**ui-lovelace**

```yaml
     - entity: sensor.ics_1 # Rest
       style:
         .: |
           hui-generic-entity-row {
             color: red;
           }
```

**result**

<img width="326" alt="Screenshot 2020-06-07 at 18 36 54" src="https://user-images.githubusercontent.com/1697847/83974494-e7545280-a8ed-11ea-9e4d-c8984b231984.png">

**Comment by p1ll0wf0rtress** [comment]
I'm in the same boat - looking to increase the size of the icons on a glance card.

**Comment by MijnGedacht** [comment]
Here's an example of styling text and icon in a Lovelace markdown card.
Structure of markdown looks like this:
```
<ha-card>
  Welcome to Lovelace text
    shadow-root
      <ha-markdown>
        shadow-root
          <ha-markdown-element>
            <ha-icon>
```

The icon is located somewhere under under ha-markdown tree. 
Try it yourself and view inspector in the browser.
With this example I hope you can solve your issue.


```
cards:
  - type: markdown
    content: |
      Welcome to Lovelace <ha-icon icon='mdi:home-assistant'></ha-icon>
    style:
      .: |
        ha-card {
          font-size: 24px;
        }
      ha-markdown:
        $: |
          ha-icon {
            color: red;
            float: right;
            animation: blink 1s linear infinite;
          }
          @keyframes blink {
            0%, 49% {color: white;}
            50%, 85% {color: red;}
          }
```

Also have a look here for more info and hints --> [Custom font styling is not applied to markdown card](https://github.com/thomasloven/lovelace-card-mod/issues/52)

**Comment by strafe** [comment]
@thomasloven could you elaborate on this or possibly reopen? The last comment shows an element that's only under one shadow root, not two or more.

**Comment by KTibow** [comment]
@strafe use the new syntax `first$second$: |`

**Comment by JtMotoX** [comment]
<img width="422" height="153" alt="Image" src="https://github.com/user-attachments/assets/d93cb4cf-807b-4e59-8ef9-a2b82911245b" />

---

I am able to apply the css to the `hui-clock-card-digital` with this:
```css
hui-clock-card-digital {
  font-size: 14rem !important;
}
```

But what I need is to have it apply inside the #shadow-root elements, which I cannot seem to get working.

```css
hui-clock-card-digital:
  $: |
    .time-parts {
      font-size: 14rem !important;
    }
```

Please help. Thank you.

**Comment by dcapslock** [comment]
> But what I need is to have it apply inside the #shadow-root elements, which I cannot seem to get working.

This is working for me.

```yaml
clock_style: digital
clock_size: large
show_seconds: true
no_background: false
type: clock
grid_options:
  columns: 48
  rows: 4
face_style: markers
card_mod:
  style:
    hui-clock-card-digital:
      $: |
        .time-parts {
          font-size: 14rem !important;
        }

```
