### ISSUE TITLE
Bug with mod-card and layout-card

### ISSUE THREAD

**Issue by mortimus1987** [thomasloven/lovelace-card-mod#54]
My Home Assistant version: **0.112.0 (but issue existed in .111.x and .110..x also)**

My lovelace configuration method (GUI or yaml): **yaml**

What I am doing: **trying to use mod-card to apply styles to a layout card**

What I expected to happen: **Style to be applied, cards to display**

What happened instead: **red card error box displayed with "n.setConfig is not a function" error. The card may actually display correctly the first time the config is altered, but on refresh it throws the error. It will also sometimes work after a seemingly random period, navigating to other views and back. Tested on Chrome and Firefox on desktop and on the official android app, and shows up in all three. Everything worked perfectly up until 0.110 (I think), this issue has only started appearing since then and I haven't made any changes to my lovelace configuration that would cause it.**

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

- type: custom:mod-card
  style: |
    :host {
      padding: 20px;
    }
  card:
    type: custom:layout-card
    cards:

      - type: entities
        title: test1
        entities:
          - light.office_main


# End of code
```

Error messages from the browser console:

chunk.05249f4f0c68b2555de6.js:12717 card custom:mod-card TypeError: n.setConfig is not a function
    at h (card-mod.js:1)
    at p (card-mod.js:1)
    at card-mod.js:1
    at HTMLElement.setConfig (card-mod.js:1)
    at s (chunk.05249f4f0c68b2555de6.js:12717)
    at chunk.05249f4f0c68b2555de6.js:12717
    at d (chunk.05249f4f0c68b2555de6.js:12717)
    at l (chunk.05249f4f0c68b2555de6.js:12717)
    at Kt (chunk.05249f4f0c68b2555de6.js:11940)
    at HTMLElement.value (chunk.05249f4f0c68b2555de6.js:23033)

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
