### ISSUE TITLE
debug_cardmod: true not working

### ISSUE THREAD

**Issue by KTibow** [thomasloven/lovelace-card-mod#58]
My Home Assistant version: 0.112.4

My lovelace configuration method (GUI or yaml): GUI (but using YAML to control `card-mod`)

What I am doing: Trying to set the background color of `layout-card` and expecting debug info

What I expected to happen: In the console I could see debug info

What happened instead: I saw nothing

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
# Any type works, but here I use the entities type
type: entities
entities:
  - person.kendell
debug_cardmod: true
style:
  .: |
    * {
      background-color: red !important;
    }
# End of code
```

Error messages from the browser console:
None, except for an annoying unrelated `card-tools` one:
```yaml
card-tools.js:1 Uncaught (in promise) TypeError: Cannot read property '_addCard' of null
    at card-tools.js:1
    at new Promise (<anonymous>)
    at Module.<anonymous> (card-tools.js:1)
    at r (card-tools.js:1)
    at card-tools.js:1
    at card-tools.js:1
```

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
