### ISSUE TITLE
0.113.1: popup_card shows more-info popup before showing styled popup

### ISSUE THREAD

**Issue by syphernl** [thomasloven/lovelace-card-mod#64]
**My Home Assistant version:** 0.113.1

**My lovelace configuration method (GUI or yaml):** yaml

**What I am doing:**
I am using `popup_cards` to "spice up" my HASS install. When I now click an entity that has a popup_card tied to it I briefly see the original more-info popup from the entity the popup_card is connected to before it actually shows my popup.

With 0.112 / BrowserMod 29 I didn't have this behavior.

**What I expected to happen:**
popup_card to show without showing the more-info popup.

**What happened instead:**
more-info popup gets shown, popup_card on top of it. This particular issue may be related to card-mod: https://github.com/thomasloven/lovelace-card-mod/issues/63

**Minimal steps to reproduce:**

```yaml
  light.tradfri_zolder:
    title: Attic
    style:
      width: 500px
    card:
      type: custom:vertical-stack-in-card
      style: !include ../includes/style_entities_popup.yaml
      cards:
        - type: horizontal-stack
          cards:
            - !include
              - ../includes/graphs_popup.yaml
              - entity: sensor.temperature_attic
                name: Temperature
                font_size_header: 12
                line_color: var(--custom_graph_color_1)
            - !include
              - ../includes/graphs_popup.yaml
              - entity: sensor.humidity_attic
                name: Humidity
                font_size_header: 12
                line_color: var(--custom_graph_color_3)
        - !include
          - ../includes/titles.yaml
          - title: MUSIC
        - type: entities
          style: !include ../includes/style_entities_popup.yaml
          entities:
            - type: 'custom:mini-media-player'
              entity: media_player.mini_attic
              info: short
              group: true
              icon: mdi:google-home
              artwork: cover
              hide:
                name: true
                power_state: false
        - !include
          - ../includes/titles.yaml
          - title: LIGHTS & MOTION
        - type: entities
          style: !include ../includes/style_entities_popup.yaml
          show_header_toggle: false
          entities:
            - entity: light.tradfri_zolder
              name: Light
              icon: mdi:ceiling-light
              type: custom:slider-entity-row
        - type: entities
          style: !include ../includes/style_entities_popup.yaml
          entities:
            - entity: binary_sensor.pir_zolder_sensor
              name: Motion Sensor
              secondary_info: last-changed
# End of code
```

**Error messages from the browser console:**

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
