### ISSUE TITLE
TypeError: null is not an object (evaluating '(a?e.shadowRoot:e).appendChild')

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#65]
My Home Assistant version: 0.113.1

My lovelace configuration method (GUI or yaml):

yaml
What I am doing:

not sure, seems to coincide with <strike>pages using markdown. 
or conditional cards, though I cant state is a 100% match</strike> Entity Cards containing other (custom) cards. Really difficult to pin it down. Has been here for a very long time though. Below is an example that, even without the styling of card-mod, causes the error to appear.

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

type: entities
entities:
  - type: custom:hui-element
    card_type: markdown
    title: |
      Home Assistant --> Google Assistant
      Voice commands
#    style: |
#      ha-card {background: url('/local/various/google_assistant.png');
#               background-size: cover;
#               box-shadow: none;
#               margin: -16px -16px 0px -16px;
#               }
    content: |
      Ok/Hey Google,

# End of code
```

Error messages from the browser console:
in Safari (Mac)
```
Unhandled Promise Rejection: TypeError: null is not an object (evaluating '(a?e.shadowRoot:e).appendChild')
```

<img width="505" alt="Schermafbeelding 2020-07-27 om 22 25 18" src="https://user-images.githubusercontent.com/33354141/88588595-18ccdd00-d058-11ea-9013-965e4da9e4bd.png">

in Chrome (Mac)

```
Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null
    at c (card-mod.js?v=2.0:1)
```

<img width="725" alt="Schermafbeelding 2020-07-27 om 22 25 57" src="https://user-images.githubusercontent.com/33354141/88588642-2d10da00-d058-11ea-9936-268941fba3f0.png">

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ ] Have made sure I am using the latest version of the plugin.

[ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Mariusthvdb** [comment]
The same error arises when listing an auto-entities card in an entities card, which I need to do when the card has to show some other entities too :

```
  - type: entities
    title: Life360 sensors
    entities:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: binary_sensor.overdue_life360_*
#              options:
#                secondary_info: last-changed
#        sort:
#          method: state
#          reverse: true
#      - type: divider
#      - automation.life360_connected
```

Making the auto-entities card above the sole card to display takes out the error:
```
      - type: custom:auto-entities
         card:
           type: entities
        filter:
          include:
            - entity_id: binary_sensor.overdue_life360_*
```
