### ISSUE TITLE
Changing themes using class does not update card background

### ISSUE THREAD

**Issue by tomlut** [thomasloven/lovelace-card-mod#66]
My Home Assistant version: 0.113.1

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Changing the theme via an automation.

What I expected to happen: All of the theme elements to change.

What happened instead: Everything except the card background changes, until I change views or refresh the screen, then the card background changes. This only occurs when using classes. Using the direct theme element works as expected.

**Minimal** steps to reproduce:

```yaml
### Not functioning as expected###

  card-mod-theme: night
  card-mod-card: |

    ha-card.top-level-card {
      border: solid 1px var(--secondary-text-color);
      background: url("/local/background/card_bg_Night.png");
    }
```
```yaml
###Functions as expected:###

  ha-card-background: 'url("/local/background/card_bg_Night.png")'
```
Error messages from the browser console:
```
Uncaught (in promise) TypeError: null has no properties
    c https://XXXX.duckdns.org/hacsfiles/lovelace-card-mod/card-mod.js:1
```

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by tomlut** [comment]
Still an issue with home assistant 0.117.2

**Comment by thomasloven** [comment]
Please try card-mod 3.0

**Comment by tomlut** [comment]
Hi Thomas, 

I have been unable to use v3 because of this issue:

https://community.home-assistant.io/t/card-mod-super-charge-your-themes/212176/781

Should I open another issue for this?

**Comment by tomlut** [comment]
Just tied 3.0.6. It does not fix this issue (also the mobile/desktop issue remains too but I will open a new issue for that).

**Comment by thomasloven** [comment]
I'm sorry. I can't reproduce the problem.

```yaml
test:
  card-mod-theme: test
  card-mod-card: |

    ha-card {
      background: url("https://placebear.com/640/480")
    }
    ha-card.top-level-card {
      border: solid 1px var(--secondary-text-color);
      background: url("https://placekitten.com/640/480");
    }
```

![image](https://user-images.githubusercontent.com/1299821/109625504-aff29980-7b3f-11eb-8cfd-86e64f162868.png)

**Comment by tomlut** [comment]
The issue occurs when changing the theme with an automation:

automation
```
- alias: 'Select Theme'
  trigger:
  - platform: state
    entity_id: input_select.select_theme
  action:
    service: frontend.set_theme
    data:
      name: "{{ states('input_select.select_theme')|lower }}"
```
input select
```
select_theme:
  name: Select Theme
  options:
  - Day
  - Night
```

themes
```
day:
  card-mod-theme: day
  card-mod-card: |
    ha-card.top-level-card {
      border: solid 1px var(--primary-text-color);
      background: url("/local/background/card_bg_Day.png");
    }

night:
  card-mod-theme: night
  card-mod-card: |
    ha-card.top-level-card {
      border: solid 1px var(--secondary-text-color);
      background: url("/local/background/card_bg_Night.png");
    }
```

I did notice that the card background updates as soon as an entity in the card updates now that I'm using card-mod v3:

![update](https://user-images.githubusercontent.com/10679300/109631977-58b4ef00-7b68-11eb-96ec-e9c15c76c075.png)
