### ISSUE TITLE
2.0.1/2 moves full card config based on individual mod

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#74]
My Home Assistant version: 0.XX.X
116.0

My lovelace configuration method (GUI or yaml):

yaml
What I am doing:
```
  - type: entities
    title: System settings
    show_header_toggle: false
    style: |
      .card-header {color: var(--primary-color);font-weight: bold;}
    entities:
      - sensor.speedtest_download
      - type: custom:slider-entity-row
        entity: input_number.ha_delayed_startup
      - type: divider
      - entity: automation.update_available
        secondary_info: last-triggered
      - entity: automation.updater_notification
        secondary_info: last-triggered
      - type: divider
      - type: custom:hui-element
        card_type: markdown
        style: |
          .card-header {color: var(--primary-color);font-weight: bold;}
          ha-card {
            box-shadow: none;
            margin: -5px 15px 0px -15px;
          }
        title: Log tail
        content: >
          {{states('sensor.log_tail')}}
```
What I expected to happen:

show the above setup aligned (as it was up to 2.0.0)

What happened instead:

1 picture says it all:

<img width="583" alt="Schermafbeelding 2020-10-08 om 15 01 55" src="https://user-images.githubusercontent.com/33354141/95462012-3b904180-0977-11eb-8eab-bd34f6cea591.png">

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
      - type: custom:hui-element
        card_type: markdown
        style: |
          .card-header {color: var(--primary-color);font-weight: bold;}
          ha-card {
            box-shadow: none;
            margin: -5px 15px 0px -15px;
          }

# End of code
```
couldnt really say, in the above code. Surely it is the style: with the margin settings. After having refreshed a few times, this sometimes goes way. And displays as it should (up to 2.0.0)

<img width="562" alt="Schermafbeelding 2020-10-08 om 15 05 43" src="https://user-images.githubusercontent.com/33354141/95462401-c2ddb500-0977-11eb-949f-eb3f933c0193.png">

only to come back again unexpectedly. 
Have tested some more, and can conform it is the update from 2.0.0 to 2.0.1 causing this behavior. I'll change the title of the issue accordingly

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X ] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Ah yes, I can see why it's happening.

I'll have a fix up for card-mod and hui-element soon.

As a workaround, try to be more specific in your style. card-mod adds a class to every card with its type, so you could to `ha-card.type-markdown` to only have it apply to the markdown card in this case.

**Comment by thomasloven** [comment]
I like what you've got going on there, btw. It looks cool!

**Comment by Mariusthvdb** [comment]
so I understand completely:

> As a workaround, try to be more specific in your style. card-mod adds a class to every card with its type, so you could to ha-card.type-markdown to only have it apply to the markdown card in this case.

that is new to this version 2.0.1/2 ? Ive never seen this before, and use the technique on many 'dashboard' cards like this (which indeed now all show with the individual card_mod style for the full setup....

**Comment by thomasloven** [comment]
That's weird, because it 100% works all the time for me:
```yaml
type: entities
title: test
entities:
  - light.bed_light
  - type: 'custom:hui-element'
    card_type: markdown
    content: Hello!
    title: test2
    style: |
      ha-card.type-markdown .card-header {
        color: red;
      }
      ha-card.type-markdown {
          margin-left: 20px;
      }
````
![image](https://user-images.githubusercontent.com/1299821/95515785-74073e00-09be-11eb-83d7-73741b3742ba.png)

vs this without `.type-markdown`
![image](https://user-images.githubusercontent.com/1299821/95515827-85504a80-09be-11eb-9791-e50b329f2a35.png)
