### ISSUE TITLE
card_mod doest work with glance and Custom UI sind 0.116.2

### ISSUE THREAD

**Issue by gadric** [thomasloven/lovelace-card-mod#78]
My Home Assistant version: 0.106.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing: reduce the font size in official glance card 

What I expected to happen: font size in glance card to decrease, which worked until 2 or 3 days again. 

What happened instead: the defined style is not applied. 

**Minimal** steps to reproduce:

- Install Home Assistant 0.116.2
- Install custom-ui from here: https://github.com/Mariusthvdb/custom-ui
- Install card-mod over hacs
- use the code below

```yaml
# The least ammount of code possible to reproduce my error

- type: glance
  show_icon: false
  columns: 6
  align: right
  style: |
    ha-card {
      font-size: 12px;
      margin-top: -2.5%;
    }
  state_color: true
entities:
  - entity: sensor.hourly_current_total_power_consumption
    name: "Hourly"
  - entity: sensor.daily_current_total_power_consumption
    name: "Today"
  - entity: sensor.weekly_current_total_power_consumption
    name: "Weekly"
  - entity: sensor.monthly_current_total_power_consumption
    name: "Monthly"
  - entity: sensor.quarterly_current_total_power_consumption
    name: "Quarterly"
  - entity: sensor.yearly_current_total_power_consumption
    name: "Yearly"
# End of code
```

Error messages from the browser console:

no error message
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
What happens if you remove everything but card-mod?

**Comment by gadric** [comment]
Then it works normal/as expected.

**Comment by KTibow** [comment]
Update card-mod?

**Comment by gadric** [comment]
I am on version 2.0.2 installed via HACS. Isn’t it the most recent of card-mod?

**Comment by KTibow** [comment]
Clear cache and reload?

**Comment by gadric** [comment]
I did this. No change. Tried also different browsers, no change ... were there breaking changes in the last card-mod update 2 days ago?

**Comment by Mariusthvdb** [comment]
as a fyi, ive added your mod together with a header mod like this:
```
  - type: glance
    title: Weather glance
    style: |
      .card-header {color: var(--primary-color);font-weight: bold;}
      ha-card {
        font-size: 12px;
        margin-top: -2.5%;
      }
    entities:
      - weather.dark_sky
      - weather.buienradar
      - weather.openweathermap
```

and it all works just fine?

<img width="444" alt="Schermafbeelding 2020-10-10 om 23 40 24" src="https://user-images.githubusercontent.com/33354141/95665576-ff650880-0b51-11eb-856d-d192508f6fbc.png">

compare without mod:

<img width="441" alt="Schermafbeelding 2020-10-10 om 23 41 18" src="https://user-images.githubusercontent.com/33354141/95665587-24f21200-0b52-11eb-8aea-b6b3ab779695.png">

**Comment by gadric** [comment]
That is really weird. 

I have done the same test including screenshots. 

Here is the code: 

```yaml

      - type: vertical-stack
        in_card: true 
        cards:
          - type: entities
            title: Infrastructure
            entities:
              - entity: sensor.current_total_power_consumption
                type: custom:multiple-entity-row
                name: Total Power Consumption
                state_header: Status
                show_state: false
                entities:
                  - entity: sensor.current_total_power_consumption
                    name: Current
                  - entity: sensor.statistics_sensor_current_total_power_consumption
                    name: Average
          - type: glance
            show_icon: false
            columns: 6
            align: right
            style: |
              ha-card {
                font-size: 12px;
                margin-top: -2.5%;
              }
            state_color: true
            entities:
              - entity: sensor.hourly_current_total_power_consumption
                name: "Hourly"
              - entity: sensor.daily_current_total_power_consumption
                name: "Today"
              - entity: sensor.weekly_current_total_power_consumption
                name: "Weekly"
              - entity: sensor.monthly_current_total_power_consumption
                name: "Monthly"
              - entity: sensor.quarterly_current_total_power_consumption
                name: "Quarterly"
              - entity: sensor.yearly_current_total_power_consumption
                name: "Yearly"
          - type: glance
            show_icon: false
            show_name: false
            style: |
              ha-card {
                font-size: 12px;
                margin-top: -2.5%;
              }
            align: right
            columns: 6
            state_color: true
            entities:
              - entity: sensor.cost_of_hourly_total_power_consumption
                name: "Hourly"
              - entity: sensor.cost_of_daily_total_power_consumption
                name: "Today"
              - entity: sensor.cost_of_weekly_total_power_consumption
                name: "Weekly"
              - entity: sensor.cost_of_monthly_total_power_consumption
                name: "Monthly"
              - entity: sensor.cost_of_quarterly_total_power_consumption
                name: "Quarterly"
              - entity: sensor.cost_of_yearly_total_power_consumption
                name: "Yearly"

```

With card-mod style: 

![Screenshot 2020-10-11 115521](https://user-images.githubusercontent.com/19403905/95675651-1db21f00-0bb9-11eb-8d09-c62f12e8be3f.png)

And this is without card-mod style
![Screenshot 2020-10-11 114657](https://user-images.githubusercontent.com/19403905/95675661-2571c380-0bb9-11eb-8c08-049063e4b067.png)

**Comment by Mariusthvdb** [comment]
not sure if this is the place, so if Thomas removes us, please continue on the community, but:

what does `in_card: true` in the [vertical-stack](https://www.home-assistant.io/lovelace/vertical-stack/)? no option like that documented?
then, you use `state_color: true` but these are not binary states, so that doesn't do anything? And, on the bottom glance, you have `show_name: false`, yet you specifically set the name for these entities. Lastly you use `align: right` for the bottom [glance](https://www.home-assistant.io/lovelace/glance/) and tis also isn't an option documented?

why don't you first check these configs for these options, and then show us a minimum piece of code that should work?

**Comment by gadric** [comment]
Well reducing everything to the minimum does not change the situation. 

```yaml in_card: true ```  is to put everything in the vertical stack in one card. Can you see the different in the screenshot
```yaml state_color: true ```, ```yaml show_name: false ```& ```yaml align: right ``` yes you are right. I removed it. 


Now the code looks like this: 

```yaml
      - type: vertical-stack
        #in_card: true 
        cards:
          - type: entities
            title: Infrastructure
            entities:
              - entity: sensor.current_total_power_consumption
                type: custom:multiple-entity-row
                name: Total Power Consumption
                state_header: Status
                show_state: false
                entities:
                  - entity: sensor.current_total_power_consumption
                    name: Current
                  - entity: sensor.statistics_sensor_current_total_power_consumption
                    name: Average
          - type: glance
            show_icon: false
            columns: 6
            align: right
            style: |
              ha-card {
                font-size: 12px;
                margin-top: -2.5%;
              }
            #state_color: true
            entities:
              - entity: sensor.hourly_current_total_power_consumption
                name: "Hourly"
              - entity: sensor.daily_current_total_power_consumption
                name: "Today"
              - entity: sensor.weekly_current_total_power_consumption
                name: "Weekly"
              - entity: sensor.monthly_current_total_power_consumption
                name: "Monthly"
              - entity: sensor.quarterly_current_total_power_consumption
                name: "Quarterly"
              - entity: sensor.yearly_current_total_power_consumption
                name: "Yearly"
          - type: glance
            show_icon: false
            #show_name: false
            style: |
              ha-card {
                font-size: 12px;
                margin-top: -2.5%;
              }
            #align: right
            columns: 6
            #state_color: true
            entities:
              - entity: sensor.cost_of_hourly_total_power_consumption
                #name: "Hourly"
              - entity: sensor.cost_of_daily_total_power_consumption
                #name: "Today"
              - entity: sensor.cost_of_weekly_total_power_consumption
                #name: "Weekly"
              - entity: sensor.cost_of_monthly_total_power_consumption
                #name: "Monthly"
              - entity: sensor.cost_of_quarterly_total_power_consumption
                #name: "Quarterly"
              - entity: sensor.cost_of_yearly_total_power_consumption
                #name: "Yearly"
```


![Screenshot 2020-10-11 124516](https://user-images.githubusercontent.com/19403905/95676622-b481da00-0bbf-11eb-84c4-b9ac99f0af30.png)

**Comment by Mariusthvdb** [comment]
One more try: please see if listing  the entities instead of the object helps?

Check my example.

**Comment by gadric** [comment]
Unfortunately, 

listing the entities does not change ...

![image](https://user-images.githubusercontent.com/19403905/95677959-80131b80-0bc9-11eb-899b-26a53cbff0d8.png)

code: 

```yaml
      - type: vertical-stack'
        in_card: true 
        title: Infrastructure
        cards:
          - type: glance
            title: Test glance
            style: |
              .card-header {color: var(--primary-color);font-weight: bold;}
              ha-card {
                font-size: 12px;
                margin-top: -2.5%;
              }
            entities:
              - sensor.hourly_current_total_power_consumption
              - sensor.daily_current_total_power_consumption
              - sensor.weekly_current_total_power_consumption
          - type: glance
            title: Test glance without
            entities:
              - sensor.hourly_current_total_power_consumption
              - sensor.daily_current_total_power_consumption
              - sensor.weekly_current_total_power_consumption
```
