### ISSUE TITLE
Modification of element in shadow-root takes several seconds on load

### ISSUE THREAD

**Issue by noxhirsch** [thomasloven/lovelace-card-mod#8]
My Home Assistant version: 0.97.2

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
I modded the map card to reduce the size of the device_tracker markers.

What I expected to happen:
That they are always smaller from the beginning they appear

What happened instead:
When I load the view, the markers appear in their original size. After several seconds (2-15 sec) they scale down to the intended size. When I click on them, the scale down immediately.

**Minimal** steps to reproduce:
Add the yaml code for a map card with a device_tracker (no entity_picture needed)

```yaml
# The least ammount of code possible to reproduce my error

aspect_ratio: '3:2'
dark_mode: true
default_zoom: 14
entities:
  - entity: device_tracker.first_tracker
  - entity: device_tracker.second_tracker
style:
  .: |
    .leaflet-control-zoom {
      opacity: 0.2;
    }
    .leaflet-control-attribution {
      opacity: 0.2;
    }
    paper-icon-button{
      opacity: 0.3;
    }
    .leaflet-marker-icon{
        margin-top: -18px!important;
        margin-left: -18px!important;
        width: 32px!important;
        height: 32px!important;
    }
  ha-entity-marker:
    $: |
      .marker {
        width: 32px!important;
        height: 32px!important;
      }
type: map


# End of code
```

Error messages from the browser console:
No errors

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
