### ISSUE TITLE
Styled title of vertical-stack

### ISSUE THREAD

**Issue by radek-foltyn** [thomasloven/lovelace-card-mod#81]
Hi, is it possible styled title?

```
- type: vertical-stack
    title: Kitchen
    panel: true
    cards:
      - type: horizontal-stack
```
I would like change padding of this element
