### ISSUE TITLE
Styling badges - Loosing custom color

### ISSUE THREAD

**Issue by medicus07** [thomasloven/lovelace-card-mod#84]
My Home Assistant version: 0.115.1, problem in newer versions of HA, don't know since when... before it was working fine

My lovelace configuration method (GUI or yaml): YAML

What I am doing: 
I style my badges with card mod in the following way...

``` 
badges:
  - entity: binary_sensor.garage_status
    name: Garage
      style: |
        :host {
          --label-badge-blue: {% if is_state('binary_sensor.garage_status', 'off') %} green {% else %} red {% endif %};
        }
```

What I expected to happen: 
Changing color of the badge between green and red...

What happened instead: 
When refreshing webpage or app, there is no color in styled batches anymore. After clicking or touching screen, push a button or something else, the color appears again. In older versions of HA it worked just fine without this bug.

Screenshots:
<img width="340" alt="Bildschirmfoto 2020-11-22 um 08 53 56" src="https://user-images.githubusercontent.com/24975901/99898252-4e996f80-2ca0-11eb-8550-64bddce7c691.png">
<img width="344" alt="Bildschirmfoto 2020-11-22 um 08 53 40" src="https://user-images.githubusercontent.com/24975901/99898255-51946000-2ca0-11eb-90e0-91a9eacba9ab.png">

**Comment by KTibow** [comment]
Does it work in 0.118? Are you sure you only need to style `label-badge-blue`?

**Comment by medicus07** [comment]
No, with 0.118 it is still the same problem. 
For the binary sensor changing only the standard blue color shoulder be correct.

**Comment by KTibow** [comment]
It could be the feature that auto-disconnects the event stream. I believe binary sensors toggle between `label-badge-blue` and `label-badge-red`.

**Comment by medicus07** [comment]
Any chance to solve the problem?

**Comment by KTibow** [comment]
Can you give a reproducible config?

**Comment by medicus07** [comment]
in configuration.yaml I use the following:

```
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/custom-ui/custom-ui.js

lovelace:
  mode: yaml

homeassistant:
  customize:
    binary_sensor.garage_status:
      device_class: garage_door
      unit_of_measurement: 'Status'

binary_sensor:
  - platform: mqtt
    state_topic: "homee.garage"
    name: "Garage Status"
```

in ui-lovelace.yaml I use the following:

```
resources:
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module

views:
  - badges:
      - entity: binary_sensor.garage_status
        name: Garage
        style: |
          :host {
            --label-badge-blue: {% if is_state('binary_sensor.garage_status', 'off') %} green {% else %} red {% endif %};
          }
```
