### ISSUE TITLE
FloorPlan in full screen

### ISSUE THREAD

**Issue by fcastroruiz** [thomasloven/lovelace-card-mod#9]
I have problem with image css format, i try to reference with #id but do not work, 
```yaml
  - badges: []
    title: P ALTA
    panel: true
    cards:
      - type: picture-elements
        title: esto es una prueba
        style: |
          ha-card {
            height:70vh;
          }
          .card-header {
            font-size: 1px;
          }
          #image {
            height: 70vh;
            width: auto;
          }
        image: /local/3d_planta_alta.jpg
        elements:
          - entity: alarm_control_panel.alarma
            style:
              '--iron-icon-height': 50px
              '--iron-icon-width': 50px
              left: 94%
              top: 4%
            type: state-icon
```
![image](https://user-images.githubusercontent.com/34915602/63591192-54406b00-c5ae-11e9-9496-299b26e527ce.png)
