### ISSUE TITLE
[FR] - templating to reduce yaml

### ISSUE THREAD

**Issue by jaburges** [thomasloven/lovelace-card-mod#93]
Hi there,
I wonder if its possible to template (like a custom:button-card)

I can create a standard set of CSS values, then call them from the `style`

```yaml
- type: custom:bar-card
  entity: sensor.blah
  show_icon: true
  style: |
    template: standard_button
```

custom_card_mod_templates:
  background_tile:
    style: |
      :host {
      --ha-card-background: var(--dwains-theme-primary);
      --ha-card-border-radius: 10px;
      --ha-card-box-shadow: 10px;
      --ha-card-font-weight: bold;
      --ha-card-opacity: 0.8;
    }
    ha-card {
      font-size: 10px; 
      color: var(--dwains-theme-names);
      icon-color: black;                
    }
    bar-card-value {
      font-size: 10px;
      color: var(--dwains-theme-names);
    }
    bar-card-content-bar {
      color: black;
    }
    ha-icon {
      color: var(--dwains-theme-grey);
    }
    bar-card-name {
      color: var(--dwains-theme-grey);
      font-size: 18px;
    }
    bar-card-card {
      padding: 14px;
    }
```
