### ISSUE TITLE
Style element and multiple nested shadow-roots inside same parent element?

### ISSUE THREAD

**Issue by mightymight88** [thomasloven/lovelace-card-mod#98]
My Home Assistant version: 2021.1.5

My lovelace configuration method (GUI or yaml): YAML

What I am doing:
Modifying the icon and border of the alarm state in the alarm card to be bigger. There's one parent element `ha-label-badge`. Inside the first shadow-root is an element I need to style `.label-badge`. Then there's a second shadow-root element nested under ha-label-badge > ha-icon called ha-svg-icon that I need to style as well.

What I expected to happen:
Be able to style both the .label-badge and ha-svg-icon elements. But am unable to use both $: and $: | under the same parent element.

What happened instead:
I have an error of `duplicated mapping key at line 19, column -116: $: ^` 

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
style:
  .: |
    #keypad {
      max-width: 75% !important;
    }
  ha-label-badge:
    $: |
      .label-badge {
        width: 3.5em;
        height: 3.5em;
        line-height: 3.5em;
      }
    $:
      ha-icon:
        $: |
          ha-svg-icon {
            width: 60px;
            height:60px;
          }

# End of code
```

Error messages from the browser console:
No errors in console as the configuration panel won't let me save the card until the duplicated mapping key at line 19, column -116: $: ^ is fixed.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
That's the old syntax. This should work:
```yaml
style:
  .: |
    #keypad {
      max-width: 75% !important;
    }
  ha-label-badge$: |
    .label-badge {
      width: 3.5em;
      height: 3.5em;
      line-height: 3.5em;
    }
  ha-label-badge$ha-icon$: |
    ha-svg-icon {
      width: 60px;
      height: 60px;
    }
```
Consider closing if that worked.
